---
title: "ctsem 2.0 introduction"
author: "Charles Driver"
date: "24 June 2016"
output: html_document
---


```{setup, include = FALSE, cache = FALSE, echo = FALSE}
library('ctsem')
library(knitr)
render_sweave()
set.seed(22)
opts_chunk$set(fig.path = 'figures/plots-', warning = FALSE, fig.align = 'center', width.cutoff = 80, fig.show = 'hold', eval = TRUE, echo = TRUE, message = FALSE, background = "white", prompt = FALSE, highlight = FALSE, comment = NA, tidy = FALSE, out.truncate = 80)
options(replace.assign = TRUE, width = 80, scipen = 12, digits = 3)


# setwd('C:\\Users\\driver\\Dropbox\\MPIB\\CT-SEM\\manual') #set this working directory!
Sys.setenv(TEXINPUTS = getwd(),
  BIBINPUTS = getwd(),
  BSTINPUTS = getwd())

Tpoints=5
n.manifest=2
n.TDpred=1
n.TIpred=3
n.latent=2
n.subjects=50
gm<-ctModel(type='omx', Tpoints=Tpoints,n.latent=n.latent,n.TDpred=n.TDpred,n.TIpred=n.TIpred,n.manifest=n.manifest,
  MANIFESTVAR=diag(0.5,2),
  TIPREDEFFECT=matrix(c(.5,0,0,-.5,0,0),nrow=2),
  TIPREDVAR=matrix(c(1,-.2,0, 0,1,0, 0,0,.5),nrow=3),
  TDPREDEFFECT=matrix(c(.1,-.2),nrow=2),
  TDPREDVAR=matrix(0,nrow=n.TDpred*(Tpoints-1),ncol=n.TDpred*(Tpoints-1)),
  TDPREDMEANS=matrix(rnorm(n.TDpred*(Tpoints-1),0,1),nrow=n.TDpred*(Tpoints-1)),
  LAMBDA=diag(1,2), 
  # DRIFT=matrix(c(-.6+rnorm(1,0,.15),-.2+rnorm(1,0,.1),.12+rnorm(1,0,.1),-.3+rnorm(1,0,.05)),nrow=2),
  DRIFT=matrix(c(-.3,.2,-.1,-.2),nrow=2),
  TRAITVAR=t(chol(matrix(c(4,3,3,4),nrow=2))),
  # T0TRAITEFFECT=diag(3,n.latent),
  DIFFUSION=matrix(c(.3,.1,0,.2),2),CINT=matrix(c(0,0),nrow=2),T0MEANS=matrix(0,ncol=1,nrow=2),
  T0VAR=diag(100,2))

cd<-ctGenerate(gm,n.subjects=50,burnin=300, dT=1,asymptotes=F,simulTDpredeffect = T)
checkm<-ctModel(type='stanct',n.latent=n.latent,n.manifest=n.manifest,n.TDpred=n.TDpred,n.TIpred=n.TIpred,LAMBDA=diag(n.latent))
long<-ctWideToLong(cd,Tpoints,n.manifest=checkm$n.manifest,manifestNames = checkm$manifestNames, 
  n.TDpred=n.TDpred,n.TIpred=n.TIpred,TDpredNames = checkm$TDpredNames,TIpredNames = checkm$TIpredNames)
long[is.na(long)]<-0
# fit<-ctStanFit(long,checkm,iter=500,chains=2,fit=T,plot=T,densehyper=F,noncentered=F,optimize=F,
#   vb=F,tol_rel_obj=.001,eta=1, kalman=T)
```
###Overview
ctsem allows for easy specification and fitting of a range of continuous and discrete time dynamic models, including multiple indicators (dynamic factor analysis), multiple, potentially higher order processes, and time dependent (varying) and independent (not varying) covariates. Classic longitudinal models like latent growth curves and latent change score models are also possible.  Version 1 of ctsem provided SEM based functionality by linking to the OpenMx software, allowing mixed effects models (random means but fixed regression and variance parameters) for multiple subjects. For version 2 of the \proglang{R} package \pkg{ctsem}, we include a Bayesian specification and fitting routine that uses the \pkg{Stan} probabilistic programming language, via the \pkg{rstan} package in R. This allows for all parameters of the dynamic model to individually vary, using an estimated population mean and variance, and any time independent covariate effects, as a prior. ctsem version 1 is documented in a forthcoming JSS publication (Driver, Voelkle, Oud, in press), and in R vignette form at https://cran.r-project.org/web/packages/ctsem/vignettes/ctsem.pdf , here we provide the basics for getting started with the new Bayesian approach.

###Subject Level Latent Dynamic model
This section describes the fundamental subject level model, and where appropriate, the name of the ctModel argument used to specify specific matrices.

The subject level dynamics are described by the following stochastic differential equation:
\begin{equation}
\label{eq:process1}
\mathrm{d}\eta(t) =
\bigg( 
A\eta(t) +
b +
M \chi(t)  
\bigg) \mathrm{d}t +
G \mathrm{d} W(t)  
\end{equation}

Vector $\eta(t)\in\mathbb{R}^{v}$ represents the state of the latent processes at time $t$. The matrix $A \in \mathbb{R}^{v \times v}$ represents the DRIFT matrix, with auto effects on the diagonal and cross effects on the off-diagonals characterizing the temporal relationships of the processes. 

The long term  level of processes $\eta(t)$ is determined by the continuous time intercept (CINT) vector $b \in\mathbb{R}^{v}$, which (in combination with $A$) determines the long-term level at which the processes fluctuate around.

Time dependent predictors $\chi(t)$ represent inputs to the system that vary over time and are independent of fluctuations in the system. The above equation shows a generalised form for time dependent predictors, that could be treated a variety of ways dependent on the assumed time course (or shape) of time dependent predictors. We use a simple impulse form, in which the predictors are treated as impacting the processes only at the instant of an observation occasion $u$. When necessary, the evolution over time can be modeled by extending the state matrices. 

\begin{equation}
\label{eq:spike}
\chi (t) = \sum_{ u \in U}  x_{u} \delta (t-t)     
\end{equation}

Here, time dependent predictors $x_u \in \mathbb{R}^{l}$ are observed at times $ u \in U \subset \mathbb{R}$. The Dirac delta function $\delta(t-t)$ is a generalized function that is $\infty$ at 0 and 0 elsewhere, yet has an integral of 1 (when 0 is in the range of integration). It is useful to model an impulse to a system, and here is scaled by the vector of time dependent predictors $x_u$.  The effect of these impulses on processes $\eta(t)$ is then $M\in \mathbb{R}^{v \times l}$ (TDPREDEFFECT). 

$W(t) \in \mathbb{R}^{v}$ represents independent Wiener processes, with a Wiener process being a random-walk in continuous time. $dW(t)$ is meaningful in the context of stochastic differential equations, and represents the stochastic error term, an infinitesimally small increment of the Wiener process. Lower triangular matrix $G \in \mathbb{R}^{v \times v}$ represents the effect of this noise on the change in  $\eta(t)$.  $Q$, where $Q = GG^\top$, represents the variance-covariance matrix of the diffusion process in continuous time. The DIFFUSION matrix in ctModel is essentially G, except off-diagonal elements of DIFFUSION specify Cholesky decomposed correlation values, rather than covariance.

###Subject level measurement model
The latent process vector $\eta(t)$ has measurement model:

\begin{equation}
\label{eq:measurement}
y(t) = \Lambda \eta(t) + h + \zeta(t)  
\quad \text{where } \zeta(t) \sim  \mathrm{N} (0, \Theta)
\end{equation}

$y (t)\in\mathbb{R}^{c}$ is the manifest variables, $\Lambda \in \mathbb{R}^{c \times v}$ is factor loadings (LAMBDA), $h \in\mathbb{R}^{c}$ is the manifest intercepts (MANIFESTMEANS), and  residual vector $\zeta \in \mathbb{R}^{c}$ has covariance matrix $\Theta \in\mathbb{R}^{c \times c}$. To specify $\Theta$ with ctModel, the lower-triangular MANIFESTVAR matrix is used, with standard deviations on the diagonal and Cholesky decomposed correlations in the off-diagonals.


###Install software and prepare data
Install ctsem software from github repository https://github.com/cdriveraus/ctsem .

```{install,eval=FALSE}
require('devtools')
install_github("ctsem",username='cdriveraus')
```

Prepare data in long format, each row containing one time point of data for one subject. We need a subject id column (named by default "id"), columns for manifest variables (the names of which must be given in the next step using ctModel), columns for time dependent predictors (these vary over time but have no model estimatedand are assumed to impact latent processes instantly - generally intervention or event dummy variables), and columns for time independent predictors (the value will be stable for each measurement of a particular subject). Relationships are estimated between time independent predictors and individually varying subject level parameters. 

```{data,echo=FALSE}
head(long,10)
```

###Model specification
Specify model using \code{ctModel(type="stanct",...)}. "stanct" specifies a continuous time model in Stan format, "standt" specifies discrete time, while "omx" is the classic \pkg{ctsem} behaviour and prepares an \pkg{OpenMx} model. Other arguments to ctModel proceed as normal, although many matrices are not relevant for the Stan formats, either because the between subject matrices have been removed, or because time dependent and independent predictors (covariates that either change over time or don't) are now treated as fixed regressors and only require effect (or design) matrices.

```{model}
checkm<-ctModel(type='stanct',
  n.latent=2, latentNames=c('eta1','eta2'),
  n.manifest=2, manifestNames=c('Y1','Y2'),
  n.TDpred=1, TDpredNames='TD1', 
  n.TIpred=3, TIpredNames=c('TI1','TI2','TI3'),
  LAMBDA=diag(2))
```

This generates a simple first order bivariate latent process model, with each process measured by a potentially noisy manifest variable. Additional complexity or restrictions may be added, the table below shows the basic arguments one may consider and their link to the dynamic model parameters. For more details see the ctsem help files or papers. Note that for the Stan implementation, ctModel requires variance covariance matrices (DIFFUSION, T0VAR, MANIFESTVAR) to be specified with standard deviations on the diagonal, and Cholesky decomposed correlations on the off diagonal. This is for computational reasons, and hopefully poses little concern for the user since in our experience these are most often set to be either free, or fixed to 0, which translates directly. 


| Argument |  Sign | Default | Meaning |
|---|---|----------|----------------------------------------------------------|
| n.manifest | \textit{c} || Number of manifest indicators per individual at each measurement occasion.|
| n.latent | \textit{v} || Number of latent processes.|
| LAMBDA | $\boldsymbol{\Lambda}$|| n.manifest $\times$ n.latent loading matrix relating latent to manifest variables.|
| manifestNames | | Y1, Y2, etc | n.manifest length character vector of manifest names.|
| latentNames | | eta1, eta2, etc | n.latent length character vector of latent names.|
| T0VAR | | free | lower tri n.latent $\times$ n.latent matrix of latent process initial cov.|
| T0MEANS | | free | n.latent $\times$ 1 matrix of latent process means at first time point, T0.|
| MANIFESTMEANS | $\boldsymbol{\tau}$ | free | n.manifest $\times$ 1 matrix of manifest means.|
| MANIFESTVAR | $\boldsymbol{\Theta}$ | free diag | lower triangular matrix of var / cov between manifests|
| DRIFT | \textbf{A} | free | n.latent $\times$ n.latent matrix of continuous auto and cross effects.| 
| CINT | $\boldsymbol{\kappa}$ | 0 | n.latent $\times$ 1 matrix of continuous intercepts.|
| DIFFUSION | $\textbf{Q}$ | free | lower triangular n.latent $\times$ n.latent matrix of diffusion variance / covariance.|
| n.TDpred | \textit{l} | 0 | Number of time dependent predictors in the dataset.|
| TDpredNames | | TD1, TD2, etc | n.TDpred length character vector of time dependent predictor names.|
| TDPREDEFFECT | $\textbf{M}$ | free | n.latent $\times$ n.TDpred matrix of effects from time dependent predictors to latent processes.|
| n.TIpred | \textit{p} | 0 | Number of time independent predictors.| 
| TIpredNames | | TI1, TI2, etc | n.TIpred length character vector of time independent predictor names.|
| TIPREDEFFECT | $\textbf{B}$ | free | n.latent $\times$ n.TIpred effect matrix of time independent predictors on latent processes.|

These matrices may all be specified using a combination of character strings to name free parameters, or numeric values to represent fixed parameters. 

The parameters subobject of the created model object shows the parameter specification that will go into Stan, including both fixed and free parameters, whether the parameters vary across individuals, how the parameter is transformed from a standard normal distribution (thus setting both priors and bounds), and whether that parameter is regressed on the time independent predictors.

```{model}
head(checkm$parameters,8)
```

One may modify the output model to either restrict between subject differences (set some parameters to fixed over subjects), alter the transformation used to determine the prior / bounds, or restrict which effects of time independent predictors to estimate. Plotting the original prior, making a change, and plotting the resulting prior, are shown here -- in this case we believe the latent process error for our first latent process, captured by row 1 and column 1 of the DIFFUSION matrix, to be very small, so restrict our prior accordingly to both speed and improve sampling.

```{transform}
par(mfrow=c(1,2))
ctStanPlotPriors(checkm,rows=11)
checkm$parameters$transform[11]<- 'log(exp((param)*1.5)+1)*2'
ctStanPlotPriors(checkm,rows=11)
```

The plots show the prior distribution for the population mean of DIFFUSION[1,1] in black, as well as two possible priors for the subject level parameters. The blue prior results from assuming the population mean is two standard deviations lower than the mean for our prior, and assuming that the population standard deviation is 1, which given our prior on population standard deviations is a truncated normal(0, 0.5) distribution, is also two sd's from the base of 0. To understand better, the pre-transformation population sd prior for all subject level parameters looks like:

```{sdprior}
sd<-rnorm(5000000,0,.5)
sd<-sd[sd>0]
plot(density(sd,bw=.01,n=50000),lwd=2)
```

Restrict between subject effects as desired. Unnecessary between subject effects will slow sampling, but be aware of the many parameter dependencies in these models -- restricting one parameter may sometimes lead to variation from it showing up elsewhere.

```{restrictbetween}
checkm$parameters[25:28,]
checkm$parameters[25:28,]$indvarying<-FALSE
```

Also restrict time independent predictor effects in a similar way, for similar reasons. In this case, the only adverse effects of restriction are that the relationship between the predictor and variables will not be estimated, but the subject level parameters themselves should not be very different, as they are still freely estimated. Note that such effects are only estimated for individually varying parameters anyway -- so after the above change there is no need to set the tipredeffect to FALSE for the T0VAR variables, it is assumed. Instead, we restrict the tipredeffects on all parameters, and free them only for the auto effect of the first latent process.

```{restricttipred}
checkm$parameters[,c('TI1_effect','TI2_effect','TI3_effect')]<-FALSE
checkm$parameters[7,c('TI1_effect','TI2_effect','TI3_effect')]<-TRUE
```

###Model fitting
Once model specification is complete, the model is fit to the data using the ctStanFit function as follows -- depending on the data, model, and number of iterations requested, this can take anywhere from a few minutes to days. Current experience suggests 500 iterations is enough to get an idea of what is going on, but more are necessary for robust inference.

```{fitting,eval=FALSE}
fit<-ctStanFit(long,checkm,iter=500,chains=2,fit=T,plot=T,
  densehyper=F)
```

The plot argument allows for plotting of sampling chains in real time, which is useful for slow models to ensure that sampling is proceeding in a functional manner. The densehyper argument may be set to TRUE to estimate the priors for the correlation between parameters, which may allow somewhat better priors for subject level parameters to be estimated, but also tends to slow down sampling substantially. 

###Output
After fitting, the standard rstan output functions such as summary and extract are available, and the shinystan package provides an excellent browser based interface. The parameters which are likely to be of most interest in the output all begin with an "output" prefix, followed by either "hmean" for hyper (population) mean, or "hsd" for hyper standard deviation. Subject specific parameters are denoted by the matrix they are from, then the first index represents the subject id, followed by standard matrix notation. For example, the 2nd row and 1st column of the DRIFT matrix for subject 8 is "DRIFT[8,2,1]". Parameters are all returned in the form used for internal calculations -- that is, variance covariance matrices are returned as such, rather than the lower-triangular standard deviation and cholesky correlation matrices required for input. The exception to this are the time independent predictor effects, prefixed with "output\_tip\_", for which a linear effect of a change of 1 on the predictor is approximated. So although "output\_tip\_TI1" is only truly linear with respect to internal parameterisations, we approximate the linear effect by averaging the effect of a score of +1 or -1 on the predictor, on the population mean. For any subject that substantially differs from the mean, or simply when precise absolute values of the effects are required (as opposed to general directions), they will need to be calculated manually.

```{output,eval=FALSE}
library("shinystan")
launch_shinystan(fit)
```

###Convert from wide data
Data can be converted from the wide format data used for the OpenMx based ctsem approach as follows:

```{convertdata}
#specify some ctModel called mymodel, including a Tpoints argument
long<-ctWideToLong(mydata,mymodel$Tpoints,
n.manifest=mymodel$n.manifest, manifestNames = mymodel$manifestNames, 
  n.TDpred=mymodel$n.TDpred, TDpredNames = mymodel$TDpredNames,
  n.TIpred=mymodel$n.TIpred, TIpredNames = mymodel$TIpredNames)
