# Is the committed man/ and NAMESPACE what the R sources say it should be?
#
# Run `Rscript dev/document.R` first; this compares the result against what is
# committed. The comparison ignores layout, because layout belongs to roxygen2
# and changes between its versions -- 8.1.0 rewrote every multi-symbol
# `importFrom()` into a multi-line form, which a plain `git diff` reports as
# documentation drift in a repository where nothing has drifted. Pinning the
# generator to dodge that only moves the failure to the day the pin goes
# stale, which is how this check spent a fortnight red.
#
# So the question asked here is the one that matters to a reader of the help
# page: does it still say what the source says? A new file, a removed file, or
# a changed word each fails.
#
# Whitespace is dropped entirely rather than collapsed to a single space.
# Collapsing is not layout-independent, which a test of this script caught:
# 8.1.0 writing an `importFrom()` over three lines collapses to
# "importFrom(pkg, sym )" against 8.0.0's "importFrom(pkg,sym)", and a
# rewrapped \usage block differs the same way. The price is that a change
# which is only whitespace inside prose does not register here -- which is
# not a change a reader of the rendered page sees either.

norm <- function(lines) {
  # The generator's banner names its own version, so it differs whenever the
  # runner's roxygen2 does, and says nothing about the content below it.
  lines <- lines[!grepl("^[%#] Generated by roxygen2", lines)]
  gsub("[[:space:]]+", "", paste(lines, collapse = ""))
}

committed <- function(path) {
  out <- suppressWarnings(system2(
    "git", c("show", shQuote(paste0("HEAD:", path))),
    stdout = TRUE, stderr = FALSE))
  if (is.null(attr(out, "status"))) out else NULL
}

# `git ls-files` rather than a directory listing: a generated file that is
# present and untracked is as much drift as one that changed, and only the
# index knows which those are. man/figures/ holds README images, which no
# roxygen run writes.
tracked <- system2("git", c("ls-files", "--", "man/*.Rd", "NAMESPACE"),
                   stdout = TRUE)
present <- c(sort(list.files("man", pattern = "[.]Rd$", full.names = TRUE)),
             "NAMESPACE")
present <- gsub("\\\\", "/", present)

added <- setdiff(present, tracked)
removed <- setdiff(tracked, present)
changed <- character()
for (p in intersect(tracked, present)) {
  old <- committed(p)
  if (is.null(old)) next
  new <- readLines(p, warn = FALSE)
  if (!identical(norm(old), norm(new))) changed <- c(changed, p)
}

cat(sprintf(
  "roxygen2 %s: %d generated files, %d new, %d removed, %d changed\n",
  as.character(packageVersion("roxygen2")), length(present),
  length(added), length(removed), length(changed)))

if (!length(c(added, removed, changed))) {
  cat("DOCS_CURRENT\n")
  quit(status = 0)
}

# GitHub serves a failed run's log only to someone who can write to the
# repository, and serves annotations to anyone. So the names go in one.
none <- function(x) if (length(x)) paste(x, collapse = " ") else "none"
cat(sprintf(paste0("::error title=Documentation is stale::regenerate with ",
                   "dev/document.R and commit. new: %s | removed: %s | ",
                   "changed: %s\n"),
            none(added), none(removed), none(changed)))
for (p in changed) {
  cat("\n#### ", p, "\n", sep = "")
  d <- system2("git", c("--no-pager", "diff", "--", shQuote(p)), stdout = TRUE)
  cat(head(d, 40), sep = "\n")
}
quit(status = 1)
