"""
Compile the filter for the model shapes ctsem actually generates, at package
build time rather than in the user's first fit.

# Why this can work at all

A model's type carries its transform closures: `EKFParameters{RT,PT,UT,TT,AX,FV}`
where `RT` holds one closure type per free cell. Until recently each closure was
compiled from source with its parameter index baked in, so `param[3]` and
`param[4]` were *different types* -- two models identical but for which
parameter sits where shared no compiled code at all, and every new model paid
twenty to seventy seconds on its first evaluation, every session.

`_regular_transform_closure` lifted the index out into a closed-over value, so a
closure's type now depends only on its *template*. ctsem writes a handful of
templates, which is what makes precompiling worth anything: a model is typed by
its matrix dimensions and free-parameter count, not by its parameter layout, so
one compiled shape covers every model of those dimensions.

# The shapes are captured, not written

`precompile_shapes.jl` holds the exact parameter tables ctsem's model writer
produces, generated by `tools/generate-precompile-shapes.R`. That indirection is
load-bearing. The first version of this file hand-wrote a plausible-looking
model instead, and it was wrong in four ways at once -- `PARS` first rather than
last, `JAx` sharing DRIFT's parameter numbers, different templates on `T0VAR`
and `MANIFESTMEANS` -- so it compiled a shape no fit ever asks for. It cost 100
seconds of build time and saved nothing, and nothing said so.

`ctsem_shape_is_precompiled` is how that stays honest: it answers whether a spec
built from given columns has one of the types built here, and the R suite asks
it about a real model.

# What it does not cover

Matrix dimensions are part of the ComponentArrays axis type, so a shape not
listed still compiles on first use. Nonlinear models write their own transform
expressions and cannot be predicted from here at all.

# Failure must not be fatal

This is an optimisation. A broken workload degrades to "nothing was
precompiled", never to a package that will not load -- hence the `try`. Set
`JULIA_CTSEM_PRECOMPILE=0` to skip it, which is worth doing while editing the
engine: the cache key is a content hash, so every edit pays the build again.
"""

include("precompile_shapes.jl")

"""
The `EKFParameters` type each precompiled shape produced.

Recorded because "did precompilation still cover real models?" has no other
symptom: when a template drifts the shapes silently stop matching and first fits
are merely slow again. `ctsem_shape_is_precompiled` reads this.
"""
const _PRECOMPILE_SHAPE_TYPES = Dict{Symbol,Any}()

"""Build the `EKFParameters` for one captured shape."""
function _precompile_spec(name::Symbol)
    s = _PRECOMPILE_SHAPES[name]
    spec = ekf_from_columns(s.matrix, s.row, s.col, s.parnumber, s.value,
        s.transform, s.predicttransform, s.updatetransform, s.tdtransform)
    _PRECOMPILE_SHAPE_TYPES[name] = typeof(spec)
    return spec, s
end

"""
    _precompile_evaluate(spec, s)

Pull one built shape through value, gradient and the Laplace route over a tiny
dataset: two subjects, because one would not exercise the subject loop, and four
rows each, because the tape is per-row and fewer would prove nothing.

Separate from `_precompile_spec` because the caller must re-enter the world
between them -- see the workload block below.
"""
function _precompile_evaluate(spec, s)
    # The manifest count is not in the table as such; LAMBDA's row extent is it.
    nmanifest = maximum(s.row[i] for i in eachindex(s.matrix) if s.matrix[i] == "LAMBDA")
    nsubjects, nobs = 2, 4
    nrows = nsubjects * nobs
    subject_starts = [1 + (i - 1) * nobs for i in 1:nsubjects]
    times = repeat(collect(0.0:(nobs - 1)), nsubjects)
    data = [0.3 * sin(1.7 * t + 0.4 * m) for m in 1:nmanifest, t in 1:nrows]

    objective = ctsem_objective(spec, subject_starts, times, data)
    values = fill(0.1, s.npar)

    # The optimiser, not just the objective. Measured on a first fit after the
    # objective was already precompiled: building it cost 1.0s and *optimising*
    # cost 6.9s, of which about five were Optim's line search, the `fg!`
    # closure and the chunk tuner specialising on this objective type. Two
    # iterations reach all of it; more would only add build time.
    #
    # `tune_chunks=false` because the tuner times a ladder of chunk counts, and
    # timings taken during a build say nothing about the machine that will run
    # the fit -- it is the one part of this that must not be precompiled with
    # its answer baked in.
    if isempty(s.re_index)
        # No random-effect block means the augmented route, which is ctsem's
        # default: the state carries the random effects and the Laplace wrapper
        # never appears.
        ctsem_evaluate(objective, values; gradient=true)
        ctsem_optimize(objective, values; maxiter=2, gradient_method=:adjoint,
            tune_chunks=false)
    else
        laplace = ctsem_laplace_objective(objective; re_index=s.re_index,
            sd_index=s.sd_index, cor_index=s.cor_index, sd_scale=s.sd_scale)
        ctsem_laplace_evaluate(laplace, values; gradient=true)
        ctsem_laplace_optimize(laplace, values; maxiter=2, tune_chunks=false)
    end
    return nothing
end

export ctsem_shape_is_precompiled
"""
    ctsem_shape_is_precompiled(matrix, row, col, parnumber, value, transform,
                               predicttransform, updatetransform, tdtransform)

Does a model built from these columns have one of the types compiled into the
package image?

This is the only observable difference between precompilation working and
precompilation quietly covering nothing: both load fine, and only one of them
makes the first fit fast. The R suite asks this about a real model so that a
drift in what `ctModelWriter` emits fails a test rather than a stopwatch.
"""
function ctsem_shape_is_precompiled(matrix, row, col, parnumber, value, transform,
    predicttransform, updatetransform, tdtransform)
    spec = ekf_from_columns(matrix, row, col, parnumber, value, transform,
        predicttransform, updatetransform, tdtransform)
    return typeof(spec) in values(_PRECOMPILE_SHAPE_TYPES)
end

using PrecompileTools: @compile_workload

# `@compile_workload` rather than a bare call, because a bare call is not
# enough: running the workload at build time *compiles* the code but does not
# mark it for serialisation, so the image would get the transform cache and none
# of the machine code. The macro opens Julia's newly-inferred collection window
# around the block and attaches what it catches.
#
# Two `invokelatest` calls, not one, and this is the whole trick. `eval`ing the
# transform closures inside `_precompile_spec` defines methods in a world newer
# than the frame that called it, and `invokelatest` fixes the world at *call*
# time -- so a single wrapping call cannot see the closures its own callee just
# created. The first version did exactly that and failed with `MethodError: ...
# The applicable method may be too new`, which the `try` then swallowed.
@compile_workload begin
    if get(ENV, "JULIA_CTSEM_PRECOMPILE", "1") != "0"
        for name in keys(_PRECOMPILE_SHAPES)
            try
                built = Base.invokelatest(_precompile_spec, name)
                Base.invokelatest(_precompile_evaluate, built...)
            catch err
                err isa InterruptException && rethrow()
                @debug "ContinuousTimeSEM: precompile workload skipped" name err
            end
        end
    end
end
