# GENERATED by tools/generate-precompile-shapes.R -- do not edit by hand.
#
# The exact parameter tables ctsem's model writer produces for the shapes
# listed in that script, captured so the engine can compile for them at build
# time. Regenerate after any change to what `.ctJuliaPrepare` emits; a stale
# table costs nothing but correctness of the *optimisation* -- the shapes
# simply stop matching and first fits get slow again, silently. The test
# `precompiled shapes still match what ctsem sends` is what catches that.

const _PRECOMPILE_SHAPES = (
    one_latent_augmented = (
        matrix = ["PARS", "T0MEANS", "T0MEANS", "LAMBDA", "DRIFT", "DIFFUSION", "MANIFESTVAR", "MANIFESTMEANS", "CINT", "T0VAR", "T0VAR", "T0VAR", "T0VAR", "JAx", "JAx", "JAx", "JAx", "Jy", "Jy", "DRIFT", "DRIFT", "DRIFT", "DIFFUSION", "DIFFUSION", "DIFFUSION", "CINT", "LAMBDA"],
        row = Int[1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 1, 2, 2, 1, 2, 2, 2, 1],
        col = Int[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 2, 1, 2, 2, 1, 2, 1, 2],
        parnumber = Int[0, 1, 6, 0, 2, 3, 4, 0, 0, 5, 0, 0, 7, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        value = Float64[ 0, NaN, NaN,  1, NaN, NaN, NaN, NaN,  0, NaN,  0,  0, NaN, NaN,  0,  0,  0,  1, 10,  0,  0,  0,  0,  0,  0,  0,  0],
        transform = ["", "10 * param[1]", "param[6]", "", "-(1e-06 + 2 * log1p_exp(-(2 * param[2])))", "10 * log1p_exp(2 * param[3]) + 1e-10", "1e-10 + 5 * log1p_exp(2 * param[4])", "0 + 10 * (param * 1 + 0)", "", "1e-10 + 5 * log1p_exp(2 * param[5])", "", "", "1 * (1e-10 + 1 * log1p_exp(2 * param[7] - 1))", "-(1e-06 + 2 * log1p_exp(-(2 * param[2])))", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        predicttransform = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        updatetransform = ["", "", "", "", "", "", "", "10*state[2]", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        tdtransform = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        npar = 7,
        re_index = Int[],
        sd_index = Int[],
        cor_index = Int[],
        sd_scale = Float64[],
    ),
    two_latent_augmented = (
        matrix = ["PARS", "T0MEANS", "T0MEANS", "T0MEANS", "LAMBDA", "LAMBDA", "LAMBDA", "LAMBDA", "DRIFT", "DRIFT", "DRIFT", "DRIFT", "DIFFUSION", "DIFFUSION", "DIFFUSION", "DIFFUSION", "MANIFESTVAR", "MANIFESTVAR", "MANIFESTVAR", "MANIFESTVAR", "MANIFESTMEANS", "MANIFESTMEANS", "CINT", "CINT", "T0VAR", "T0VAR", "T0VAR", "T0VAR", "T0VAR", "T0VAR", "T0VAR", "T0VAR", "T0VAR", "JAx", "JAx", "JAx", "JAx", "JAx", "JAx", "JAx", "JAx", "JAx", "Jy", "Jy", "Jy", "Jy", "Jy", "Jy", "DRIFT", "DRIFT", "DRIFT", "DRIFT", "DRIFT", "DIFFUSION", "DIFFUSION", "DIFFUSION", "DIFFUSION", "DIFFUSION", "CINT", "LAMBDA", "LAMBDA"],
        row = Int[1, 1, 2, 3, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 2, 1, 2, 1, 1, 2, 2, 1, 2, 3, 3, 3, 1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 1, 1, 2, 2, 2, 1, 2, 3, 3, 3, 1, 2, 3, 3, 3, 3, 1, 2],
        col = Int[1, 1, 1, 1, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 1, 1, 1, 1, 2, 1, 2, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 3, 3, 1, 2, 3, 3, 3, 1, 2, 3, 1, 3, 3],
        parnumber = Int[0, 1, 2, 16, 0, 0, 0, 0, 3, 4, 5, 6, 7, 0, 8, 9, 10, 0, 0, 11, 0, 12, 0, 0, 13, 0, 14, 15, 0, 0, 0, 0, 17, 3, 4, 0, 5, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        value = Float64[ 0, NaN, NaN, NaN,  1,  0,  0,  1, NaN, NaN, NaN, NaN, NaN,  0, NaN, NaN, NaN,  0,  0, NaN, NaN, NaN,  0,  0, NaN,  0, NaN, NaN,  0,  0,  0,  0, NaN, NaN, NaN,  0, NaN, NaN,  0,  0,  0,  0,  1,  0, 10,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        transform = ["", "10 * param[1]", "10 * param[2]", "param[16]", "", "", "", "", "-(1e-06 + 2 * log1p_exp(-(2 * param[3])))", "param[4]", "param[5]", "-(1e-06 + 2 * log1p_exp(-(2 * param[6])))", "10 * log1p_exp(2 * param[7]) + 1e-10", "", "2/(1 + exp(-param[8])) - 1", "10 * log1p_exp(2 * param[9]) + 1e-10", "1e-10 + 5 * log1p_exp(2 * param[10])", "", "", "1e-10 + 5 * log1p_exp(2 * param[11])", "0 + 10 * (param * 1 + 0)", "10 * param[12]", "", "", "1e-10 + 5 * log1p_exp(2 * param[13])", "", "2/(1 + exp(-param[14])) - 1", "1e-10 + 5 * log1p_exp(2 * param[15])", "", "", "", "", "1 * (1e-10 + 1 * log1p_exp(2 * param[17] - 1))", "-(1e-06 + 2 * log1p_exp(-(2 * param[3])))", "param[4]", "", "param[5]", "-(1e-06 + 2 * log1p_exp(-(2 * param[6])))", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        predicttransform = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        updatetransform = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "10*state[3]", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        tdtransform = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        npar = 17,
        re_index = Int[],
        sd_index = Int[],
        cor_index = Int[],
        sd_scale = Float64[],
    ),
    one_latent_laplace = (
        matrix = ["PARS", "T0MEANS", "LAMBDA", "DRIFT", "DIFFUSION", "MANIFESTVAR", "MANIFESTMEANS", "CINT", "T0VAR", "JAx", "Jy"],
        row = Int[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        col = Int[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        parnumber = Int[0, 1, 0, 2, 3, 4, 5, 0, 6, 2, 0],
        value = Float64[ 0, NaN,  1, NaN, NaN, NaN, NaN,  0, NaN, NaN,  1],
        transform = ["", "10 * param[1]", "", "-(1e-06 + 2 * log1p_exp(-(2 * param[2])))", "10 * log1p_exp(2 * param[3]) + 1e-10", "1e-10 + 5 * log1p_exp(2 * param[4])", "10 * param[5]", "", "1e-10 + 5 * log1p_exp(2 * param[6])", "-(1e-06 + 2 * log1p_exp(-(2 * param[2])))", ""],
        predicttransform = ["", "", "", "", "", "", "", "", "", "", ""],
        updatetransform = ["", "", "", "", "", "", "", "", "", "", ""],
        tdtransform = ["", "", "", "", "", "", "", "", "", "", ""],
        npar = 7,
        re_index = Int[5],
        sd_index = Int[7],
        cor_index = Int[],
        sd_scale = Float64[1],
    ),
    two_latent_laplace = (
        matrix = ["PARS", "T0MEANS", "T0MEANS", "LAMBDA", "LAMBDA", "LAMBDA", "LAMBDA", "DRIFT", "DRIFT", "DRIFT", "DRIFT", "DIFFUSION", "DIFFUSION", "DIFFUSION", "DIFFUSION", "MANIFESTVAR", "MANIFESTVAR", "MANIFESTVAR", "MANIFESTVAR", "MANIFESTMEANS", "MANIFESTMEANS", "CINT", "CINT", "T0VAR", "T0VAR", "T0VAR", "T0VAR", "JAx", "JAx", "JAx", "JAx", "Jy", "Jy", "Jy", "Jy"],
        row = Int[1, 1, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 2, 1, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2],
        col = Int[1, 1, 1, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 1, 1, 1, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
        parnumber = Int[0, 1, 2, 0, 0, 0, 0, 3, 4, 5, 6, 7, 0, 8, 9, 10, 0, 0, 11, 12, 13, 0, 0, 14, 0, 15, 16, 3, 4, 5, 6, 0, 0, 0, 0],
        value = Float64[ 0, NaN, NaN,  1,  0,  0,  1, NaN, NaN, NaN, NaN, NaN,  0, NaN, NaN, NaN,  0,  0, NaN, NaN, NaN,  0,  0, NaN,  0, NaN, NaN, NaN, NaN, NaN, NaN,  1,  0,  0,  1],
        transform = ["", "10 * param[1]", "10 * param[2]", "", "", "", "", "-(1e-06 + 2 * log1p_exp(-(2 * param[3])))", "param[4]", "param[5]", "-(1e-06 + 2 * log1p_exp(-(2 * param[6])))", "10 * log1p_exp(2 * param[7]) + 1e-10", "", "2/(1 + exp(-param[8])) - 1", "10 * log1p_exp(2 * param[9]) + 1e-10", "1e-10 + 5 * log1p_exp(2 * param[10])", "", "", "1e-10 + 5 * log1p_exp(2 * param[11])", "10 * param[12]", "10 * param[13]", "", "", "1e-10 + 5 * log1p_exp(2 * param[14])", "", "2/(1 + exp(-param[15])) - 1", "1e-10 + 5 * log1p_exp(2 * param[16])", "-(1e-06 + 2 * log1p_exp(-(2 * param[3])))", "param[4]", "param[5]", "-(1e-06 + 2 * log1p_exp(-(2 * param[6])))", "", "", "", ""],
        predicttransform = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        updatetransform = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        tdtransform = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        npar = 17,
        re_index = Int[12],
        sd_index = Int[17],
        cor_index = Int[],
        sd_scale = Float64[1],
    ),
)

