#' ctJagsFit
#'
#' Fits a ctsem model specified via \code{\link{ctModel}} with type either 'stanct' or 'standt', using Bayseian inference software
#' Jags. 
#' 
#' @param datalong long format data containing columns for subject id, manifest variables, 
#' any time dependent (i.e. varying within subject) predictors, 
#' and any time independent (not varying within subject) predictors.
#' @param ctstanmodelobj model object as generated by \code{\link{ctModel}} with type='stanct' or 'standt'.
#' @param kalman logical indicating whether or not to integrate over latent states using a Kalman filter. 
#' Generally recommended to set TRUE.
#' @param densehyper logical indicating whether to estimate a prior for correlations between parameters, or fix it to 0.
#' Samples much faster if set to FALSE, but setting TRUE may improve estimation of priors for subject level parameters.
#' @param fit If TRUE, fit specified model using Stan, if FALSE, return stan model object without fitting.
#' @param noncentered if FALSE, sample subject level parameters directly, if TRUE, sample subject level parameters as
#' deviations from the estimated population mean. TRUE seems to result in somewhat more effective sampling, 
#' based on limited testing.
#' @param optimize if TRUE, use Stan's optimizer for maximum a posteriori estimates. Not recommended unless
#' no parameters vary across subjects.
#' @param vb if TRUE, use Stan's variational approximation. Presently experimental and not recommended.
#' @param iter number of iterations, half of which will be devoted to warmup.
#' @param chains number of chains to sample.
#' @export
ctJagsFit<-function(datalong, ctstanmodelobj, iter=1000, kalman=TRUE, binomial=FALSE, 
  fit=TRUE, chains=3,...){
 
  noncentered=TRUE
  
  #read in ctmodel values
  ctspec<-ctstanmodelobj$parameters
  
  if(kalman==FALSE) {
    message('ATTENTION: T0VAR matrix is ignored when kalman=FALSE \n')
    ctspec<-ctspec[-which(ctspec$matrix %in% 'T0VAR'),]
    if(any(!is.na(ctspec[ctspec$matrix %in% 'T0MEANS','value']))) message('ATTENTION: Some T0MEANS are fixed - may be problematic when kalman=FALSE \n')
  }
  
  n.latent<-ctstanmodelobj$n.latent
  n.manifest<-ctstanmodelobj$n.manifest
  n.TDpred<-ctstanmodelobj$n.TDpred
  n.TIpred<-ctstanmodelobj$n.TIpred
  
  manifestNames<-ctstanmodelobj$manifestNames
  latentNames<-ctstanmodelobj$latentNames
  TDpredNames<-ctstanmodelobj$TDpredNames
  TIpredNames<-ctstanmodelobj$TIpredNames
  id<-ctstanmodelobj$subjectIDname
  timeName<-ctstanmodelobj$timeName
  continuoustime<-ctstanmodelobj$continuoustime
  indvarying<-ctspec$indvarying
  nindvarying<-sum(indvarying)
  nparams<-sum(is.na(ctspec$value))
  
  
  #data checks
  if(any(is.na(as.numeric(datalong[,id])))) stop('id column may not contain NA\'s or character strings!')
  
  #fit spec checks
  if(binomial & any(kalman)) stop('Binomial observations only possible with kalman=FALSE')
  
  
  T0check<-1
  for(i in 2:nrow(datalong)){
    T0check<-c(T0check, ifelse(datalong[,'id'][i] != datalong[,'id'][i-1], 1, 0))
  }
  
  if(any(is.na(datalong[,timeName]))) stop('Missing "time" column!')
  
  #check id and calculate intervals
  oldsubi<-0
  dT<-rep(-1,length(datalong[,timeName]))
  # intervalChange<-dT
  for(rowi in 1:length(datalong[,timeName])) {
    subi<-datalong[rowi,id]
    if(rowi==1 && subi!=1) stop('subject id column must ascend from 1 to total subjects without gaps')
    if(oldsubi!=subi && subi-oldsubi!=1) stop('subject id column must ascend from 1 to total subjects without gaps')
    if(continuoustime==TRUE){
      if(subi - oldsubi == 1) dT[rowi]<-0
      if(subi - oldsubi == 0) dT[rowi]<-datalong[rowi,timeName] - datalong[rowi-1,timeName]
      # if(subi!=oldsubi) intervalChange[rowi] <-  0
      # if(subi==oldsubi && dT[rowi] != dT[rowi-1]) intervalChange[rowi] <- 1
      # if(subi==oldsubi && dT[rowi] == dT[rowi-1]) intervalChange[rowi] <- 0
    }
    oldsubi<-subi
  }
  
  
  if(n.TDpred > 0) {
    datalong[,TDpredNames][is.na(datalong[,TDpredNames])] <-0 ## temporary fix for missingness
    if(any(is.na(datalong[,TDpredNames]))) stop('Missingness in TDpreds!')
  }
  if(n.TIpred > 0) {
    if(n.TIpred > 0) tipreds <- datalong[match(unique(datalong[,id]),datalong[,id]),TIpredNames,drop=FALSE]
    if(any(is.na(tipreds))) stop('Missingness in TIpreds!')
  }
  
  datalong[is.na(datalong)]<-99999 #missing data
  
  if(n.TDpred > 0) tdpreds <- datalong[,TDpredNames,drop=FALSE]
  
  nsubjects <- length(unique(datalong[, 'id'])) 
  
  checkvarying<-function(matrixnames,yesoutput,nooutput=''){#checks if a matrix is set to individually vary in ctspec
    out<-nooutput
    if(any(ctspec$indvarying[ctspec$matrix %in% matrixnames])) out<-yesoutput
    return(out)
  }
  
  
browser()
  stanmodelobj <- paste0('
    
model {
    
hypermeans[1:nparams]~dnorm(0,1)
    
    ',if(any(ctspec$indvarying)) paste0('
      for(i in 1:nindvarying){ hypersd[i] ~ dnorm(0,1)}
      for(i in 1:nhypercorrpars){ hypercorrpars[i] ~ dnorm(0,1)}
      for(i in 1:(nindvarying*nsubjects)){ indparamsbase[i]~dnorm(0,1)}

      parcount <- 0
for(coli in 1:nindvarying){
      for(rowi in (coli+1):nindvarying){
      parcount <- parcount+1
      hypercorr[rowi,coli] <- 2/(1+exp(hypercorrpars[parcount]))-1 
      hypercorr[coli,coli] <- hypersd[rowi] * sdscale[rowi]
      mscale[rowi,coli] <- 0
      mscale[coli,coli] <-hypercorr[rowi,coli]
      mscale[coli,rowi] <- 0
      mcholcor[rowi,coli] <-  hypercorr[rowi,coli]
      mcholcor[coli,rowi] <-0
      }
}

mcholcor[1,1]<-1

',if(nindvarying>1) paste0(
'for(rowi in 2:nindvarying){
for(coli in 1:(rowi-1)){
tempsum[rowi,coli] = mcholcor[rowi,coli]^2
}
mcholcor2[rowi,rowi]=sqrt(abs(1-sum(tempsum[rowi,])))
}
  '),'

    paramchol <- mscale %*% mcholcor2

'),'

for(subjecti in 1:nsubjects) { indparams[subjecti,1:nindvarying]<- paramchol %*% indparamsbase[(1+(subjecti-1)*nindvarying):(subjecti*nindvarying)] }

    ',paste0(unlist(lapply(1:nrow(ctspec),function(rowi) {
      
      x<-paste0(
        checkvarying(ctspec[rowi,'matrix'],'for(subjecti in 1:nsubjects) {'),
        ctspec[rowi,'matrix'], checkvarying(ctspec[rowi,'matrix'],'[subjecti,','[1,'), ctspec[rowi,'row'], 
        if(ctspec[rowi,'matrix'] %in% c('LAMBDA','DRIFT','DIFFUSION',
          'MANIFESTVAR', 'TDPREDEFFECT', 'T0VAR')) paste0(' , ', ctspec[rowi,'col']),
        ']') 
      
      y<- paste0('(',
        if(is.na(ctspec[rowi,'value']) & (noncentered | !ctspec$indvarying[rowi])) paste0('hypermeans[',which(ctspec$param[is.na(ctspec$value)] == ctspec$param[rowi]),']'),
        if(ctspec[rowi,'indvarying'] & noncentered) ' + ',
        if(ctspec[rowi,'indvarying']) paste0('indparams[subjecti,',which(ctspec[ctspec$indvarying,'param']==ctspec[rowi,'param']),']')
        ,')')
      
      if(!is.na(ctspec[rowi,'value'])) out<-paste0(x,' = ',ctspec[rowi,'value'],' \n')
      
      if(!is.na(ctspec$transform[rowi]) & is.na(ctspec$value[rowi])) out<-paste0(
        x, ' <- ', gsub('param',y,ctspec$transform[rowi]),'} \n')
      return(out)
      })),collapse=''),'


       ',if(binomial==FALSE) paste0(
         'for(individual in 1:',checkvarying('MANIFESTVAR','nsubjects','1'),'){  MANIFESTVAR[individual] <- inverse(MANIFESTVAR[individual] %*% t(MANIFESTVAR[individual])) }
         '),'
    
    for(individual in 1:',checkvarying('DIFFUSION','nsubjects','1'),'){ DIFFUSION[individual] <- DIFFUSION[individual] %*% t(DIFFUSION[individual])}
    for(individual in 1:',checkvarying('T0VAR','nsubjects','1'),'){ T0VAR[individual] <- inverse(T0VAR[individual]  %*% t(T0VAR[individual]))}
    
    ',if(continuoustime==TRUE) paste0('
      for(individual in 1:',checkvarying('DRIFT','nsubjects','1'),') {
      invDRIFT[individual] = inverse(DRIFT[individual])

     for (i in 1:nlatent){
        for (j in 1:nlatent){
        for (k in 1:nlatent){
        for (l in 1:nlatent){
        DRIFTHATCH[individual, p*(i-1)+k, q*(j-1)+l] <- DRIFT[individual,i,j] * IIlatent[k,l] + DRIFT[individual,k,l] * IIlatent[i,j]
        }
        }
        }
        }
      }
      
      for(individual in 1:',checkvarying(c('DIFFUSION','DRIFT'),'nsubjects','1'),'){
      for(rowi in 1:nlatent){
      for(coli in 1:nlatent){
      DIFFUSIONvec[rowi+coli] = DIFFUSION[individual,rowi,coli]
}}
      asymDIFFUSIONvec[individual] =  -inverse(DRIFTHATCH[individual]) %*% DIFFUSIONvec
      for(drowi in 1:nlatent) {
      for(dcoli in 1:nlatent){
      asymDIFFUSION[individual,drowi,dcoli] =  asymDIFFUSIONvec[individual,drowi+(dcoli-1)*nlatent]
      }}
      }
      '),
    
    if(continuoustime==FALSE) paste0('
      for(individual in 1:',checkvarying(c('DIFFUSION','DRIFT'),'nsubjects','1'),'){
      asymDIFFUSIONvec[individual] = (diag_matrix(rep_vector(1, nlatent*nlatent)) - kron_prod(DRIFT[individual],DRIFT[individual])) * 
      to_vector(DIFFUSION[individual])
      for(drowi in 1:nlatent) {
      for(dcoli in 1:nlatent){
      asymDIFFUSION[individual][drowi,dcoli] =  asymDIFFUSIONvec[individual][drowi+(dcoli-1)*nlatent]
      }}
      }
      '),'


',if(kalman==FALSE) paste0('

  dt = dT[1]
  
  for(rowi in 1:ndatapoints){

  int whichobs[nobs_y[rowi]]
  whichobs = whichobs_y[rowi[1:nobs_y[rowi]]
  subjecti = subject[rowi]
  etarow = rowi-subjecti
  
  ',if(continuoustime==TRUE) paste0('if(T0check[rowi]==0){
    intervalChange = if_else(dT[rowi] != dt,1,0) 
      dt = dT[rowi]

    if(intervalChange==1 ',checkvarying('DRIFT',' || T0check[rowi-1]==1'),')', 
      'discreteDRIFT= mexp(DRIFT',checkvarying('DRIFT','[subjecti]','[1]'),' * dT[rowi])
    if(intervalChange==1 ',checkvarying('CINT',' || T0check[rowi-1]==1'),')',
    'discreteCINT= invDRIFT',checkvarying('DRIFT','[subjecti]','[1]'),' %*% (discreteDRIFT - IIlatent) %*% CINT',checkvarying('CINT','[subjecti]','[1]'),'
    if(intervalChange==1 ',checkvarying('DRIFT',' || T0check[rowi-1]==1'),')',
    'discreteDIFFUSION = inverse(asymDIFFUSION',checkvarying(c('DIFFUSION','DRIFT'),'[subjecti]','[1]'),' - (',
    'discreteDRIFT %*% asymDIFFUSION',checkvarying(c('DIFFUSION','DRIFT'),'[subjecti]','[1]'),' %*% t(discreteDRIFT)))
    intervalChange=0
  }'),'
  

    if(T0check[rowi] ==0){ 
    if(T0check[rowi-1] ==1)  eta[etarow]~ dmnorm(discreteDRIFT * T0MEANS',checkvarying('T0MEANS','[subjecti]','[1]'),' - discreteCINT', 
    if(n.TDpred > 0) paste0('+ TDPREDEFFECT',checkvarying('TDPREDEFFECT','[subjecti]','[1]'),' * tdpreds[rowi]'),
    ', discreteDIFFUSION)
    
    if(T0check[rowi-1] ==0)  eta[etarow]~ dmnorm(discreteDRIFT * eta[etarow-1] - discreteCINT', 
    if(n.TDpred > 0) paste0('+ TDPREDEFFECT',checkvarying('TDPREDEFFECT','[subjecti]','[1]'),' * tdpreds[rowi]'),
    ', discreteDIFFUSION)
    }
    
    if(T0check[rowi] ==0 && nobs_y[rowi]>0) Y[rowi][whichobs] ~ ',
    ifelse(!binomial,'dmnorm','bernoulli_logit'),'(LAMBDA',checkvarying('LAMBDA','[subjecti]','[1]'),'[whichobs,] * 
    eta[etarow] + MANIFESTMEANS',checkvarying('MANIFESTMEANS','[subjecti]','[1]'),'[whichobs]',
    if(!binomial) paste0(', MANIFESTVAR',checkvarying('MANIFESTVAR','[subjecti]','[1]'),'[whichobs,whichobs]'),
    ')
    
    if(T0check[rowi] ==1 && nobs_y[rowi]>0) Y[rowi][whichobs] ~ ',
    ifelse(!binomial,'dmnorm','bernoulli_logit'),'(LAMBDA',checkvarying('LAMBDA','[subjecti]','[1]'),'[whichobs,] * 
    T0MEANS',checkvarying('T0MEANS','[subjecti]','[1]'),'+ 
    MANIFESTMEANS',checkvarying('MANIFESTMEANS','[subjecti]','[1]'),'[whichobs]',
    if(!binomial) paste0(', MANIFESTVAR',checkvarying('MANIFESTVAR','[subjecti]','[1]'),'[whichobs,whichobs]'),
    ')
    
    
    }
  '),'

',paste0(unlist(lapply(1:nrow(ctspec),function(rowi){
  if(is.na(ctspec$value[rowi])) paste0('output_hmean_',ctspec$param[rowi],' = ',
    gsub('param',
      paste0('hypermeans[',which(ctspec$param[is.na(ctspec$value)] == ctspec$param[rowi]),']'),
      ctspec$transform[rowi]),' \n')
  })),collapse=''),'


',paste0(unlist(lapply(1:nrow(ctspec),function(rowi){
  if(ctspec$indvarying[rowi]) paste0('output_hsd_',ctspec$param[rowi],' = ',
    'hypersd[',which(ctspec$param[ctspec$indvarying] == ctspec$param[rowi]),'] * ', 
    'sdscale[',which(ctspec$param[ctspec$indvarying] == ctspec$param[rowi]),'] \n',
    if(!is.na(ctspec$transform[rowi])) paste0(
      'output_hsd_',ctspec$param[rowi],' = abs
      (', 
      gsub('param', paste0('(hypermeans[',which(ctspec$param[is.na(ctspec$value)] == ctspec$param[rowi]),'] + output_hsd_',ctspec$param[rowi]),ctspec$transform[rowi]), ') - (',
      gsub('param', paste0('hypermeans[',which(ctspec$param[is.na(ctspec$value)] == ctspec$param[rowi]),'] - output_hsd_',ctspec$param[rowi]),ctspec$transform[rowi]),'))/2 \n')
    )
})),collapse=''),'


',if(n.TIpred > 0) paste0(unlist(lapply(1:n.TIpred,function(tip){
  paste0(unlist(lapply(1:nrow(ctspec),function(rowi){
    if(ctspec$indvarying[rowi] & ctspec[,paste0(TIpredNames[tip],'_effect')][rowi]) paste0('
      output_tip_',TIpredNames[tip], '_on_', ctspec$param[rowi],' = ',
      'tipredeffect[',which(ctspec$param[ctspec$indvarying] == ctspec$param[rowi]),',',tip,'] \n',
      if(!is.na(ctspec$transform[rowi])) paste0('output_tip_', TIpredNames[tip], '_on_', ctspec$param[rowi],' = ((', 
        gsub('param', 
          paste0('hypermeans[',which(ctspec$param[is.na(ctspec$value)] == ctspec$param[rowi]),'] + tipredeffect[',which(ctspec$param[ctspec$indvarying] == ctspec$param[rowi]),',',tip,']'),
          ctspec$transform[rowi]), 
        ') - (',
        gsub('param', 
          paste0('hypermeans[',which(ctspec$param[is.na(ctspec$value)] == ctspec$param[rowi]),'] - tipredeffect[',which(ctspec$param[ctspec$indvarying] == ctspec$param[rowi]),',',tip,']'),
          ctspec$transform[rowi]),'))/2 \n')
    )
  })),collapse='')
  })),collapse=''),'
    
}')

  out<-stanmodelobj

  if(fit==TRUE){
    
    # browser()
    standata<-list(
      Y=cbind(datalong[,manifestNames]),
      subject=datalong[,'id'],
      nsubjects=nsubjects,
      nmanifest=n.manifest,
      T0check=T0check,
      indvaryingindex=which(ctspec$indvarying[is.na(ctspec$value)]),
      nlatent=n.latent,
      ntipred=n.TIpred,
      ntdpred=n.TDpred,
      nparams=nparams,
      nindvarying=nindvarying,
      sdscale=array(ctspec$sdscale[ctspec$indvarying]),
      ndatapoints=nrow(datalong),
      nhypercorrpars=(nindvarying^2-nindvarying)/2,
      dT=dT,
      nobs_y=array(apply(datalong[,manifestNames,drop=FALSE],1,function(x) length(x[x!=99999])),dim=nrow(datalong)),
      whichobs_y=matrix(t(apply(datalong[,manifestNames,drop=FALSE],1,function(x) {
        out<-as.numeric(which(x!=99999))
        if(length(out)==0) out<-rep(0,n.manifest)
        if(length(out)<n.manifest) out<-c(out,rep(0,n.manifest-length(out)))
        out
      }) ),nrow=c(nrow(datalong),ncol=n.manifest)))
    
    if(n.TIpred > 0) standata$tipreds <- tipreds
    
    if(n.TDpred > 0) standata<-c(standata,list(tdpreds=array(tdpreds,dim=c(nrow(tdpreds),ncol(tdpreds)))))
    
    
  
    jags.inits <- function(){
      list(list("hypermeans"=rnorm(nindvarying),"hypersd"=rnorm(nindvarying),"indparamsbase"=rnorm(nindvarying*nsubjects)))
    }
   writeLines(stanmodelobj,con=file('stanmodelobj'))
    out<-jags(data=standata,inits=jags.inits(),parameters.to.save=paste0('output_hmean_',ctspec$param[ctspec$indvarying]),
      model.file="stanmodelobj",n.chains=1,n.iter=iter)
    
  }
  return(out)
  } 
