# Regenerate the model shapes the Julia engine precompiles for.
#
# The engine caches compiled code per model *type*, and a model's type is its
# matrix dimensions plus one closure type per transform template. Precompiling
# is therefore only worth anything if the shapes built at build time are the
# ones ctsem actually sends -- a hand-written approximation compiles a great
# deal of code that no real fit ever reaches, which is how the first attempt at
# this managed to add 100 seconds of build time and save nothing.
#
# So the shapes are generated from ctsem's own model writer rather than guessed,
# and this script is how. Run it after anything that changes what
# `.ctJuliaPrepare` puts in `parameter_table`:
#
#     Rscript tools/generate-precompile-shapes.R
#
# It rewrites inst/julia/ContinuousTimeSEM/src/precompile_shapes.jl, which is
# checked in -- the engine must be precompilable without R present.

suppressMessages(devtools::load_all(
  file.path(dirname(sub("^--file=", "", grep("^--file=", commandArgs(FALSE), value = TRUE)[1])), ".."),
  compile = FALSE, quiet = TRUE))

# The shapes worth paying build time for: one and two latents with matching
# indicators, which is the overwhelming majority of first fits. Each costs its
# own compile at build time, so this list should stay short and be justified by
# how often the shape is the *first* one of a session.
# Both `intoverpop` routes, because they are different *models*: augmenting the
# state with the random effects changes the latent dimension, hence the axis
# type, hence every specialisation downstream. `TRUE` is ctsem's default and so
# the more common first fit; "laplace" is the one this branch exists for.
shapes <- list(
  list(name = "one_latent_augmented", nlatent = 1L, intoverpop = TRUE),
  list(name = "two_latent_augmented", nlatent = 2L, intoverpop = TRUE),
  list(name = "one_latent_laplace", nlatent = 1L, intoverpop = "laplace"),
  list(name = "two_latent_laplace", nlatent = 2L, intoverpop = "laplace")
)

fake_data <- function(nlatent, nsubjects = 3L, nobs = 4L) {
  out <- do.call(rbind, lapply(seq_len(nsubjects), function(i) {
    d <- data.frame(id = i, time = seq_len(nobs) - 1)
    for (m in seq_len(nlatent)) d[[paste0("Y", m)]] <- stats::rnorm(nobs)
    d
  }))
  out
}

julia_string <- function(x) paste0('"', gsub('"', '\\\\"', x, fixed = FALSE), '"')

emit <- function(shape) {
  nl <- shape$nlatent
  manifest <- paste0("Y", seq_len(nl))
  latent <- paste0("eta", seq_len(nl))
  model <- suppressMessages(suppressWarnings(ctModel(type = "ct",
    manifestNames = manifest, latentNames = latent, LAMBDA = diag(nl))))
  # One parameter individually varying, so the Laplace route is covered too.
  model$pars$indvarying <- FALSE
  model$pars$indvarying[match(TRUE, model$pars$matrix == "MANIFESTMEANS")] <- TRUE
  spec <- suppressMessages(suppressWarnings(ctFit(fake_data(nl), model,
    backend = "julia", fit = FALSE, intoverpop = shape$intoverpop)))
  tb <- as.data.frame(spec$parameter_table, stringsAsFactors = FALSE)
  nz <- function(x, empty) { x[is.na(x)] <- empty; x }

  vec <- function(x, quote = FALSE) {
    x <- if (quote) vapply(as.character(x), julia_string, "") else as.character(x)
    paste0("[", paste(x, collapse = ", "), "]")
  }
  # An augmented fit has no Laplace block at all; the empty index vectors are
  # what the workload reads to know which optimiser to call.
  lap <- spec$laplace
  if (is.null(lap)) lap <- list(npar = NA_integer_, re_index = integer(),
    sd_index = integer(), cor_index = integer(), sd_scale = numeric())
  paste0(
    "    ", shape$name, " = (\n",
    "        matrix = ", vec(tb$matrix, quote = TRUE), ",\n",
    "        row = Int", vec(as.integer(tb$row)), ",\n",
    "        col = Int", vec(as.integer(tb$col)), ",\n",
    "        parnumber = Int", vec(nz(as.integer(tb$parnumber), 0L)), ",\n",
    "        value = Float64", vec(ifelse(is.na(tb$value), "NaN", format(as.numeric(tb$value), digits = 17))), ",\n",
    "        transform = ", vec(nz(as.character(tb$transform), ""), quote = TRUE), ",\n",
    "        predicttransform = ", vec(nz(as.character(tb$predicttransform), ""), quote = TRUE), ",\n",
    "        updatetransform = ", vec(nz(as.character(tb$updatetransform), ""), quote = TRUE), ",\n",
    "        tdtransform = ", vec(nz(as.character(tb$tdtransform), ""), quote = TRUE), ",\n",
    "        npar = ", max(c(tb$parnumber, lap$npar), na.rm = TRUE), ",\n",
    "        re_index = Int", vec(as.integer(lap$re_index)), ",\n",
    "        sd_index = Int", vec(as.integer(lap$sd_index)), ",\n",
    "        cor_index = Int", vec(as.integer(lap$cor_index)), ",\n",
    "        sd_scale = Float64", vec(format(as.numeric(lap$sd_scale), digits = 17)), ",\n",
    "    ),\n")
}

body <- paste(vapply(shapes, emit, ""), collapse = "")
out <- paste0(
  "# GENERATED by tools/generate-precompile-shapes.R -- do not edit by hand.\n",
  "#\n",
  "# The exact parameter tables ctsem's model writer produces for the shapes\n",
  "# listed in that script, captured so the engine can compile for them at build\n",
  "# time. Regenerate after any change to what `.ctJuliaPrepare` emits; a stale\n",
  "# table costs nothing but correctness of the *optimisation* -- the shapes\n",
  "# simply stop matching and first fits get slow again, silently. The test\n",
  "# `precompiled shapes still match what ctsem sends` is what catches that.\n",
  "\n",
  "const _PRECOMPILE_SHAPES = (\n", body, ")\n")
path <- file.path("inst", "julia", "ContinuousTimeSEM", "src", "precompile_shapes.jl")
writeLines(out, path)
cat("wrote", path, "--", nchar(out), "bytes\n")
