#' Update a ctStanFit object
#'
#' Either to include different data, or because you have upgraded ctsem and the internal data structure has changed.
#'
#' @param oldfit fit object to be upgraded
#' @param data replacement long format data object
#' @param recompile whether to force a recompile -- safer but slower and usually unnecessary.
#' @param refit if TRUE, refits the model using the old estimates as a starting point. Only applicable for
#' optimized fits, not sampling.
#' @param ... extra arguments to pass to ctFit
#'
#' @return updated ctStanFit object.
#' @aliases ctStanFitUpdate
#' @export
#'
#' @examples
#' newfit <- ctFitUpdate(ctstantestfit,refit=FALSE)

ctFitUpdate <- function(oldfit, data=NA, recompile=FALSE,refit=FALSE,...){

  if(!refit) message('Trying to do a quick update -- if there are problems, try with refit=TRUE for more robustness')

  dots <- list(...)
  # `$args$input` -- the literal call, still carrying 'auto'/'maxneeded' and
  # whatever else was unresolved -- not `$args$resolved`, which would freeze
  # this refit at whatever a previous 'auto' happened to route to instead of
  # letting it re-route against the new data or overrides in `...`.
  args <- as.list(oldfit$args$input)
  for(n in names(dots)){
    args[[n]] <- dots[[n]]
  }
  if(length(oldfit$stanfit$stanfit@sim) > 0) refit=FALSE
  args$fit <- refit
  args$inits <- oldfit$stanfit$rawest
  args$model <- oldfit$ctstanmodelbase
  args$ctstanmodel <- NULL

  newargs <- as.list(args(ctFit))
  for(argi in names(args)){
    if(argi %in% names(args)) newargs[[argi]] <- args[[argi]] else message(argi, ' is no longer a valid argument, dropping...')
  }


  if(length(data==1)) args$datalong <- standatatolong(oldfit$standata,origstructure = TRUE,ctm=oldfit$ctstanmodelbase)
  if(length(data) > 1) args$datalong <- data
  newfit <- do.call(ctFit,args)

  if(!refit){
    oldfit$standata <- newfit$standata
    if(oldfit$ctstanmodel$recompile || recompile) oldfit$stanmodel <- rstan::stan_model(model_code = newfit$stanmodeltext) else
      oldfit$stanmodel <- stanmodels$ctsm
  }
  if(refit) oldfit <- newfit
  return(oldfit)
}

#' @export
ctStanFitUpdate <- ctFitUpdate


T0VARredundancies <- function(ctm) { #check for redundant T0VAR parameters (because indvarying t0means) and disable
  whichT0VAR_T0MEANSindvarying <- ctm$pars$matrix %in% 'T0VAR'  &
    is.na(ctm$pars$value) &
    (ctm$pars$row %in% ctm$pars$row[ctm$pars$matrix %in% 'T0MEANS' & ctm$pars$indvarying] |
        ctm$pars$col %in% ctm$pars$row[ctm$pars$matrix %in% 'T0MEANS' & ctm$pars$indvarying])
  if(any(whichT0VAR_T0MEANSindvarying)){
    message('Free T0VAR parameters as well as indvarying T0MEANS -- fixing T0VAR pars to diag matrix of 1e-6')
    ctm$pars$value[whichT0VAR_T0MEANSindvarying & ctm$pars$col == ctm$pars$row ] <- 1e-6
    ctm$pars$value[whichT0VAR_T0MEANSindvarying & ctm$pars$col != ctm$pars$row ] <- 0
    ctm$pars$param[whichT0VAR_T0MEANSindvarying] <- NA
    ctm$pars$transform[whichT0VAR_T0MEANSindvarying] <- NA
    ctm$pars$indvarying[whichT0VAR_T0MEANSindvarying] <- FALSE
  }
  return(ctm)
}



#' Fit a ctsem model
#'
#' Fits a ctsem model specified via \code{\link{ctModel}} with type either 'ct' or 'dt'.
#' \code{ctStanFit} is maintained as a backward-compatible alias.
#'
#' @aliases ctStanFit
#' @seealso \code{\link{ctIdentify}} reports which parameters the data can
#' inform, before a fit is spent finding out; \code{\link{ctTracePlot}} draws
#' the optimisation trace a julia fit records.
#' @param datalong long format data containing columns for subject id (numeric values, 1 to max subjects), manifest variables,
#' any time dependent (i.e. varying within subject) predictors,
#' and any time independent (not varying within subject) predictors.
#' @param model model object as generated by \code{\link{ctModel}} with type='ct' or 'dt', for continuous or discrete time
#' models respectively.
#' @param ctstanmodel Deprecated. Use \code{model}.
#' @param stanmodeltext already specified Stan model character string, generally leave NA unless modifying Stan model directly.
#' (Possible after modification of output from fitting with argument fit=FALSE)
#' @param intoverstates logical indicating whether or not to integrate over
#' latent states using a Kalman filter. \code{FALSE} instead makes the
#' latent states part of what is estimated: the target becomes the joint
#' density of the data and the states, and the fit reports the trajectory
#' alongside the parameters in \code{fit$estimate$states}.
#'
#' With \code{backend='julia'} that route is exact -- no Gaussian
#' assumption is made about the state anywhere, where the filter's update
#' for a binary, ordinal or count indicator is an assumed-density
#' projection. Pair it with \code{optimize=FALSE}: sampling the joint
#' density gives the posterior of parameters and states together, while
#' \code{optimize=TRUE} gives its joint mode, whose variance parameters
#' are biased downward. Standard errors for an optimised fit come from the
#' Hessian with the states profiled out, and \code{uncertainty} is
#' restricted to \code{'hessian'} for that reason.
#' Generally recommended to set TRUE unless using non-gaussian measurement model.
#' @param binomial Deprecated. Logical indicating the use of binary rather than Gaussian data, as with IRT analyses.
#' This now sets \code{intoverstates = FALSE} and the \code{manifesttype} of every indicator to 1, for binary.
#' @param fit If TRUE, fit specified model using Stan, if FALSE, return stan model object without fitting.
#' @param intoverpop how to handle declared individual differences. If 'auto',
#' set to TRUE if optimizing and FALSE if using hmc.
#' if TRUE, integrates over population distribution of parameters rather than full sampling.
#' Allows for optimization of non-linearities and random effects, via state expansion.
#' 'augmented' names that state-expansion method explicitly. 'laplace' instead
#' integrates the random effects out subject by subject with a Laplace
#' approximation, leaving each subject's filtered state space at its
#' single-subject size, so the cost of a random effect stops growing cubically
#' with the number of varying parameters. 'laplace' requires
#' \code{backend='julia'} and \code{optimize=TRUE}, and is exact whenever the
#' varying parameters enter the state mean linearly; elsewhere it is an
#' approximation, and \code{summary()} says so.
#' \code{FALSE} is the other route, and the one \code{'auto'} chooses when
#' \code{optimize=FALSE}: the individual parameters are sampled rather than
#' integrated over, so HMC targets the joint posterior over the population
#' parameters and every subject's random effects. That is exact whatever the
#' model, and its dimension grows with the number of subjects rather than
#' staying at the parameter count. \code{TRUE} and \code{FALSE} may be given
#' in place of the character forms above.
#' @param sameInitialTimes if TRUE, include an empty observation for every subject that has no observation
#' at the earliest observation time of the dataset. This ensures that the T0MEANS occurs for every subject at the same time,
#' rather than just at the earliest observation for that subject. Important when modelling trends over time, age, etc.
#' @param plot if TRUE, for sampling, a Shiny program is launched upon fitting to interactively plot samples.
#' May struggle with many (e.g., > 5000) parameters. For optimizing, various optimization details are plotted -- in development.
#' With \code{backend='julia'} the trace is plotted once the fit returns
#' rather than during it: a julia fit is a single blocking call into the
#' engine, so there is no point at which R could draw anything while it runs.
#' For genuinely live output use \code{optimcontrol$callback}.
#' @param derrind deprecated, latents involved in dynamic error calculations are determined automatically now.
#' @param optimize if TRUE, use \code{\link{stanoptimis}} function for maximum a posteriori / importance sampling estimates,
#' otherwise use the HMC sampler from Stan, which is (much) slower, but generally more robust for complex individual differences.
#' When \code{optimize=FALSE}, the stored point estimate (\code{stanfit$rawest}) is the per-parameter
#' median of the posterior draws; the julia backend's sampled point estimate (see \code{\link{ctSample}})
#' is the per-parameter mean instead.
#' @param optimcontrol list of parameters sent to \code{\link{stanoptimis}} governing optimization / importance sampling.
#' With \code{backend='julia'}, \code{optimcontrol$gradient} selects the
#' gradient method: \code{'adjoint'} (reverse mode, the default) or
#' \code{'forward'} (ForwardDiff). Both compute the same gradient; 'adjoint'
#' costs the same regardless of the number of free parameters, so it is
#' dramatically faster for larger models and marginally slower for very small
#' ones.
#' \code{optimcontrol$datastart} (\code{backend='julia'}, default \code{TRUE})
#' takes the starting values for the diagonals of \code{DRIFT},
#' \code{DIFFUSION}, \code{T0VAR} and \code{MANIFESTVAR} from the data
#' instead of from the fixed point every fit used to start at. That point put
#' \code{DIFFUSION} at 6.93 and the variances at 3.47 whatever the data were
#' measured in, and starting far above the data's scale lets the optimiser
#' collapse the latent process to zero variance and call the whole signal
#' measurement error. Each process's scale is read off the indicators loading
#' on it -- on the scale its link puts them, so a count is read through
#' \code{log1p} and a binary or ordinal indicator, whose logit fixes the
#' latent scale by itself, contributes none -- and each cell's own transform is
#' then inverted numerically to get the raw value. Everything is clamped, and a
#' cell that cannot be solved keeps the old default.
#'
#' Measured on a three-indicator factor model with the data rescaled, over
#' four starting-jitter seeds each: at x0.01 the fit converged 0 times out of
#' 4 with this off and 4 out of 4 with it on, reaching 4565.60 against
#' 4203.69-4237.21 and recovering the first free loading at 0.808 against
#' -844 to -1206, for a generating value of 0.8. At x1 the two are identical.
#' At x100 it is neutral: that model is near a basin boundary at that scale
#' and converges twice in four either way, decided by the jitter on the
#' parameters this does not set rather than by the derived ones. Supplied
#' \code{inits} are never overridden, and \code{optimcontrol$datastart =
#' FALSE} restores the fixed start.
#'
#' \code{optimcontrol$carefulfit} works for \code{backend='julia'} as it does
#' for Stan: when \code{priors=FALSE}, a rough first pass is run \emph{with}
#' ctsem's \code{normal(0,1)} raw priors to obtain starting values, and the
#' likelihood is then maximised from there. It defaults to \code{TRUE}, capped
#' at 10 iterations, and is skipped when \code{inits} are supplied. Set
#' \code{optimcontrol$carefulfit = FALSE} to switch it off or to a number to
#' choose the cap.
#'
#' It does not make fits faster: measured over 800 fits, total iterations came
#' to 0.91-1.14 times a plain fit at ten prior iterations, 1.09-1.50 at twenty
#' and 1.47-1.64 at forty. It is on by default for where the fit lands rather
#' than how quickly it gets there. Over 720 fits judged on a random-effect SD
#' with a true value of 0.5, a cap of 10 gave an RMSE of 0.190 and a worst
#' error of 0.547, against 0.478 and 6.73 with the pass switched off. A longer
#' pass is not a safer one -- a cap of 20 scored 0.550 and 7.99, worse than not
#' warming up at all -- because the prior pass pulls the start toward the prior
#' mode and past about ten iterations that is what it hands the likelihood.
#'
#' \code{fit$estimate$carefulfit} records whether the pass ran, and
#' \code{$carefulfit_iterations} how long it was allowed.
#' With \code{backend='julia'}, \code{optimcontrol$callback} is a function
#' called while the fit runs, with \code{(iteration, total, objective,
#' gradient_norm)}. It is for a front end that wants to draw progress live:
#' the engine calls it on a time cadence rather than once per iteration,
#' because a callback costs about half a millisecond through the Julia
#' bridge, and always once more at the end. An error inside it disables it
#' and warns, leaving the fit unaffected. If output after the fit is enough,
#' \code{fit$trace} holds every iteration and \code{\link{ctTracePlot}}
#' draws it.
#' \code{backend='julia'} also finishes by estimating uncertainty, as the stan
#' backend does, and reads the same \code{stanoptimis} control names for it:
#' \code{uncertainty} (default \code{'hessian'}), \code{uncertaintyDraws},
#' \code{finishsamples}, and \code{uncertaintyControl}. Set
#' \code{optimcontrol$estonly = TRUE} for point estimates only.
#'
#' \code{optimcontrol$stallretries} and \code{optimcontrol$stalltol} govern what happens
#' when the stan optimizer stops somewhere that is not a maximum. A rough likelihood can
#' leave it unable to find any improving step, which it reports as convergence -- returning
#' the starting values with the uncertainty computed about them. The gradient where it
#' stopped separates the two cases by orders of magnitude, so the fit is restarted from
#' fresh values (twice by default) when it exceeds \code{stalltol} per data point, and warns
#' if it still ends up there.
#'
#' @param nopriors deprecated, use priors argument. logical. If TRUE, any priors are disabled -- sometimes desirable for optimization.
#' @param priors if TRUE, priors are included in computations, otherwise specified priors are ignored.
#' @param iter used when \code{optimize=FALSE}. number of iterations, half of which will be devoted to warmup by default when sampling.
#' @param inits either character string 'optimize, NULL, or vector of (unconstrained)
#' parameter start values, as returned by the rstan function \code{rstan::unconstrain_pars}, or the parameter values
#' found in a ctsem fit object \code{myfit$stanfit$rawest} (or \code{$rawposterior}) for instance.
#' @param chains used when \code{optimize=FALSE}. Number of chains to sample, during HMC or post-optimization importance sampling. Unless the cores
#' argument is also set, the number of chains determines the number of cpu cores used, up to
#' the maximum available minus one. Irrelevant when \code{optimize=TRUE}.
#' @param cores number of cpu cores to use. Either 'maxneeded' to use as many as available minus one,
#' up to the number of chains, or a positive integer. If \code{optimize=TRUE}, more cores are generally faster.
#' @param backend Either 'stan' (the default) or 'julia'. The julia backend is a
#' separate maximum-likelihood engine with the same model definitions and the
#' same summaries; it takes its own reverse-mode gradient, supports
#' \code{intoverpop='laplace'} for random effects, and can be sampled afterwards
#' with \code{\link{ctSample}}. It needs a working Julia -- see
#' \code{\link{ctJuliaSetup}} and \code{\link{ctJuliaInstall}}.
#' @param backendcontrol Used when \code{backend='julia'}. List of engine
#' settings: \code{maxiter}, \code{g_tol}, \code{f_tol}, \code{x_tol} for the
#' optimizer's stopping rules, \code{lbfgs_memory} for how many curvature pairs
#' L-BFGS keeps, \code{gradient} ('adjoint' or 'forward'), \code{julia_project}
#' to point at a local engine checkout, \code{restart_session} to clear the
#' Julia session before fitting, and \code{progress} to force progress
#' reporting on or off for this fit.
#' @param control Used when \code{optimize=FALSE}. For \code{backend='stan'}, a list of arguments sent to \code{\link[rstan]{stan}} control argument,
#' regarding warmup / sampling behaviour. Unless specified, values used are:
#' list(adapt_delta = .8, adapt_window=2, max_treedepth=10, adapt_init_buffer=2, stepsize = .001).
#' For \code{backend='julia'}, the same argument instead carries the julia sampler's own settings:
#' \code{maxdepth}/\code{max_treedepth} (default 10), \code{target_accept}/\code{adapt_delta} (0.8),
#' \code{maxdelta} (1000), \code{init_scale} (1), \code{adapt_metric} (TRUE), \code{adapt_effects} (FALSE),
#' and the optional effective-sample-size target \code{minEss}, \code{meanEss}, \code{maxDraws},
#' \code{rhatTarget} (1.01) and \code{settleTol} -- all documented in full under \code{control} in
#' \code{\link{ctSample}} -- plus \code{warmup} (default half of \code{iter}), \code{seed} (default
#' 20260828) and \code{processes} (default TRUE), which \code{\link{ctSample}} instead takes as
#' separate named arguments.
#' @param nlcontrol List of non-linear control parameters.
#' \code{maxtimestep} must be a positive numeric,  specifying the largest time
#' span covered by the numerical integration. The large default ensures that for each observation time interval,
#' only a single step of exponential integration is used. When \code{maxtimestep} is smaller than the observation time interval,
#' the integration is nested within an Euler like loop.
#' Smaller values may offer greater accuracy, but are slower and not always necessary. Given the exponential integration,
#' linear model elements are fit exactly with only a single step.
#' @param verbose Integer from 0 to 2. 1 reports progress while the model
#'   fits; 2 additionally keeps every progress line rather than overwriting one
#'   in place, and prints more for debugging. Whether overwriting is possible is
#'   detected from where the output is going; set
#'   \code{options(ctsem.progress.overwrite = FALSE)} if that detection is wrong
#'   for your front end -- a Shiny app capturing stdout, for instance -- or
#'   \code{TRUE} to force it on.
#' @param stationary Logical. If TRUE, T0VAR and T0MEANS input matrices are ignored,
#' the parameters are instead fixed to long run expectations. More control over this can be achieved
#' by instead setting parameter names of T0MEANS and T0VAR matrices in the input model to 'stationary', for
#' elements that should be fixed to stationarity.
#' @param forcerecompile logical. For development purposes.
#' If TRUE, stan model is recompiled, regardless of apparent need for compilation.
#' @param saveCompile if TRUE and compilation is needed / requested, writes the stan model to
#' the parent frame as ctsem.compiled (unless that object already exists and is not from ctsem), to avoid unnecessary recompilation.
#' @param savescores Logical. If TRUE, output from the Kalman filter is saved in output. For datasets with many variables
#' or time points, will increase file size substantially.
#' @param savesubjectmatrices Logical. If TRUE, subject specific matrices are saved --
#' only relevant when either time dependent predictors or individual differences are
#' used. Can increase memory usage dramatically in large models, and can be computed after fitting using ctExtract
#' or ctSubjectPars .
#' @param saveComplexPars Logical. If TRUE, also save rowwise output of any complex parameters specified,
#' i.e. combinations of parameters, functions and states.
#' @param gendata Logical -- If TRUE, uses provided data for only covariates and a time and missingness structure, and
#' generates random data according to the specified model / priors.
#' Generated data is in the $Ygen subobject after running \code{extract} on the fit object.
#' For datasets with many manifest variables or time points, file size may be large.
#' To generate data based on the posterior of a fitted model, see \code{\link{ctGenerateFromFit}}.
#' @param compileArgs List of arguments to pass to \code{\link[rstan]{stan_model}} for compilation of the Stan model.
#' @param ... additional arguments to pass to \code{\link[rstan]{stan}} function.
#' @return A fitted object of class \code{ctStanFit} (\code{backend='stan'}) or
#' \code{ctJuliaFit} (\code{backend='julia'}), both also classed \code{ctFit}.
#' Besides backend-specific components, every fit carries \code{$args}, a list
#' with two sublists that mean the same thing on both backends:
#' \describe{
#'  \item{\code{input}}{Exactly what was passed to \code{ctFit()}, or the
#'  formal default when an argument was not supplied -- \code{intoverpop} may
#'  still read \code{'auto'}, \code{cores} may still read \code{'maxneeded'}.}
#'  \item{\code{resolved}}{What the fit actually ran with, after \code{'auto'}
#'  routing, deprecated-argument merges (e.g. \code{nopriors} into
#'  \code{priors}) and backend-specific defaults were settled -- \code{cores}
#'  is a concrete integer, \code{intoverpop} is one of \code{'augmented'},
#'  \code{'laplace'} or \code{'none'}. A call that gives the same \code{input}
#'  on both backends gives the same \code{resolved} on both.}
#' }
#' Before this, \code{$args} itself held the raw call on a stan fit and only
#' the resolved settings on a julia fit, so the same field name meant opposite
#' things across backends; code reading \code{fit$args$intoverpop} or
#' \code{fit$args$cores} directly should now read \code{fit$args$resolved} (or
#' \code{$input}, if the literal call is what is wanted, as
#' \code{\link{ctFitUpdate}} does).
#' @export
#' @examples
#' \donttest{
#'
#' #generate a modern ctsem model relying heavily on defaults
#' model<-ctModel(type='ct',
#'   latentNames=c('eta1','eta2'),
#'   manifestNames=c('Y1','Y2'),
#'   MANIFESTVAR=diag(.1,2),
#'   TDpredNames='TD1',
#'   TIpredNames=c('TI1','TI2','TI3'),
#'   LAMBDA=diag(2))
#'
#' fit<-ctFit(ctstantestdat, model,priors=TRUE)
#'
#' summary(fit)
#'
#' plot(fit,wait=FALSE)
#'
#' #### extended examples
#'
#' library(ctsem)
#' set.seed(3)
#'
#' #  Data generation (run this, but no need to understand!) -----------------
#'
#' Tpoints <- 20
#' nmanifest <- 4
#' nlatent <- 2
#' nsubjects<-20
#'
#' #random effects
#' age <- rnorm(nsubjects) #standardised
#' cint1<-rnorm(nsubjects,2,.3)+age*.5
#' cint2 <- cint1*.5+rnorm(nsubjects,1,.2)+age*.5
#' tdpredeffect <- rnorm(nsubjects,5,.3)+age*.5
#'
#' for(i in 1:nsubjects){
#'   #generating model
#'   gm<-ctModel(Tpoints=Tpoints,n.manifest = nmanifest,n.latent = nlatent,n.TDpred = 1,
#'   type='omx',
#'     LAMBDA = matrix(c(1,0,0,0, 0,1,.8,1.3),nrow=nmanifest,ncol=nlatent),
#'     DRIFT=matrix(c(-.3, .2, 0, -.5),nlatent,nlatent),
#'     TDPREDMEANS=matrix(c(rep(0,Tpoints-10),1,rep(0,9)),ncol=1),
#'     TDPREDEFFECT=matrix(c(tdpredeffect[i],0),nrow=nlatent),
#'     DIFFUSION = matrix(c(1, 0, 0, .5),2,2),
#'     CINT = matrix(c(cint1[i],cint2[i]),ncol=1),
#'     T0VAR=diag(2,nlatent,nlatent),
#'     MANIFESTVAR = diag(.5, nmanifest))
#'
#'   #generate data
#'   newdat <- ctGenerate(ctmodelobj = gm,n.subjects = 1,burnin = 2,
#'     dtmat<-rbind(c(rep(.5,8),3,rep(.5,Tpoints-9))))
#'   newdat[,'id'] <- i #set id for each subject
#'   newdat <- cbind(newdat,age[i]) #include time independent predictor
#'   if(i ==1) {
#'     dat <- newdat[1:(Tpoints-10),] #pre intervention data
#'     dat2 <- newdat #including post intervention data
#'   }
#'   if(i > 1) {
#'     dat <- rbind(dat, newdat[1:(Tpoints-10),])
#'     dat2 <- rbind(dat2,newdat)
#'   }
#' }
#' colnames(dat)[ncol(dat)] <- 'age'
#' colnames(dat2)[ncol(dat)] <- 'age'
#'
#'
#' #plot generated data for sanity
#' plot(age)
#' matplot(dat[,gm$manifestNames],type='l',pch=1)
#' plotvar <- 'Y1'
#' plot(dat[dat[,'id']==1,'time'],dat[dat[,'id']==1,plotvar],type='l',
#'   ylim=range(dat[,plotvar],na.rm=TRUE))
#' for(i in 2:nsubjects){
#'   points(dat[dat[,'id']==i,'time'],dat[dat[,'id']==i,plotvar],type='l',col=i)
#' }
#'
#'
#' dat2[,gm$manifestNames][sample(1:length(dat2[,gm$manifestNames]),size = 100)] <- NA
#'
#'
#' #data structure
#' head(dat2)
#'
#'
#' # Model fitting -----------------------------------------------------------
#'
#' ##simple univariate default model
#'
#' m <- ctModel(type = 'ct', manifestNames = c('Y1'), LAMBDA = diag(1))
#' ctModelLatex(m)
#'
#' #Specify univariate linear growth curve
#'
#' m1 <- ctModel(type = 'ct',
#'   manifestNames = c('Y1'), latentNames=c('eta1'),
#'   DRIFT=matrix(-.0001,nrow=1,ncol=1),
#'   DIFFUSION=matrix(0,nrow=1,ncol=1),
#'   T0VAR=matrix(0,nrow=1,ncol=1),
#'   CINT=matrix(c('cint1'),ncol=1),
#'   T0MEANS=matrix(c('t0m1'),ncol=1),
#'   LAMBDA = diag(1),
#'   MANIFESTMEANS=matrix(0,ncol=1),
#'   MANIFESTVAR=matrix(c('merror'),nrow=1,ncol=1))
#'
#' ctModelLatex(m1)
#'
#' #fit
#' f1 <- ctFit(datalong = dat2, model = m1, optimize=TRUE, priors=FALSE)
#'
#' summary(f1)
#'
#' #plots of individual subject models v data
#' ctPredict(f1,plot=TRUE,subjects=1,kalmanvec=c('y','yprior'),timestep=.01)
#' ctPredict(f1,plot=TRUE,subjects=1:3,kalmanvec=c('y','ysmooth'),timestep=.01,errorvec=NA)
#'
#' ctPostPredict(f1, wait=FALSE) #compare randomly generated data from posterior to observed data
#'
#' cf<-ctCheckFit(f1) #compare mean and covariance of randomly generated data to observed cov
#' plot(cf,wait=FALSE)
#'
#'  ### Further example models
#'
#' #Include intervention
#' m2 <- ctModel(type = 'ct',
#'   manifestNames = c('Y1'), latentNames=c('eta1'),
#'   n.TDpred=1,TDpredNames = 'TD1', #this line includes the intervention
#'   TDPREDEFFECT=matrix(c('tdpredeffect'),nrow=1,ncol=1), #intervention effect
#'   DRIFT=matrix(-1e-5,nrow=1,ncol=1),
#'   DIFFUSION=matrix(0,nrow=1,ncol=1),
#'   CINT=matrix(c('cint1'),ncol=1),
#'   T0MEANS=matrix(c('t0m1'),ncol=1),
#'   T0VAR=matrix(0,nrow=1,ncol=1),
#'   LAMBDA = diag(1),
#'   MANIFESTMEANS=matrix(0,ncol=1),
#'   MANIFESTVAR=matrix(c('merror'),nrow=1,ncol=1))
#'
#'
#'
#' #Individual differences in intervention, Bayesian estimation, covariates
#' m2i <- ctModel(type = 'ct',
#'   manifestNames = c('Y1'), latentNames=c('eta1'),
#'   TIpredNames = 'age',
#'   TDpredNames = 'TD1', #this line includes the intervention
#'   TDPREDEFFECT=matrix(c('tdpredeffect||TRUE'),nrow=1,ncol=1), #intervention effect
#'   DRIFT=matrix(-1e-5,nrow=1,ncol=1),
#'   DIFFUSION=matrix(0,nrow=1,ncol=1),
#'   CINT=matrix(c('cint1'),ncol=1),
#'   T0MEANS=matrix(c('t0m1'),ncol=1),
#'   T0VAR=matrix(0,nrow=1,ncol=1),
#'   LAMBDA = diag(1),
#'   MANIFESTMEANS=matrix(0,ncol=1),
#'   MANIFESTVAR=matrix(c('merror'),nrow=1,ncol=1))
#'
#'
#' #Including covariate effects
#' m2ic <- ctModel(type = 'ct',
#'   manifestNames = c('Y1'), latentNames=c('eta1'),
#'   n.TIpred = 1, TIpredNames = 'age',
#'   n.TDpred=1,TDpredNames = 'TD1', #this line includes the intervention
#'   TDPREDEFFECT=matrix(c('tdpredeffect'),nrow=1,ncol=1), #intervention effect
#'   DRIFT=matrix(-1e-5,nrow=1,ncol=1),
#'   DIFFUSION=matrix(0,nrow=1,ncol=1),
#'   CINT=matrix(c('cint1'),ncol=1),
#'   T0MEANS=matrix(c('t0m1'),ncol=1),
#'   T0VAR=matrix(0,nrow=1,ncol=1),
#'   LAMBDA = diag(1),
#'   MANIFESTMEANS=matrix(0,ncol=1),
#'   MANIFESTVAR=matrix(c('merror'),nrow=1,ncol=1))
#'
#' m2ic$pars$indvarying[m2ic$pars$matrix %in% 'TDPREDEFFECT'] <- TRUE
#'
#'
#' #Include deterministic dynamics
#' m3 <- ctModel(type = 'ct',
#'   manifestNames = c('Y1'), latentNames=c('eta1'),
#'   n.TDpred=1,TDpredNames = 'TD1', #this line includes the intervention
#'   TDPREDEFFECT=matrix(c('tdpredeffect'),nrow=1,ncol=1), #intervention effect
#'   DRIFT=matrix('drift11',nrow=1,ncol=1),
#'   DIFFUSION=matrix(0,nrow=1,ncol=1),
#'   CINT=matrix(c('cint1'),ncol=1),
#'   T0MEANS=matrix(c('t0m1'),ncol=1),
#'   T0VAR=matrix('t0var11',nrow=1,ncol=1),
#'   LAMBDA = diag(1),
#'   MANIFESTMEANS=matrix(0,ncol=1),
#'   MANIFESTVAR=matrix(c('merror1'),nrow=1,ncol=1))
#'
#'
#'
#'
#'
#' #Add system noise to allow for fluctuations that persist in time
#' m3n <- ctModel(type = 'ct',
#'   manifestNames = c('Y1'), latentNames=c('eta1'),
#'   n.TDpred=1,TDpredNames = 'TD1', #this line includes the intervention
#'   TDPREDEFFECT=matrix(c('tdpredeffect'),nrow=1,ncol=1), #intervention effect
#'   DRIFT=matrix('drift11',nrow=1,ncol=1),
#'   DIFFUSION=matrix('diffusion',nrow=1,ncol=1),
#'   CINT=matrix(c('cint1'),ncol=1),
#'   T0MEANS=matrix(c('t0m1'),ncol=1),
#'   T0VAR=matrix('t0var11',nrow=1,ncol=1),
#'   LAMBDA = diag(1),
#'   MANIFESTMEANS=matrix(0,ncol=1),
#'   MANIFESTVAR=matrix(c(0),nrow=1,ncol=1))
#'
#'
#'
#' #include 2nd latent process
#'
#' m4 <- ctModel(n.manifest = 2,n.latent = 2, type = 'ct',
#'   manifestNames = c('Y1','Y2'), latentNames=c('L1','L2'),
#'   n.TDpred=1,TDpredNames = 'TD1',
#'   TDPREDEFFECT=matrix(c('tdpredeffect1','tdpredeffect2'),nrow=2,ncol=1),
#'   DRIFT=matrix(c('drift11','drift21','drift12','drift22'),nrow=2,ncol=2),
#'   DIFFUSION=matrix(c('diffusion11','diffusion21',0,'diffusion22'),nrow=2,ncol=2),
#'   CINT=matrix(c('cint1','cint2'),nrow=2,ncol=1),
#'   T0MEANS=matrix(c('t0m1','t0m2'),nrow=2,ncol=1),
#'   T0VAR=matrix(c('t0var11','t0var21',0,'t0var22'),nrow=2,ncol=2),
#'   LAMBDA = matrix(c(1,0,0,1),nrow=2,ncol=2),
#'   MANIFESTMEANS=matrix(c(0,0),nrow=2,ncol=1),
#'   MANIFESTVAR=matrix(c('merror1',0,0,'merror2'),nrow=2,ncol=2))
#'
#' #dynamic factor model -- fixing CINT to 0 and freeing indicator level intercepts
#'
#' m3df <- ctModel(type = 'ct',
#'   manifestNames = c('Y2','Y3'), latentNames=c('eta1'),
#'   n.TDpred=1,TDpredNames = 'TD1', #this line includes the intervention
#'   TDPREDEFFECT=matrix(c('tdpredeffect'),nrow=1,ncol=1), #intervention effect
#'   DRIFT=matrix('drift11',nrow=1,ncol=1),
#'   DIFFUSION=matrix('diffusion',nrow=1,ncol=1),
#'   CINT=matrix(c(0),ncol=1),
#'   T0MEANS=matrix(c('t0m1'),ncol=1),
#'   T0VAR=matrix('t0var11',nrow=1,ncol=1),
#'   LAMBDA = matrix(c(1,'Y3loading'),nrow=2,ncol=1),
#'   MANIFESTMEANS=matrix(c('Y2_int','Y3_int'),nrow=2,ncol=1),
#'   MANIFESTVAR=matrix(c('Y2residual',0,0,'Y3residual'),nrow=2,ncol=2))
#'
#' }

ctFit<-function(datalong, model, stanmodeltext=NA, iter=1000, intoverstates=TRUE, binomial=FALSE,
  fit=TRUE, intoverpop='auto', sameInitialTimes=FALSE, stationary=FALSE,plot=FALSE,  derrind=NA,
  optimize=TRUE,  optimcontrol=list(),
  backend=c('stan','julia'), backendcontrol=list(),
  nlcontrol = list(), nopriors=NA, priors=FALSE, chains=2,
  cores=ifelse(optimize,getOption("mc.cores", 2L),'maxneeded'),
  inits=NULL,
  compileArgs=list(),
  forcerecompile=FALSE,saveCompile=TRUE,savescores=FALSE,
  savesubjectmatrices=FALSE, saveComplexPars=FALSE,
  gendata=FALSE,
  control=list(),verbose=0,..., ctstanmodel){

  # `vb` (Stan's variational Bayes) was removed: it is a stan-only path,
  # crashed on the default fit=TRUE, and stan is being deprecated. Without
  # this check a caller's `vb=TRUE` would silently fall into `...` and be
  # ignored rather than erroring, which would fit MCMC or MLE while the
  # caller believed they had asked for variational inference.
  if('vb' %in% ...names()) stop(
    "the 'vb' (variational Bayes) argument to ctFit() has been removed -- ",
    "stan's variational inference was broken and stan is being deprecated. ",
    "Use optimize=TRUE or optimize=FALSE (sampling) instead.", call.=FALSE)

  if(missing(model)){
    if(missing(ctstanmodel)) stop('model must be supplied')
    warning('ctstanmodel argument is deprecated, use model instead')
    model <- ctstanmodel
  } else if(!missing(ctstanmodel)) {
    stop('Use only one of model or deprecated ctstanmodel')
  }
  ctstanmodel <- model
  backend <- match.arg(backend)
  if(backend %in% 'julia') {
    .ctJuliaUnsupported(ctstanmodel, optimize=optimize, priors=priors,
      intoverpop=intoverpop, gendata=gendata,
      stanmodeltext=stanmodeltext, compileArgs=compileArgs,
      forcerecompile=forcerecompile, optimcontrol=optimcontrol)
    # Before any data preparation, so that a first-time user is asked about the
    # setup they need rather than being told about it after a wait. Only when
    # the fit will actually run: preparation is pure R, and stays usable -- and
    # testable -- on a machine with no Julia at all.
    if(isTRUE(fit)) .ctJuliaEnsureInstalled()
  } else if(!is.null(optimcontrol$is)) {
    # `optimcontrol$is` selected Stan's optimization-plus-importance-sampling
    # route before the `uncertainty` argument replaced it. stanoptimis() has
    # no `is` parameter and no `...` catch-all, so leaving this in place would
    # reach `do.call(stanoptimis, optimcontrol)` and fail with a raw "unused
    # argument" error. Caught here, before any work happens.
    stop("optimcontrol$is is no longer supported; use optimcontrol$uncertainty='is' instead.", call.=FALSE)
  }

  if(!is.na(nopriors)){
    warning('nopriors argument is deprecated, use priors argument in future')
    priors <- !nopriors
  }

  if(any(!is.na(derrind))) warning('derrind argment is deprecated, computed automatically now')

  datalong <- data.frame(datalong)

  if(!ctstanmodel$timeName %in% colnames(datalong) && !ctstanmodel$continuoustime) {
    dtable <- data.table(datalong)
    dtable[,.ObsCount:=1:.N,by=ctstanmodel$id]
    datalong[[ctstanmodel$timeName]] <- dtable[['.ObsCount']]
    rm(dtable)
  }

  datalong <- datalong[order(datalong[[ctstanmodel$subjectIDname]],datalong[[ctstanmodel$timeName]]),] #sort by subject, time.

  datavars <- c(ctstanmodel$timeName,ctstanmodel$subjectIDname, ctstanmodel$manifestNames,ctstanmodel$TDpredNames,ctstanmodel$TIpredNames)
  sapply(datavars,function(x){
    if(!x %in% colnames(datalong)) stop(paste0(x,' column not found in data!'))
    if(!x %in% ctstanmodel$subjectIDname){ #if not an id column
      if(any(!is.numeric(as.numeric(datalong[!is.na(datalong[,x]),x])))) stop(x ,' column contains non-numeric data!')
    }
  })

  if(!'ctStanModel' %in% class(ctstanmodel)) stop('not a ctStanModel object')

  #set nlcontrol defaults
  if(is.null(nlcontrol$maxtimestep)) nlcontrol$maxtimestep = 999999
  if(is.null(nlcontrol$Jstep)) nlcontrol$Jstep = 1e-6

  args=c(as.list(environment()), list(...)) #as.list((match.call(expand.dots=FALSE)))
  args$datalong <- NULL
  args$model <- NULL
  args$ctstanmodel <- NULL

  ctm <- ctstanmodel

  if(!is.null(ctm$TIpredAuto) && ctm$TIpredAuto %in% c(1L,TRUE)){ #if auto tipred, set all effects to true
    for(tip in ctm$TIpredNames){
      ctm$pars[[paste0(tip,'_effect')]] <- TRUE
    }
  }

  if(optimize && !priors) message("Maximum likelihood estimation requested")
  # `optimcontrol$is` is refused above, so it is NULL by the time we get here
  # and the importance-sampling wording this used to choose is unreachable.
  # Importance sampling is now `optimcontrol$uncertainty='is'`, which runs
  # after optimization rather than instead of it, so the estimation this
  # message describes is a posteriori either way.
  if(optimize && priors) message("Maximum a posteriori estimation requested")
  # Naming stan here was wrong for half the fits it described: with
  # backend='julia' the engine runs its own NUTS over the joint posterior of
  # parameters and random effects, and a user reading "Stan's NUTS sampler" on a
  # julia fit has no reason to believe the julia sampler ran at all.
  if(!optimize) message("Bayesian estimation via ",
    if(identical(backend,'julia')) "the julia engine's" else "Stan's",
    " NUTS sampler requested")


  ###stationarity
  if(stationary) {
    stop('Stationary option temporarily unavailable -- reductions needed to pass all CRAN checks')
    ctm$pars$param[ctm$pars$matrix %in% c('T0VAR','T0MEANS')] <- 'stationary'
    ctm$pars$value[ctm$pars$matrix %in% c('T0VAR','T0MEANS')] <- NA
    ctm$pars$indvarying[ctm$pars$matrix %in% c('T0VAR','T0MEANS')] <- FALSE
  }

  #collect individual stationary elements and update ctm$pars
  if(any(ctm$pars$param %in% 'stationary'))  stop('Stationary option temporarily unavailable -- reductions needed to pass all CRAN checks')
    ctm$t0varstationary <- as.matrix(rbind(ctm$pars[which(ctm$pars$param %in% 'stationary' & ctm$pars$matrix %in% 'T0VAR'),c('row','col')]))
    if(nrow(ctm$t0varstationary) > 0){ #ensure upper tri is consistent with lower
      for(i in 1:nrow(ctm$t0varstationary)){
        if(ctm$t0varstationary[i,1] != ctm$t0varstationary[i,2]) ctm$t0varstationary <- rbind(ctm$t0varstationary,ctm$t0varstationary[i,c(2,1)])
      }}
    ctm$t0varstationary = unique(ctm$t0varstationary) #remove any duplicated rows
    ctm$t0meansstationary <- as.matrix(rbind(ctm$pars[which(ctm$pars$param[ctm$pars$matrix %in% 'T0MEANS'] %in% 'stationary'),c('row','col')]))
    ctm$pars$value[ctm$pars$param %in% 'stationary'] <- -99 #does this get inserted?
    ctm$pars$indvarying[ctm$pars$param %in% 'stationary'] <- FALSE
    ctm$pars$transform[ctm$pars$param %in% 'stationary'] <- NA
    ctm$pars$param[ctm$pars$param %in% 'stationary'] <- NA


  if(length(unique(datalong[,ctm$subjectIDname]))==1 && any(ctm$pars$indvarying[is.na(ctm$pars$value)]==TRUE)){
    # is.null(ctm$fixedrawpopmeans) && is.null(ctm$fixedsubpars) & is.null(ctm$forcemultisubject)) {
    ctm$pars$indvarying <- FALSE
    message('Individual variation not possible as only 1 subject! indvarying set to FALSE on all parameters')
  }

  if(length(unique(datalong[,ctm$subjectIDname]))==1 & any(is.na(ctm$pars$value[ctm$pars$matrix %in% 'T0VAR']))){
    # is.null(ctm$fixedrawpopmeans) & is.null(ctm$fixedsubpars) & is.null(ctm$forcemultisubject)) {
    for(ri in 1:nrow(ctm$pars)){
      if(is.na(ctm$pars$value[ri]) && ctm$pars$matrix[ri] %in% 'T0VAR'){
        ctm$pars$value[ri] <- ifelse(ctm$pars$row[ri] == ctm$pars$col[ri], 1e-3, 0)
      }
    }
    message('Free T0VAR parameters fixed to diagonal matrix of 0.001 as only 1 subject - consider appropriateness!')
  }

  if(binomial){
    # A warning, as the other two deprecations are. A message is easy to miss,
    # and this one silently changes `intoverstates` and every indicator's type.
    warning('binomial argument is deprecated -- set manifesttype in the model object to 1 for binary indicators instead. It has set manifesttype=1 for every indicator.', call.=FALSE)
    # It used to set `intoverstates <- FALSE` as well, which is a leftover from
    # when binary data meant sampling the latent states rather than integrating
    # them. The very next check warns that `intoverstates=TRUE` is required for
    # sensible optimization -- so the documented shortcut put a user straight
    # into the state the code itself calls unreliable, under the default
    # `optimize=TRUE`. Setting `manifesttype` directly never did that, and the
    # linearised measurement handles binary indicators with the filter intact:
    # on a three-indicator model it recovers a generating drift of -0.3 as
    # -0.279 and a diffusion of 0.8 as 0.681, both intervals containing the
    # truth.
    ctm$manifesttype[] <- 1
  }

  recompile <- FALSE
  if(!optimize && !priors){
    message('HMC sampling requested, but priors disabled -- are you sure? consider setting priors=TRUE')
    # !priors <- FALSE
  }
  # Maximising over the states rather than integrating them out biases the
  # variance parameters downward -- a variance whose own realisations are
  # being chosen at the same time can always be made to look smaller -- so
  # the joint mode is not the maximum likelihood estimate. That is a property
  # of the estimator and not of a backend, so the warning stands for both.
  # Sampling the same density has no such problem, which is why it points
  # there.
  if(optimize && !intoverstates){
    # Two strengths, because the damage is not uniform. Maximising over the
    # states biases every variance parameter downward, which is the general
    # case. But a parameter that governs how tightly the transition prior
    # constrains the freely chosen states is not merely biased: the joint
    # mode buys cheaper innovations by weakening mean reversion, so such a
    # parameter runs to the flat end of its transform and stays there.
    # Measured on the engine's own fixture: a free DRIFT landed at a raw
    # value of -17 to -19, against a saturation guard at 20, at every sample
    # size from 20 to 120 observations and in six of seven seeds. The
    # engine's count-model test asserts the same runaway independently, on
    # data generated from the model. Fix those parameters and the joint mode
    # is well behaved -- the same fixture with DRIFT fixed converges to a
    # gradient norm of 1e-9 or better -- which is the case this route is for.
    jointrunaway <- ctm$pars$matrix %in% c('DRIFT','DIFFUSION') &
      is.na(ctm$pars$value)
    if(any(jointrunaway)){
      warning(
        'intoverstates=FALSE with optimize=TRUE maximises over the latent ',
        'states rather than integrating them out, and this model leaves ',
        paste0(unique(ctm$pars$matrix[jointrunaway]), collapse=' and '),
        ' free. Those parameters set how tightly the transition prior holds ',
        'the states, so the joint mode weakens them without limit to buy ',
        'cheaper innovations: they run to the end of their transform and ',
        'more data does not help. Treat their estimates as unusable. Fix ',
        'them and free only the means, or use optimize=FALSE to sample the ',
        'states, or intoverstates=TRUE to integrate them out.',
        call.=FALSE)
    } else {
      warning(
        'intoverstates=FALSE maximises over the latent states rather than ',
        'integrating them out, which biases variance parameters downward: ',
        'the joint mode is not the maximum likelihood estimate. Use ',
        'intoverstates=TRUE, or optimize=FALSE to sample the states instead.',
        call.=FALSE)
    }
    # And for a Gaussian indicator with free measurement error it is worse
    # than biased: the joint density is *unbounded*. Send the measurement
    # variance to zero and let the trajectory interpolate the data exactly,
    # and the density diverges -- there is no maximum to find, and an
    # optimiser correctly runs off toward the boundary. Measured on a
    # one-indicator model: MANIFESTVAR reached a raw value of -10.6 with a
    # gradient of 3e9, reported as not converged.
    #
    # Said here rather than left to that non-convergence, which describes
    # the symptom and not the cause. A categorical indicator has no such
    # parameter and is unaffected; so is a Gaussian one whose MANIFESTVAR
    # is fixed. Confirmed degenerate rather than merely biased, so this one
    # is a hard error rather than a warning: there is no fit to return.
    freevar <- ctm$pars$matrix %in% 'MANIFESTVAR' &
      ctm$pars$row == ctm$pars$col & is.na(ctm$pars$value)
    if(any(freevar)){
      gaussian <- ctm$manifesttype[ctm$pars$row[freevar]] %in% 0
      if(any(gaussian)) stop(
        'With intoverstates=FALSE the joint density is unbounded for a ',
        'Gaussian indicator whose MANIFESTVAR is free: the measurement ',
        'variance goes to zero and the latent trajectory interpolates the ',
        'data exactly. The optimiser will run to that boundary and report ',
        'not converged. Fix MANIFESTVAR for ',
        paste(ctm$manifestNames[unique(ctm$pars$row[freevar][gaussian])],
          collapse=', '), ', or use optimize=FALSE.', call.=FALSE)
    }
  }

  # `intoverpop` selects how declared individual differences are handled.
  # TRUE, FALSE and 'auto' keep their existing meanings exactly. The two
  # character forms name the two methods: 'augmented' is the existing
  # state-augmentation, which appends a static latent state per varying
  # parameter and lets the ordinary filter integrate them out; 'laplace'
  # integrates them out per subject instead, so each subject keeps the
  # single-subject state space and the cost of a random effect stops being
  # cubic in the augmented dimension.
  #
  # `intoverpopmethod` carries that choice onwards. `intoverpop` itself stays
  # the logical that drives augmentation everywhere downstream, so the Laplace
  # route reaches the backend with an unaugmented model and every existing
  # `if(intoverpop)` keeps meaning what it meant.
  intoverpopmethod <- 'none'
  if(is.character(intoverpop)){
    intoverpop <- match.arg(intoverpop[1], c('auto','augmented','laplace'))
    if(intoverpop %in% 'auto'){
      intoverpop <- isTRUE(optimize) && any(ctm$pars$indvarying[is.na(ctm$pars$value)])
    } else {
      intoverpopmethod <- intoverpop
      intoverpop <- identical(intoverpopmethod,'augmented')
    }
  }
  intoverpop <- isTRUE(intoverpop)
  if(intoverpop) intoverpopmethod <- 'augmented'

  if(identical(intoverpopmethod,'laplace')){
    if(!backend %in% 'julia') stop(
      "intoverpop='laplace' requires backend='julia'; the generated Stan model ",
      "does not provide the higher-order derivatives it needs.", call.=FALSE)
    if(!any(ctm$pars$indvarying[is.na(ctm$pars$value)])) stop(
      "intoverpop='laplace' was requested but no free parameters are marked ",
      "indvarying, so there is nothing to integrate over.", call.=FALSE)
  }

  # Optimizing without integrating over the population distribution is not a
  # combination that means anything. `intoverpop=FALSE` leaves each subject's
  # random effects as free parameters of the objective, so maximizing it
  # maximizes over the effects as well as over the population parameters, and
  # the population variance it lands on is the one that makes those particular
  # effects most likely -- which is zero, or as near as the data allow. Sampling
  # is what handles that model, which is why `intoverpop='auto'` resolves to
  # FALSE exactly when `optimize` is FALSE.
  #
  # It is refused rather than quietly corrected because both readings of the
  # request are plausible -- integrate them, or sample instead -- and guessing
  # would silently answer a different question. Before this it died inside a
  # transform rendering with `invalid format '%.17g'`, which named neither.
  if(isTRUE(optimize) && !intoverpop && identical(intoverpopmethod,'none') &&
      any(ctm$pars$indvarying[is.na(ctm$pars$value)])) stop(
    "intoverpop=FALSE with optimize=TRUE leaves each subject's random effects ",
    "as free parameters to be maximized over, which drives the population ",
    "variance to zero rather than estimating it. Use intoverpop='augmented' ",
    "or 'laplace' to integrate them out, or optimize=FALSE to sample.",
    call.=FALSE)

  # if(optimize && !intoverpop && any(ctm$pars$indvarying[is.na(ctm$pars$value)]) &&
  #     is.null(ctm$fixedrawpopchol) && is.null(ctm$fixedsubpars)){
  #   intoverpop <- TRUE
  #   message('Setting intoverpop=TRUE to enable optimization of random effects...')
  # }

  # if(intoverpop==TRUE && !any(ctm$pars$indvarying[is.na(ctm$pars$value)])) {
  #   # message('No individual variation -- disabling intoverpop switch');
  #   intoverpop <- FALSE
  # }

  ctm <- ctModel0DRIFT(ctm, ctm$continuoustime) #offset 0 drift
  ctm$pars <- ctModelStatesAndPARS(ctm$pars,statenames = ctm$latentNames,tdprednames=ctm$TDpredNames) #replace latent states and PARS with state and PAR[] refs, need this early because we rely on [] detection
  if(intoverpop)   ctm <- ctStanModelIntOverPop(ctm) #extend system matrices for individual differences

#   #check this *after* replacing PARS references as needed
#   if(any(duplicated(ctm$pars$param[ctm$pars$matrix %in% 'T0MEANS' &
#       !grepl('[',ctm$pars$param,fixed=TRUE) &
#       !is.na(ctm$pars$param)]))) stop(paste0(
#         'Unfortunately, duplicate T0MEANS parameters must be specified via inclusion of additional PARS matrix in ctModel: e.g.,
# ctModel(... #regular model code
# PARS=c("t0mPar||TRUE"), #specify an additional parameter called t0mPar, with random effects
# T0MEANS=c("t0mPar","t0mPar"), #insert this parameter into the T0MEANS matrix as many times as needed.
# ... #regular model code)
# '))

  #jacobian addition
  ctm$jacobian <- try(ctJacobian(ctm))
  if('try-error' %in% class(ctm$jacobian)) ctm$jacobian <- ctJacobian(ctm,simplify=FALSE)
  # ctm$jacobian <- unfoldmats( #replaces matrix references with base parameter
  #   c(listOfMatrices(ctm$pars),ctm$jacobian))
  ctm$jacobian <- ctm$jacobian[names(ctStanMatricesList()$jacobian)]
  jl <- ctModelUnlist(ctm$jacobian,names(ctm$jacobian))
  jl <- jl[apply(jl,1,function(x) any(!is.na(x))),] #clean up messy leftovers of NA's
  jl2 <- as.data.frame(rbind(data.table(ctm$pars[1,]),data.table(jl),fill=TRUE))[-1,]


  for(i in 1:nrow(jl2)){ #copy base parameter transforms etc to jacobian when needed
    if(!is.na(jl2$param[i]) && jl2$param[i] %in% ctm$pars$param){
      jl2[i, !colnames(jl2) %in% list('matrix','row','col')] <-
        ctm$pars[which(ctm$pars$param %in% jl2$param[i])[1], !colnames(ctm$pars) %in% list('matrix','row','col')]
    }
  }

  ctm$pars <- rbind(ctm$pars,jl2)

  ctm$pars <- ctModelStatesAndPARS(ctm$pars,statenames = ctm$latentNames,tdprednames=ctm$TDpredNames) #replace any new state and par refs with square bracket refs

  # The transform text as the model states it, keyed by cell, kept before
  # `ctModelTransformsToNum` replaces it with four numbers recovered from it by
  # a grid search. That search scores candidates by squared residual, so it
  # cannot see a constant small enough not to move the residual: every variance
  # diagonal carries a `1e-10` floor -- `1e-10 + 5 * log1p_exp(2 * param)` --
  # and the `round(x, 6)` that follows finishes it off. DRIFT's floor is `1e-06`
  # and survives, which is why only the variances lost theirs.
  #
  # A floorless variance reaches *exactly* zero, since `log1p_exp` is exactly
  # zero once `1 + exp(x)` rounds to one, and a zero variance is then divided
  # by and differentiated through. The julia backend reads this rather than
  # re-rendering the numbers; see `.ctJuliaParameterTable`.
  #
  # Keyed by cell and kept *off* `ctm$pars`, because parts of the Stan pipeline
  # read that frame's columns by position -- carrying it there as a character
  # column turned Stan's `pop_CINT` into NaN.
  if(is.null(ctm$transformtext) && is.character(ctm$pars$transform)){
    # A cell whose transform column already parses as a bare number (the
    # output of an earlier ctModelTransformsToNum() call, which
    # ctEBadjustModel() makes before handing its adjusted model to ctFit --
    # see R/ctEmpiricalBayesFit.R) is not descriptive source text: it is a
    # transform *code*, with the real expression already discarded, and this
    # column is character-typed regardless because it mixes such codes with
    # genuine expression strings. Recording a bare code as `text` fed
    # .ctJuliaParameterTable() a rendered transform of literally "1", with no
    # param[] reference left for the engine's adjoint to find -- see the
    # comment there. NA leaves that cell to the numeric multiplier/meanscale
    # reconstruction, which is what a bare code needs regardless of whether it
    # arrived that way from the user or from an earlier numeric reduction.
    bareCode <- !is.na(suppressWarnings(as.numeric(ctm$pars$transform)))
    text <- as.character(ctm$pars$transform)
    text[bareCode] <- NA_character_
    ctm$transformtext <- data.frame(
      matrix = as.character(ctm$pars$matrix),
      row = as.integer(ctm$pars$row), col = as.integer(ctm$pars$col),
      text = text, stringsAsFactors = FALSE)
  }
  ctm <- ctModelTransformsToNum(ctm)

  ctm$pars <- ctStanModelCleanctspec(ctm$pars)

  ctm <- T0VARredundancies(ctm)

  if(!all(ctm$pars$transform[!is.na(suppressWarnings(as.integer(ctm$pars$transform)))] %in% c(0,1,2,3,4))) stop('Unknown transform specified -- integers should be 0 to 4')

  #fix binary manifestvariance

  if(any(ctm$manifesttype %in% 2) && !identical(backend, 'julia')){
    stop('Ordinal manifest variables (manifesttype 2) need backend="julia". ',
      'The stan model has no ordinal measurement, so its thresholds would ',
      'never be read; the julia filter integrates the observation over the ',
      'latent instead. Ordinal variable(s): ',
      paste(ctm$manifestNames[ctm$manifesttype %in% 2], collapse=', '), '.',
      call.=FALSE)
  }
  # Same reason as ordinal, and stated separately because the reason a stan fit
  # would be wrong is different: stan has no Poisson measurement at all, so it
  # would treat a count as a Gaussian observation of the log rate and return
  # numbers that look entirely reasonable.
  if(any(ctm$manifesttype %in% 3) && !identical(backend, 'julia')){
    stop('Count manifest variables (manifesttype 3) need backend="julia". ',
      'The stan model has no count measurement, so the observation would be ',
      'treated as Gaussian; the julia filter integrates it against the ',
      'predicted state under a Poisson log link instead. Count variable(s): ',
      paste(ctm$manifestNames[ctm$manifesttype %in% 3], collapse=', '), '.',
      call.=FALSE)
  }
  # Censored is refused on stan for the same reason as the others: stan has no
  # censored measurement, so a value pinned at a limit would be treated as an
  # ordinary observation of that number and the censoring simply ignored.
  if(any(ctm$manifesttype %in% 4) && !identical(backend, 'julia')){
    stop('Censored manifest variables (manifesttype 4) need backend="julia". ',
      'The stan model has no censored measurement, so a value at its limit ',
      'would be read as an ordinary observation; the julia filter integrates ',
      'the censored likelihood against the predicted state instead. Censored ',
      'variable(s): ',
      paste(ctm$manifestNames[ctm$manifesttype %in% 4], collapse=', '), '.',
      call.=FALSE)
  }
  if(any(ctm$manifesttype %in% 2)) .ctDataCategories(datalong, ctm)
  if(any(ctm$manifesttype %in% 3)) .ctDataCounts(datalong, ctm)
  if(any(ctm$manifesttype %in% 4)) .ctDataCensored(datalong, ctm)

  if(any(ctm$manifesttype > 0)){ #if any non continuous variables, (with free parameters)...
    # Censored variables are excluded: a censored observation is Gaussian
    # within its limits, so its measurement standard deviation is the scale of
    # the whole thing and has to stay free. Every other non-Gaussian type
    # supplies its own randomness through the link and would be adding noise on
    # top of noise.
    deterministic <- which(ctm$manifesttype > 0 & ctm$manifesttype != 4)
    errfix <- which(ctm$pars$matrix %in% 'MANIFESTVAR' &
        (ctm$pars$row %in% deterministic |
            ctm$pars$col %in% deterministic) &
        is.na(suppressWarnings(as.numeric(
          ctm$pars$value))))

    if(length(errfix) > 0){
      message('Fixing any free MANIFESTVAR parameters for binary / ordinal indicators to deterministic calculation')
      ctm$pars$value[errfix] <- 1e-5
      ctm$pars[errfix,c('param','transform','multiplier','offset','meanscale','inneroffset','sdscale')] <- NA
      ctm$pars$indvarying[errfix] <- FALSE
    }

    # A *fixed* non-zero variance on a binary indicator is left alone by the
    # block above, and it is almost certainly a mistake: the Bernoulli link
    # already supplies the randomness, so an extra measurement variance adds
    # noise on top of noise. Free ones are fixed silently because there is a
    # right answer; a deliberate value is the user's, so it is questioned
    # rather than overwritten.
    # What the approximation costs, said once, because it is invisible
    # otherwise and it is large.
    #
    # A binary observation is handled by a moment-matched Gaussian update: the
    # predicted probability from `inv_logit`, a finite-difference Jacobian, and
    # `ycov = Jy etacov Jy' + p(1-p)`. The covariance update that follows,
    # `etacov -= K Jy etacov`, is the standard EKF one and ignores the link's
    # curvature, so posterior uncertainty is understated and the understatement
    # compounds over time steps. The filter ends up believing the latent is
    # pinned down, its innovations shrink, and less process noise is needed to
    # explain them.
    #
    # Measured on a one-latent process with true DIFFUSIONcov 0.16, 50
    # subjects, 50 timepoints, observed only through binary indicators:
    #
    #   5 indicators   0.114   (0.71 of truth)
    #  10 indicators   0.107   (0.67)
    #  30 indicators   0.073   (0.46)
    #
    # DRIFT and CINT survive as long as the latent has few binary indicators;
    # the bias gets *worse* with more of them, which is the signature of a
    # systematic error rather than sampling noise -- more data makes it more
    # confidently wrong. A latent that also has a continuous indicator is
    # unaffected in the same fit.
    #
    # The sharpest evidence is `test-ctRaschExampleTest.R`, which fits the same
    # data twice -- linearised, and sampling the states exactly by HMC -- and
    # compares. The item parameters agree to within 0.012. The dynamics do not:
    #
    #   diff  (process noise)   0.254  linearised   0.373  exact
    #   drift_eta1             -0.095  linearised  -0.935  exact
    #
    # A drift of -0.095 against -0.935 is not a small bias: the linearised fit
    # describes a near random walk where the exact one finds strong mean
    # reversion. That test has been failing, and it is this.
    # Backend specific, because they no longer do the same thing. The julia
    # engine integrates the Bernoulli observation against the predicted state
    # (a mode-centred Gauss-Hermite rule on the scalar linear predictor); the
    # stan model moment-matches it to a Gaussian and linearises. On 40
    # replications with 50 subjects and 12 timepoints, RMSE for a true
    # DIFFUSION of 0.8:
    #
    #   indicators   julia   stan
    #            3   0.134   0.449
    #           10   0.075   0.297
    #           30   0.045   0.229
    #
    # Paired on the same data, every cell favours julia (p <= 0.014). Note the
    # shape of it: stan's *bias* is modest, its RMSE is three to five times
    # worse -- the linearised estimate is unstable rather than uniformly low,
    # which is why single-dataset comparisons looked so different from each
    # other.
    if(backend %in% 'julia'){
      message('Binary and ordinal indicators are integrated rather than ',
        'linearised on this backend: the observation is taken against the ',
        'predicted state by quadrature, so DRIFT and DIFFUSION are estimated ',
        'without the linearisation bias the stan path carries.')
      if(any(ctm$manifesttype %in% 2)) message(
        'Ordinal thresholds are reported as the first threshold followed by ',
        'the gap to each subsequent one, which is what keeps them ordered; ',
        'cumulate them to read the thresholds themselves.')
    } else {
      message('Binary indicators use a linearised (moment-matched Gaussian) ',
        'measurement update on the stan backend, which makes DRIFT and ',
        'especially DIFFUSION unreliable for a latent seen only through them. ',
        'Over 40 replications with a true diffusion of 0.8, RMSE was 0.45 with ',
        '3 indicators and 0.23 with 30, against 0.13 and 0.04 for ',
        "backend='julia', which integrates the observation instead. Prefer ",
        'the julia backend for binary data, or treat process noise as ',
        'indicative.')
    }

    binaryrows <- which(ctm$pars$matrix %in% 'MANIFESTVAR' &
        ctm$pars$row %in% which(ctm$manifesttype > 0) &
        ctm$pars$row == ctm$pars$col)
    stated <- binaryrows[!is.na(ctm$pars$value[binaryrows]) &
        abs(ctm$pars$value[binaryrows]) > 1e-4]
    if(length(stated)){
      warning('MANIFESTVAR is fixed to a non-zero value for categorical indicator',
        if(length(stated) > 1) 's ' else ' ',
        paste(ctm$manifestNames[ctm$pars$row[stated]], collapse=', '),
        '. A categorical indicator gets its randomness from its measurement ',
        'link -- the Bernoulli link for binary, the cumulative logit for ',
        'ordinal -- so ',
        'this adds measurement noise on top of it. Set it to 0 unless that is ',
        'meant.', call.=FALSE)
    }}

  ctm$modelmats <- ctStanModelMatrices(ctm) #slow!
  ctm <- ctStanCalcsList(ctm,save=saveComplexPars) #get extra calculations and adjust model spec as needed???

  #store values in ctm
  ctm$intoverpop <- as.integer(intoverpop)
  ctm$nlatentpop <- as.integer(ifelse(ctm$intoverpop ==1, max(ctm$pars$row[ctm$pars$matrix %in% 'T0MEANS']),  ctm$n.latent))
  ctm$intoverstates <- as.integer(intoverstates)
  ctm$priors <- as.integer(priors)
  ctm$stationary <- as.integer(stationary)
  ctm$nlcontrol <- nlcontrol



  #recompile checks
  if(forcerecompile) recompile <- TRUE
  if(naf(!is.na(ctm$rawpopsdbaselowerbound))) recompile <- TRUE
  if(ctm$rawpopsdbase != 'normal(0,1)') recompile <- TRUE
  if(ctm$rawpopsdtransform != 'log1p_exp(2*rawpopsdbase-1) .* sdscale') ctm$recompile <- TRUE
  if(any(ctm$modelmats$matsetup[,'transform'] < -10)) recompile <- TRUE #if custom transforms needed

  ncalcsNoJ<- length(unlist(ctm$modelmats$calcs)[!grepl('JAx[',unlist(ctm$modelmats$calcs),fixed=TRUE)])
  if(ncalcsNoJ > 0) recompile <- TRUE

  if(!recompile &&
      length(unlist(ctm$modelmats$calcs)[!grepl('JAx[',unlist(ctm$modelmats$calcs),fixed=TRUE)])>0)
    message('Finite difference jacobian used to avoid recompiling -- use forcerecompile=TRUE for analytic jacobians')


  #further model adjustments conditional on recompile
  if(!recompile){ #then use finite diffs for some elements

    #collect row and column of complicated jacobian elements into vector
    ctm$JAxfinite <- array(as.integer(unique(
      unlist(ctm$modelmats$matsetup[ctm$modelmats$matsetup$matrix %in% 52 &
          ctm$modelmats$matsetup$when == -999, 'col']))))# &
    # ctm$modelmats$matsetup$copyrow < 1,c('row','col')]))))

    ctm$Jyfinite <- array(as.integer(unique(
      unlist(ctm$modelmats$matsetup[ctm$modelmats$matsetup$matrix %in% 54 &
          ctm$modelmats$matsetup$when == -999, 'col']))))

  }
  if(recompile) ctm$JAxfinite <- ctm$Jyfinite <- array(as.integer(c()))
  ctm$recompile <- recompile


  standata <- ctStanData(ctm,datalong,optimize=optimize, sameInitialTimes=sameInitialTimes) #bit slow
  standata$verbose=as.integer(verbose)
  standata$savesubjectmatrices=as.integer(savesubjectmatrices)
  standata$gendata=as.integer(gendata)

  if(standata$savesubjectmatrices==1L) savescores = TRUE
  standata$savescores=as.integer(savescores)

  # Resolved here rather than after the julia branch below, which returns before
  # ever reaching the old resolution site: `cores='maxneeded'` arrived at
  # .ctFitJuliaBackend() as a string, `as.integer()` made it NA, and the NA guard
  # there turned it into 1. So the documented default whenever `optimize=FALSE`
  # silently meant single-core for the julia backend.
  #
  # `chains` does not cap the julia backend -- it has no MCMC chains. Its
  # parallelism is over subject chunks, and `ctsem_tune_chunks!` measures within
  # whatever ceiling it is given, so the ceiling is simply the machine.
  if(is.character(cores) && cores=='maxneeded') {
    cores <- if(backend %in% 'julia') max(1, parallel::detectCores()-1) else
      max(1,min(c(chains,parallel::detectCores()-1)))
  }

  # `args` (captured above, at the point nothing had been routed yet) is what
  # the caller literally passed, or the formal default -- 'auto', 'maxneeded'
  # and all. `argsresolved` is what the fit actually runs with, once 'auto'
  # routing and backend-independent defaults are settled. Before this, a stan
  # fit's `$args` was the raw call and a julia fit's `$args` was a curated
  # resolved list, so `fit$args$intoverpop` and `fit$args$cores` meant opposite
  # things across backends for the same call (review/jobs/J10). Both sublists
  # are attached below, under `$args$input` and `$args$resolved`, and mean the
  # same thing on both backends -- the fields overridden here are exactly the
  # ones that get routed or cast between capture and use.
  argsresolved <- args
  argsresolved$backend <- backend
  argsresolved$cores <- cores
  argsresolved$intoverpop <- intoverpopmethod
  argsresolved$priors <- as.logical(priors)
  argsresolved$optimize <- isTRUE(optimize)
  argsresolved$intoverstates <- isTRUE(intoverstates)

  if(backend %in% 'julia') {
    .ctJuliaUnsupported(ctm, optimize=optimize, priors=priors,
      intoverpop=intoverpop, gendata=gendata,
      stanmodeltext=stanmodeltext, compileArgs=compileArgs,
      forcerecompile=forcerecompile, intoverstates=intoverstates,
      optimcontrol=optimcontrol)
    # `optimize` and `intoverpop` are orthogonal here. `intoverpop` says which
    # random effects are integrated out and how; `optimize` says whether the
    # remaining parameters are maximised or sampled. Every combination is
    # meaningful for this backend:
    #
    #   optimize  intoverpop     what runs                 sampled dimension
    #   TRUE      'laplace'      Laplace ML                --
    #   TRUE      TRUE           augmented ML              --
    #   FALSE     'laplace'      NUTS, Laplace marginal    npar
    #   FALSE     TRUE           NUTS, filter marginal     npar
    #   FALSE     FALSE          NUTS over parameters      npar + effects
    #                            *and* effects
    #
    # Only 'laplace' is julia-only; the guard for that is above. `'none'` is
    # the third route the engine needs, and it prepares the Laplace structure
    # -- which is what says *which* parameters vary -- without integrating.
    juliaintoverpop <- if(identical(intoverpopmethod,'laplace')) 'laplace' else
      if(intoverpop) 'augmented' else
        if(!optimize && any(ctm$pars$indvarying[is.na(ctm$pars$value)])) 'none' else
          'augmented'
    juliafit <- .ctFitJuliaBackend(datalong=datalong, model=ctm, prepared_data=standata, inits=inits,
      cores=cores, backendcontrol=backendcontrol, optimcontrol=optimcontrol,
      verbose=verbose, fit=fit, priors=priors, optimize=optimize,
      chains=chains, iter=iter, control=control,
      intoverpop=juliaintoverpop, intoverstates=intoverstates)
    # Replaces whatever narrower `$args` the julia backend built internally
    # (it only ever had the resolved settings, and not all of them) with the
    # two-sublist form every fit now carries -- see the `argsresolved` comment
    # above. This also reaches the `fit=FALSE` case: `.ctFitJuliaBackend()`
    # returns the prepared model spec then, unclassed by `$args` before, and
    # assigning a list element to it here does not disturb its class.
    juliafit$args <- list(input = args, resolved = argsresolved)
    # `plot` draws the trace *after* the fit here, not during it.
    #
    # The Stan path can plot live because it writes sample files a second
    # process reads. A julia fit is one blocking call into the engine, so R
    # cannot draw anything until it returns -- there is no point in this
    # function where a live plot could be made. What is drawn is the same
    # information, recorded every iteration and handed back on the fit; for
    # genuinely live output, `optimcontrol$callback` is called while the fit
    # runs and can draw whatever it likes.
    if(isTRUE(fit) && !identical(plot, FALSE) && !is.null(juliafit$trace)) {
      try(ctTracePlot(juliafit), silent=TRUE)
    }
    return(juliafit)
  }

  # print(standata$savesubjectmatrices)

  #####post model / data checks
  # (`cores='maxneeded'` is resolved above, before the julia backend returns.)

  if(is.logical(stanmodeltext)) {
    stanmodeltext<- ctStanModelWriter(ctm, gendata, ctm$modelmats$extratforms,ctm$modelmats$matsetup)
  }




  if(fit){
    # if(gendata && stanmodels$ctsmgen@model_code != stanmodeltext) recompile <- TRUE
    # if(!gendata && paste0(stanmodels$ctsm@model_code) != paste0(stanmodeltext)) recompile <- TRUE

    # STAN_NUM_THREADS <- Sys.getenv('STAN_NUM_THREADS',unset=NA)
    # Sys.setenv(STAN_NUM_THREADS=cores)

    if(recompile || forcerecompile) {
      message('Compiling model...')

      #r4.2 / windows / old rstan check
      if(.Platform$OS.type=="windows" && R.version$major %in% 4 && as.numeric(R.version$minor) >= 2 &&
          unlist(utils::packageVersion('rstan'))[2] < 25){
        stop('
*****
Compiling not possible with R version 4.2+ on Windows with Rstan version < 2.26
To upgrade rstan, close and restart all R sessions then run:

install.packages("StanHeaders", repos = c("https://mc-stan.org/r-packages/", getOption("repos")))
install.packages("rstan", repos = c("https://mc-stan.org/r-packages/", getOption("repos")))
*****')
        # a=readline('Attempt to upgrade Rstan from Stan repository? y/n')
        # if(a %in% c('yes','y','Y','Yes','YES')){
        #   message(
        #   install.packages("StanHeaders", repos = c("https://mc-stan.org/r-packages/", getOption("repos")))
        #   install.packages("rstan", repos = c("https://mc-stan.org/r-packages/", getOption("repos")))
        # }
      }
      compileArgs$model_name='ctsem'
      compileArgs$model_code=stanmodeltext
      compileArgs$auto_write=TRUE
      sm <- do.call(stan_model,compileArgs)
      # ,allow_undefined = TRUE,verbose=TRUE,
      # includes = paste0(
      #   '\n#include "', file.path(getwd(), 'syl2.hpp'),'"',
      #   '\n')
      if(saveCompile){
        if(exists(x = 'ctsem.compiled',envir= parent.frame())
          && !'stanmodel' %in% class(get('ctsem.compiled',envir = parent.frame()))){
          warning('ctsem.compiled object already exists, not saving compile')
        } else  assign(x = 'ctsem.compiled',sm,envir = parent.frame())
      }
    }
    if(!recompile && !forcerecompile) {
      if(!gendata) sm <- stanmodels$ctsm else sm <- stanmodels$ctsmgen
    }


    # configure inits ---------------------------------------------------------
    initOptim <- (length(inits)==1 && (inits=='optimize' || inits=='Optimize' || inits=='optimise' || inits=='Optimise'))
    if(optimize || initOptim){ #then set optimcontrol list
      optimcontrol$cores <- cores
      optimcontrol$verbose <- verbose
      optimcontrol$priors <- as.logical(priors)
      optimcontrol$standata=standata
      optimcontrol$sm=sm
      optimcontrol$init=inits
      optimcontrol$plot=plot
      optimcontrol$matsetup <- data.frame(ctm$modelmats$matsetup)
    }

    if(!optimize && !is.null(inits)){
      if('list' %in% class(inits)){
        staninits=inits
      } else {
        if(initOptim){ #then first optimize to get inits
          if(!intoverpop && length(unique(datalong[[ctm$subjectIDname]]) > 1) && any(ctm$pars$indvarying)) stop('Cannot optimize to get inits unless intoverpop=TRUE')
          optimcontrol$init <- NULL
          optimcontrol$tol=1e-7
          if(!intoverpop & ! intoverstates) stop('Cannot initialize with optimization unless intoverpop and intoverstates are set to TRUE')
          inits <- do.call(stanoptimis,optimcontrol)$rawest
        }
        sf <- stan_reinitsf(sm,standata)
        staninits <- list()
        if(chains > 1){ #set all chains to same inits
          for(i in 1:chains){
            staninits[[i]]<-constrain_pars(sf,inits+rnorm(length(inits),0,.01))
          }
        }
      }
    }


    if(!optimize){

      #control arguments for rstan
      # if(is.null(control$adapt_term_buffer)) control$adapt_term_buffer <- min(c(iter/10,max(iter-20,75)))
      if(is.null(control$adapt_delta)) control$adapt_delta <- .8
      if(is.null(control$adapt_window)) control$adapt_window <- 5
      if(is.null(control$max_treedepth)) control$max_treedepth <- 10
      if(is.null(control$adapt_init_buffer)) control$adapt_init_buffer=2
      if(is.null(control$stepsize)) control$stepsize=.001
      if(is.null(control$metric)) control$metric='diag_e'


      message('Sampling...')
      #
      stanargs <- list(object = sm,
        init_r=.03,
        save_warmup=as.logical(plot),
        refresh=20,
        iter=iter,
        data = standata, chains = chains, control=control,
        cores=cores,
        ...)
      if(!is.null(inits)) stanargs$init=staninits

      if(plot==TRUE) stanfit <- suppressWarnings(list(stanfit=do.call(stanWplot,stanargs))) else stanfit <- suppressWarnings(list(stanfit=do.call(sampling,stanargs)))

      #find the median sample and compute kalman scores etc for this
      # browser()
      e=rstan::extract(stanfit$stanfit)
      # middle <- which(abs(e$ll-quantile(e$ll,.5)) == min(abs(e$ll-quantile(e$ll,.5) )))
      # middle <- which(e$ll==max(e$ll))
      stanfit$rawposterior <- t(stan_unconstrainsamples(fit = stanfit$stanfit,standata = standata))
      stanfit$rawest <- apply(stanfit$rawposterior,2,median)
    }

    if(optimize==TRUE) {
      stanfit <- do.call(stanoptimis,optimcontrol) #eval(parse(text=opcall))

      #update data that may have changed during optimization
      for(ni in names(stanfit$standata)){
        standata[[ni]] <- stanfit$standata[[ni]]
      }
      if(ctm$n.TIpred>0){
        ctm$modelmats$TIPREDEFFECTsetup <- stanfit$standata$TIPREDEFFECTsetup
        ms <- ctm$modelmats$matsetup
        ms$tipred <- 0L
        parswithtipreds <- sort(unique(ms$param[ms$param >0 & ms$when %in% c(0,-1) & ms$copyrow < 1]))
        parswithtipreds<-parswithtipreds[apply(stanfit$standata$TIPREDEFFECTsetup,1,sum)>0]
        ms$tipred[ms$param >0 & ms$when %in% c(0,-1) & ms$copyrow < 1 & ms$param %in% parswithtipreds] <- 1L
        ctm$modelmats$matsetup <- ms
      }
    }

    # if(is.na(STAN_NUM_THREADS)) Sys.unsetenv('STAN_NUM_THREADS') else Sys.setenv(STAN_NUM_THREADS = STAN_NUM_THREADS) #reset sys env
  } # end if fit==TRUE
  #convert missings back to NA's for data output
  standataout<-standata
  standataout$Y[standataout$Y==99999] <- NA
  standataout$tipreds[standataout$tipreds==99999] <- NA
  # standataout <- utils::relist((standataout),skeleton=standata)

  setup=list(recompile=recompile,idmap=standata$idmap,matsetup=ctm$modelmats$matsetup,matvalues=ctm$modelmats$matvalues,
    popsetup=ctm$modelmats$matsetup[ctm$modelmats$matsetup$when %in% c(0,-1) & ctm$modelmats$matsetup$param > 0,],
    popvalues=ctm$modelmats$matvalues[ctm$modelmats$matsetup$when %in% c(0,-1) & ctm$modelmats$matsetup$param > 0,],
    extratforms=ctm$modelmats$extratforms)
  if(fit) {
    stanfit$transformedparsfull <- suppressMessages(stan_constrainsamples(sm = sm,standata = standata,
      savesubjectmatrices = TRUE, samples = matrix(stanfit$rawest,1),cores=1,savescores=TRUE,pcovn=5000))

    out <- list(args=list(input=args, resolved=argsresolved),
      setup=setup,
      stanmodeltext=stanmodeltext, data=standataout, ctdatastruct=datalong[c(1,nrow(datalong)),],standata=standata,
      ctstanmodelbase=ctstanmodel, ctstanmodel=ctm,stanmodel=sm, stanfit=stanfit)
    out$backend <- 'stan'
    class(out) <- c('ctStanFit','ctFit')
    out$stanfit$kalman<-suppressMessages(ctKalmanArray(out,pointest = TRUE))
  }

  if(!fit) out=list(args=list(input=args, resolved=argsresolved),setup=setup,
    stanmodeltext=stanmodeltext,data=standataout,  ctdatastruct=datalong[c(1,nrow(datalong)),],standata=standata,
    ctstanmodelbase=ctstanmodel,  ctstanmodel=ctm)


  return(out)
}

#' @export
ctStanFit <- ctFit

