# ctFitCheckCov with group-specific model-implied lagged covariances

#' Visual lagged covariance or correlation diagnostics for ctsem fits.
#'
#' Compares empirical lagged covariances or correlations with the same quantity
#' computed from data generated by the fitted model. For each requested lag,
#' covariances or correlations are computed across subjects for each matching
#' observation-index pair, then averaged over observation-index pairs.
#' \code{ctFitCovCheck} is maintained as a backward-compatible alias.
#'
#' @param fit A fitted object from \code{\link{ctFit}}, from either backend.
#' @param cor Logical; if `TRUE` correlations are analysed instead of covariances.
#' @param plot Logical; if `TRUE` (default) a `ggplot2` object (or list of plots)
#'   is returned. If `FALSE`, the raw `data.table` with diagnostics is returned.
#' @param splitby Optional character string giving the variable name on which to
#'   split subjects or observations. Numeric variables are split at the subject
#'   mean and then at the grand mean by default; non-numeric variables are treated as
#'   groups and may vary within subject.
#' @param data Optional long-format data to use for the empirical lagged
#'   covariances or correlations. If omitted, the fitted data are used.
#' @param lags Non-negative integer vector giving observation lags to compare.
#' @param variables Optional character vector of manifest variables to include.
#'   Defaults to all manifest variables in the model.
#' @param splitdata Optional data containing `splitby`, useful when the split
#'   variable was not in the fitted model. If omitted, `data` is used when
#'   supplied, otherwise the fitted data are used.
#' @param split Split rule for `splitby`: `"median"`, `"mean"`, `"quantile"`,
#'   `"factor"`, or `"none"`. If `NULL`, numeric split variables use
#'   `"mean"` and non-numeric split variables use `"factor"`.
#' @param breaks Number of quantile groups when `split = "quantile"`.
#' @param nsamples Optional number of generated data sets to use. Existing
#'   generated data are reused when present; otherwise `ctGenerateFromFit` is
#'   called.
#' @param minpairn Minimum number of complete paired observations required for
#'   an empirical or generated lagged covariance/correlation.
#' @param cores Number of cores to use for generating data and summarising
#'   generated samples.
#' @param keep If `"samples"`, draw-level model diagnostics are attached as the
#'   `"samples"` attribute of the returned data.
#' @return Either a plot/list of plots (default, given by `ctFitCovCheckPlot`) or
#'   a `data.table`.
#' @seealso \code{\link{ctFitCheck}}, the whole diagnostic dashboard, of which
#'   this is the focused lagged-covariance panel.
#' @aliases ctFitCovCheck
#' @export
#' @examples
#' \donttest{
#' # Lagged correlations for all manifest variables, lags 0 to 3.
#' ctFitCheckCov(ctstantestfit, cor = TRUE, lags = 0:3, plot = TRUE)
#' 
#' # Lagged covariances for one manifest variable.
#' ctFitCheckCov(ctstantestfit, cor = FALSE, variables = "Y1", lags = 0:5,
#'   plot = FALSE)
#'
#' # Split the diagnostic by a time independent predictor in the fitted data.
#' gg <- ctFitCheckCov(ctstantestfit, cor = TRUE, splitby = "TI1", lags = 0:3)
#' print(gg[[1]])
#'
#' # Use an external subject-level variable for the split.
#' splitdat <- unique(data.frame(ctstantestdat)[, "id", drop = FALSE])
#' splitdat$group <- rep(c("a", "b"), length.out = nrow(splitdat))
#' ctFitCheckCov(ctstantestfit, splitby = "group", splitdata = splitdat,
#'   lags = 0:2)
#'
#' # Split observations into early and late periods within each subject.
#' dat <- data.table::as.data.table(data.frame(ctstantestdat))
#' dat[, period := ifelse(time <= stats::median(time, na.rm = TRUE),
#'   "early", "late"), by = id]
#' ctFitCheckCov(ctstantestfit, data = dat, splitby = "period",
#'   split = "factor", lags = 0:2)
#' }
ctFitCheckCov <- function(fit, cor = TRUE, plot = TRUE, splitby = NULL,
  data = NULL, lags = 0:10, variables = NULL, splitdata = data, split = NULL,
  breaks = 2, nsamples = NULL, minpairn = 10, cores = 1,
  keep = c("summary", "samples")) {

  if(!inherits(fit,c('ctStanFit','ctJuliaFit'))) stop('Not a ctsem fit object')
  ctmb <- .ctFitModelObject(fit)
  keep <- match.arg(keep)
  if(is.null(split)) split <- if(is.null(splitby)) "none" else NA_character_
  if(!is.na(split)) split <- match.arg(split,
    c("none", "median", "mean", "quantile", "factor"))
  
  lags <- unique(as.integer(lags))
  if(any(is.na(lags)) || any(lags < 0)) stop('lags must be non-negative integers')
  variables <- if(is.null(variables)) ctmb$manifestNames else variables
  if(!all(variables %in% ctmb$manifestNames)) {
    stop('variables must be manifest variables in the fitted model')
  }
  cores <- suppressWarnings(as.integer(cores[1]))
  if(!is.finite(cores) || is.na(cores) || cores < 1) cores <- 1L
  minpairn <- suppressWarnings(as.integer(minpairn[1]))
  if(!is.finite(minpairn) || is.na(minpairn) || minpairn < 2) minpairn <- 2L
  
  idname <- ctmb$subjectIDname
  timename <- ctmb$timeName
  
  .fit_data <- function(){
    as.data.table(.ctFitLongData(fit))
  }
  
  .prepare_data <- function(d){
    if(is.null(d)) d <- .fit_data()
    d <- as.data.table(d)
    if(!idname %in% names(d)) stop('data must contain the model subject id column: ', idname)
    if(!all(variables %in% names(d))) {
      stop('data must contain all requested manifest variables')
    }
    d <- copy(d)
    if(timename %in% names(d)) setorderv(d, c(idname, timename))
    d[, WhichObs := seq_len(.N) - 1L, by = idname]
    d
  }
  
  .split_groups <- function(d, sd){
    subjects <- unique(d[, .(id = get(idname))])
    setnames(subjects, 'id', idname)
    if(is.null(splitby) || identical(split, "none")) {
      subjects[, .splitgroup := 'All']
      return(subjects)
    }
    if(is.null(sd)) sd <- d
    sd <- as.data.table(sd)
    if(!idname %in% names(sd)) stop('splitdata must contain the model subject id column: ', idname)
    if(!splitby %in% names(sd)) stop('splitby variable not found in data or splitdata: ', splitby)
    sd <- copy(sd)
    if(!'WhichObs' %in% names(sd)) {
      if(timename %in% names(sd)) setorderv(sd, c(idname, timename))
      sd[, WhichObs := seq_len(.N) - 1L, by = idname]
    }
    
    splitrule <- if(is.na(split)) {
      if(is.numeric(sd[[splitby]])) "mean" else "factor"
    } else split
    rowlevel <- anyDuplicated(sd[[idname]]) &&
      (!is.numeric(sd[[splitby]]) || splitrule == "factor")
    if(rowlevel) {
      sx <- copy(sd[, c(idname, 'WhichObs', splitby), with = FALSE])
      sx[, .splitgroup := as.character(get(splitby))]
      sx[is.na(.splitgroup), .splitgroup := 'Missing']
      return(sx[, c(idname, 'WhichObs', '.splitgroup'), with = FALSE])
    }
    
    sx <- copy(sd[, c(idname, splitby), with = FALSE])
    if(is.numeric(sx[[splitby]])) {
      sx <- sx[, .(.splitscore = mean(get(splitby), na.rm = TRUE)), by = idname]
      sx[is.nan(.splitscore), .splitscore := NA_real_]
      if(splitrule == "factor") sx[, .splitgroup := as.character(.splitscore)]
      if(splitrule == "mean") {
        cutpoint <- mean(sx$.splitscore, na.rm = TRUE)
        sx[, .splitgroup := ifelse(.splitscore > cutpoint, "High", "Low")]
      }
      if(splitrule == "median") {
        cutpoint <- stats::median(sx$.splitscore, na.rm = TRUE)
        sx[, .splitgroup := ifelse(.splitscore > cutpoint, "High", "Low")]
      }
      if(splitrule == "quantile") {
        probs <- seq(0, 1, length.out = max(2L, breaks) + 1L)
        qs <- unique(stats::quantile(sx$.splitscore, probs = probs, na.rm = TRUE,
          names = FALSE))
        if(length(qs) < 2L) sx[, .splitgroup := 'All'] else {
          sx[, .splitgroup := as.character(cut(.splitscore, breaks = qs,
            include.lowest = TRUE))]
        }
      }
    } else {
      sx <- sx[, .(.splitscore = {
        z <- get(splitby)
        z <- z[!is.na(z)]
        if(length(z)) as.character(z[1]) else NA_character_
      }), by = idname]
      sx[, .splitgroup := as.character(.splitscore)]
    }
    sx <- sx[, c(idname, '.splitgroup'), with = FALSE]
    out <- merge(subjects, sx, by = idname, all.x = TRUE)
    out[is.na(.splitgroup), .splitgroup := 'Missing']
    out
  }
  
  .pair_stat <- function(x, y){
    ok <- stats::complete.cases(x, y)
    n <- sum(ok)
    if(n < minpairn) return(list(value = NA_real_, n = n))
    x <- x[ok]
    y <- y[ok]
    if(cor) {
      if(stats::sd(x) == 0 || stats::sd(y) == 0) return(list(value = NA_real_, n = n))
      return(list(value = suppressWarnings(stats::cor(x, y)), n = n))
    }
    list(value = stats::cov(x, y), n = n)
  }
  
  .lagged_stat <- function(d, xcol, ycol){
    bytime <- d[, {
      st <- .pair_stat(get(xcol), get(ycol))
      .(timevalue = st$value, timen = st$n)
    }, by = WhichObs]
    list(value = mean(bytime$timevalue, na.rm = TRUE),
      n = sum(bytime$timen, na.rm = TRUE),
      ntime = sum(!is.na(bytime$timevalue)))
  }
  
  .lag_summary <- function(d, sample = NA_integer_){
    out <- vector('list', length(lags))
    for(li in seq_along(lags)){
      lagi <- lags[li]
      cur <- d[, c(idname, 'WhichObs', '.splitgroup', variables), with = FALSE]
      lagd <- d[, c(idname, 'WhichObs', variables), with = FALSE]
      lagd[, WhichObs := WhichObs + lagi]
      setnames(lagd, variables, paste0('.lag_', variables))
      paird <- merge(cur, lagd, by = c(idname, 'WhichObs'), all = FALSE,
        sort = FALSE, allow.cartesian = FALSE)
      splitlevels <- unique(d$.splitgroup)
      rowout <- vector('list', length(variables) * length(variables) *
          length(splitlevels))
      ri <- 0L
      for(si in splitlevels){
        sdat <- paird[.splitgroup == si]
        for(rv in variables){
          for(cv in variables){
            st <- .lagged_stat(sdat, rv, paste0('.lag_', cv))
            ri <- ri + 1L
            rowout[[ri]] <- data.table(sample = sample, rowvar = rv, colvar = cv,
              lag = lagi, split = si, value = st$value, n = st$n,
              ntime = st$ntime)
          }
        }
      }
      out[[li]] <- rbindlist(rowout)
    }
    rbindlist(out)
  }
  
  dat <- .prepare_data(data)
  splitgroups <- .split_groups(dat, splitdata)
  splitmergeby <- intersect(c(idname, 'WhichObs'), names(splitgroups))
  dat <- merge(dat, splitgroups, by = splitmergeby, all.x = TRUE, sort = FALSE)
  emp <- .lag_summary(dat)
  setnames(emp, c('value', 'n', 'ntime'), c('empirical', 'n_empirical',
    'ntime_empirical'))
  emp[, sample := NULL]
  
  if(is.null(fit$generated)) {
    gensamples <- if(is.null(nsamples)) 200L else as.integer(nsamples[1])
    message('No generated data found, generating -- for faster repeated performance use ctGenerateFromFit first')
    fit <- ctGenerateFromFit(fit, nsamples = gensamples, cores = cores)
  }
  if(nrow(dat) != dim(fit$generated$Y)[2]) {
    stop('The empirical data used for ctFitCheckCov must have the same row structure as fit$generated$Y')
  }
  available_samples <- dim(fit$generated$Y)[1]
  samples <- seq_len(available_samples)
  if(!is.null(nsamples)) samples <- samples[seq_len(min(as.integer(nsamples[1]), available_samples))]
  varidx <- match(variables, dimnames(fit$generated$Y)[[3]])
  if(any(is.na(varidx))) varidx <- match(variables, ctmb$manifestNames)
  
  basedat <- dat[, c(idname, 'WhichObs', '.splitgroup'), with = FALSE]
  .generated_one <- function(i){
    gd <- copy(basedat)
    ymat <- matrix(aperm(fit$generated$Y[i, , varidx, drop = FALSE], c(2, 1, 3)),
      ncol = length(varidx))
    ydt <- as.data.table(ymat)
    setnames(ydt, variables)
    gd[, (variables) := ydt]
    .lag_summary(gd, sample = i)
  }
  
  cores <- min(cores, length(samples))
  if(cores > 1L && requireNamespace('future.apply', quietly = TRUE) &&
      requireNamespace('future', quietly = TRUE)) {
    oldplan <- future::plan()
    on.exit(future::plan(oldplan), add = TRUE)
    future::plan(future::multisession, workers = cores)
    gens <- rbindlist(future.apply::future_lapply(samples, .generated_one,
      future.seed = TRUE))
  } else {
    if(cores > 1L) warning('future and future.apply are required for parallel ctFitCheckCov summaries; using one core')
    gens <- rbindlist(lapply(samples, .generated_one))
  }
  
  gensum <- gens[, .(
    q025 = stats::quantile(value, .025, na.rm = TRUE),
    q50 = stats::quantile(value, .5, na.rm = TRUE),
    q975 = stats::quantile(value, .975, na.rm = TRUE),
    sd = stats::sd(value, na.rm = TRUE),
    mean = mean(value, na.rm = TRUE),
    n_model_mean = mean(n, na.rm = TRUE),
    ntime_model_mean = mean(ntime, na.rm = TRUE)
  ), by = .(rowvar, colvar, lag, split)]
  
  checkfit <- merge(emp, gensum, by = c('rowvar', 'colvar', 'lag', 'split'),
    all = TRUE, sort = FALSE)
  sigtol <- sqrt(.Machine$double.eps)
  checkfit[, Sig := empirical > q975 + sigtol | empirical < q025 - sigtol]
  if(cor) checkfit[rowvar == colvar & lag == 0, Sig := FALSE]
  checkfit[, stat := if(cor) 'correlation' else 'covariance']
  if(!is.null(splitby)) checkfit[, (splitby) := split]
  setcolorder(checkfit, c('rowvar', 'colvar', 'lag', 'split',
    if(!is.null(splitby)) splitby, 'stat', 'empirical', 'q025', 'q50', 'q975',
    'mean', 'sd', 'n_empirical', 'n_model_mean', 'ntime_empirical',
    'ntime_model_mean', 'Sig'))
  setattr(checkfit, 'ctFitCovCheck_cor', cor)
  if(keep == "samples") setattr(checkfit, 'samples', gens)
  
  sigprop <- mean(checkfit$Sig[!(cor & checkfit$rowvar == checkfit$colvar &
        checkfit$lag == 0)], na.rm = TRUE)
  message(sprintf("Proportion of empirical lagged %s cells outside model 95%% interval = %.3f",
    if(cor) "correlation" else "covariance", sigprop))
  
  if(plot) {
    return(ctFitCovCheckPlot(checkfit, maxlag = max(lags), vars = variables,
      splitvar = if(is.null(splitby)) NA else splitby, cor = cor))
  }
  checkfit
}

#' @export
ctFitCovCheck <- ctFitCheckCov



#' @title ctFitCovCheckPlot
#' @description Plot the results of ctFitCheckCov.
#' @param x Data output from `ctFitCheckCov(..., plot = FALSE)`. If a ggplot
#'   object or list of ggplot objects is supplied, it is returned unchanged.
#' @param maxlag Maximum lag to plot.
#' @param vars Optional character vector of variable names to plot. If `NA`, all variables are plotted.
#' @param splitvar Optional character string specifying a variable to split the plot by.
#' @param cor Logical; if `TRUE`, plot correlations instead of covariances. (label change)
#' @param ... not used.
#' @return ggplot object.
#' @examples
#' \dontrun{
#' ctFitCovCheckPlot(ctFitCheckCov(ctstantestfit,cor=TRUE,plot=FALSE),maxlag=3)
#' }
#' @export
#'  

ctFitCovCheckPlot <- function(x, maxlag = 10,vars=NA,splitvar=NA,cor=FALSE,...) {
  
  if(inherits(x, 'ggplot')) return(x)
  if(is.list(x) && length(x) > 0 && all(vapply(x, function(z) inherits(z, 'ggplot'),
      logical(1)))) return(x)
  
  gg <- list()
  checkfit <- as.data.table(x)
  if('.RowVar' %in% names(checkfit)) {
    setnames(checkfit, old = c('.RowVar', '.ColVar'), new = c('rowvar', 'colvar'),
      skip_absent = TRUE)
    if(!'lag' %in% names(checkfit)) {
      checkfit[, lag := as.numeric(.ObsRow) - as.numeric(.ObsCol)]
      setnames(checkfit, 'value', 'empirical', skip_absent = TRUE)
    }
  }
  if(is.null(attr(checkfit, 'ctFitCovCheck_cor'))) {
    attrcor <- cor
  } else attrcor <- attr(checkfit, 'ctFitCovCheck_cor')
  ylabel <- if(attrcor) 'Correlation with ' else 'Covariance with '
  if(!all(is.na(vars))) checkfit <- checkfit[rowvar %in% vars & colvar %in% vars,]
  checkfit <- checkfit[lag <= maxlag & lag >= 0]
  
  splitcol <- if(!all(is.na(splitvar)) && splitvar %in% names(checkfit)) splitvar else 'split'
  has_split <- splitcol %in% names(checkfit) && length(unique(checkfit[[splitcol]])) > 1L
  
  for(rowvari in unique(checkfit$rowvar)) {
    filtered_data <- checkfit[rowvar == rowvari]
    if(nrow(filtered_data) == 0) next
    if(has_split) {
      dodge <- position_dodge(width = 0.35)
      gg[[rowvari]] <- ggplot(filtered_data,
          aes(x = lag, colour = factor(get(splitcol)),
            group = factor(get(splitcol)))) +
        geom_point(aes(y = empirical, #alpha = n_empirical,
            shape = "Empirical"),
          position = dodge, size = 3, show.legend = TRUE) +
        geom_errorbar(aes(ymin = q025, ymax = q975, y = q50,
            linetype = "Model implied 95%"),
          position = dodge, width = 0.15, linewidth = .4,
          show.legend = TRUE) +
        scale_shape_manual(name = NULL, values = c("Empirical" = 16),
          breaks = "Empirical") +
        scale_linetype_manual(name = NULL,
          values = c("Model implied 95%" = "solid"),
          breaks = "Model implied 95%") +
        theme_bw() +
        geom_hline(yintercept = 0, linetype = 'dotted') +
        facet_wrap(~ colvar) +
        labs(x = 'Lag (observations)', y = paste0(ylabel, rowvari),
          colour = splitcol, alpha = 'Paired observations') +
        guides(
          colour = guide_legend(title = splitcol, order = 1),
          shape = guide_legend(order = 2,
            override.aes = list(linetype = 0, linewidth = 3,
              colour = "black")),
          linetype = guide_legend(order = 2,
            override.aes = list(shape = NA, linewidth = 1,
              colour = "black")),
          alpha = 'none') +
        theme(legend.position = 'bottom')
    } else {
      gg[[rowvari]] <- ggplot(filtered_data,
          aes(x = lag, y = empirical)) +
        geom_point(aes(color = "Mean sample estimate"), size = 2) +
        geom_errorbar(aes(color = "Model implied 95%",
            ymin = q025, ymax = q975, y = q50),
          width = 0.15, linewidth = .4) +
        theme_bw() +
        geom_hline(yintercept = 0, linetype = 'dotted') +
        geom_vline(xintercept = 0, linetype = 'dotted') +
        facet_wrap(~ colvar) +
        labs(x = 'Lag (observations)', y = paste0(ylabel, rowvari),
          color = '', alpha = 'Paired observations') +
        scale_color_manual(values = c("Mean sample estimate" = "red",
            "Model implied 95%" = "black")) +
        guides(alpha = 'none') +
        theme(legend.position = 'bottom')
    }
  }
  
  return(gg)
}


ctDataMelt <- function(dat,id='id',by='time', combinevars=NULL){
  if(!is.null(combinevars)) {
    dat <- ctDataCombineSplit(dat = dat,idvars = c(id,by),vars = combinevars)
  }
  if(is.null(combinevars)) dat <- melt(dat,id.vars = c(id,by))
  return(dat)
}

#takes list of vars, combines according to structure
ctDataCombineSplit <- function(dat, idvars, vars){ #no splits yet
  ldat=as.data.table(dat)
  
  idvarcombine <- idvars[which(idvars %in% names(vars) & !idvars %in% unlist(vars))]
  if(length(idvarcombine) > 0){
    for(vi in 1:length(idvarcombine)){
      # ldat[,eval(idvarcombine[vi]):= mean(eval(vars[[idvarcombine[vi]]]))]
      ldat[[eval(idvarcombine[vi])]] <- apply(data.frame(ldat)[,vars[[idvarcombine[vi]]]],1,mean,na.rm=TRUE)
    }
  }
  
  ldat <- melt(data = ldat,id.vars = idvars)
  
  #remove unneeded variables
  # vars <- fit$ctstanmodel$manifestNames
  ldat <- ldat[variable %in% eval(unlist(vars))]
  
  #combine variables
  # combinevars=list(ithr=c('T1ithr','T2ithr','T3ithr','T4ithr'),
  #   itfa=c('T1itfa','T2itfa','T3itfa','T4itfa'),
  #   ashr=c('T1ashr','T2ashr','T3ashr','T4ashr'),
  #   asfa=c('T1asfa','T2asfa','T3asfa','T4asfa') )
  
  ldat$variable <- as.character(ldat$variable)
  ldat <- as.data.frame(ldat)
  for(vi in 1:length(vars)){
    ldat[ldat$variable %in% vars[[vi]],'variable'] <- names(vars)[vi]
  }
  ldat <- as.data.table(ldat)
  
}


meltcov <- function(covm){
  if(is.null(dimnames(covm))) dimnames(covm) = list(paste0('v',1:nrow(covm)),
    paste0('v',1:ncol(covm)))
  
  colnames(covm)[colnames(covm) %in% ''] <- 
    paste0('v',(1:ncol(covm))[colnames(covm) %in% ''])
  rownames(covm)[rownames(covm) %in% ''] <- 
    paste0('v',(1:nrow(covm))[rownames(covm) %in% ''])
  covm=data.frame(row=factor(rownames(covm),levels=rownames(covm)),covm)
  
  o=data.table::melt(data.table(covm),id.vars=c('row'))
  colnames(o)[colnames(o) %in% c('row','variable')] <- c('Var1','Var2')
  return(o)
}

# The one-step-ahead predicted observations and per-row log likelihood at the
# point estimate -- everything ctFitMelt()'s StatePred and Residuals sources
# are made of, and the only part of it that used to be stan-shaped.
#
# A stan fit already carries them under `transformedparsfull` (written when the
# fit was optimised with savescores), so that is read directly rather than
# recomputed. Otherwise -- a julia fit, or a stan fit whose scores were not
# saved -- ctKalmanArray() produces the same two arrays from the backend's own
# forward pass; for julia it dispatches to ctBackendKalman(). The two routes
# were checked against each other on a stan fit: ctKalmanArray()$yprior is
# transformedparsfull$ya[1,1,,] and the llrow matrices match, so which route a
# fit takes does not change what the panels show.
.ctFitMeltStates <- function(fit){
  tp <- fit$stanfit$transformedparsfull
  if(!is.null(tp$ya) && !is.null(tp$llrow)){
    return(list(yprior = array(tp$ya[1,1,,], dim = dim(tp$ya[1,1,,,drop=FALSE])[-1]),
      llrow = tp$llrow))
  }
  k <- suppressWarnings(suppressMessages(ctKalmanArray(fit, pointest = TRUE,
    subjectpars = FALSE)))
  list(yprior = k$yprior, llrow = k$llrow)
}

ctFitMelt <- function(fit, maxsamples='all'){
  if(!inherits(fit, c('ctStanFit','ctJuliaFit'))) stop('Not a ctsem fit object', call.=FALSE)

  # Both backends keep the prepared data under `$standata` and the model under
  # an accessor, so nothing below is stan-shaped any more. `$generated` is
  # written by ctGenerateFromFit(), which dispatches; `$priorpred` has to be
  # attached by the caller from ctGenerateFromPriors(), which is stan-only --
  # a julia fit therefore simply has no PriorPred source (ctFitCheck() says so
  # rather than leaving the panel silently absent).
  model <- .ctFitModelObject(fit)
  states <- NULL
  datasources <- c('Data','StatePred','Residuals')
  if(!is.null(fit$generated)) datasources <- c(datasources,'PostPred')
  if(!is.null(fit$priorpred)) datasources <- c(datasources,'PriorPred')

  datbase <- data.table(standatatolong(standata = fit$standata,origstructure = TRUE,ctm = model))
  datbase[ ,WhichObs:=(1:.N),by=eval(model$subjectIDname)]
  datbase <- data.frame(datbase)

  dat <- matrix(NA,nrow=0,ncol=0) #blank placeholder

  for(dsi in datasources){
    dexists <- FALSE
    if(dsi %in% c('Data','StatePred','Residuals') && is.null(states)){
      states <- .ctFitMeltStates(fit)
    }
    if(dsi == 'Data'){
      dexists<-TRUE
      d<-list()
      d$Y<- array(t(t(datbase[,(model$manifestNames)])), dim=c(1,dim(fit$standata$Y)))
      d$llrow <- states$llrow
    }

    if(dsi=='PriorPred'){
      dexists<-TRUE
      d <- fit$priorpred
    }
    if(dsi=='PostPred'){
      dexists<-TRUE
      d <- fit$generated
    }

    if(dsi== 'StatePred'){ #use kalman predictions
      dexists<-TRUE
      d<-list()
      d$Y<- states$yprior
      d$Y[rep(fit$standata$Y,each=dim(d$Y)[1])==99999] <- NA
      d$llrow <- states$llrow
    }

    if(dsi=='Residuals'){
      dexists<-TRUE
      d<-list()
      d$Y<- array(t(t(datbase[,(model$manifestNames)])), dim=c(1,dim(fit$standata$Y))) -
        states$yprior
      d$llrow <- states$llrow
    }

    if(dexists){
      if(maxsamples=='all') samples=1:dim(d$Y)[1] else samples = sample(1:dim(d$Y)[1],min(maxsamples,dim(d$Y)[1]))
      gdat <- data.table(datbase[rep(seq_len(nrow(datbase)), length(samples)),])

      gdat[, (model$manifestNames)]   <- #confusing aperm needed here, wish I understood why...
        data.table(matrix(aperm(d$Y[samples,,,drop=FALSE],c(2,1,3)), ncol=dim(d$Y)[3]))
      gdat$Sample=rep(samples,each=dim(d$Y)[2])
      gdat$LogLik<-c(d$llrow[samples,])
      gdat[[model$timeName]]<-rep(datbase[[model$timeName]],times=length(samples))
      gdat$DataSource <- dsi

      if(nrow(dat)==0) dat <- gdat else dat <- rbind(dat, gdat)
    }
  }

  return(dat)
}


#' Visual model fit diagnostics for ctsem fit objects.
#'
#' Plots the observed data against several model-implied distributions -- posterior
#' predictive, one step ahead state prediction, residuals, and optionally prior
#' predictive -- as bivariate relations against \code{by}, as covariance or
#' correlation heatmaps, and as an observed-versus-implied mean trajectory.
#' \code{ctCheckFit} is maintained as a backward-compatible alias.
#'
#' @param fit A fitted object from \code{\link{ctFit}}, from either backend.
#' @param data Include empirical data in plots?
#' @param postpred Include post predictive (conditional on estimated parameters and covariates) distribution data in plots? 
#' @param priorpred Include prior predictive (conditional on priors) distribution data in plots? 
#' @param statepred Include one step ahead (conditional on estimated parameters, covariates, and earlier data points) distribution data in plots? 
#' @param residuals Include one step ahead error (conditional on estimated parameters, covariates, and earlier data points) in plots? 
#' @param by Variable name to split or plot by. 'time', 'LogLik', and 'WhichObs' are also possibilities. 
#' @param TIpredNames Since time independent predictors do not change with time, by default observations after the first are ignored. 
#' For observing attrition it can be helpful to set this to NULL, or when the combinevars argument is used, specifying different names may be useful.
#' @param nsamples Number of samples (when applicable) to include in plots.
#' @param covplot Splits variables in the model by the 'by' argument, according to the number of breaks (breaks argument), 
#' and shows the covariance (or correlation) for the different data sources selected, as well as the differences between each pair. 
#' @param corr Turns the covplot into a correlation plot. Usually easier to make sense of visually. 
#' @param combinevars Can be a list of (possibly new) variable names, where each named element of the list contains a character vector 
#' of one or more variable names in the fit object, to combine into the one variable. By default, the mean is used, but see the aggfunc argument.
#'  The combinevars argument can also be used to ensure that only certain variables are plotted.  
#' @param fastcov Uses base R cov function for computing covariances. Not recommended with missing data.
#' @param aggfunc Function to use for aggregation, if needed.
#' @param aggregate If TRUE, duplicate observation types are aggregated over using aggfunc. For example,
#' if by = 'time' and there are 8 time points per subject, but breaks = 2, 
#' there will be 4 duplicate observation types per 'row' that will be collapsed. In most cases it is helpful to not collapse. 
#' @param groupbysplit Logical. Affects variable ordering in covariance plots. 
#' Defaults to FALSE, grouping by variable, and within variable by split.
#' @param byNA Logical. Create an extra break for when the split variable is missing?
#' @param lag Integer vector. lag = 1 creates additional variables for plotting, prefixed by 'lag1_', containing the prior row of observations
#' for that subject.
#' @param lagcovplot Logical. Output lagged covariance type plots?
#' @param smooth For bivariate plots, use a smoother for estimation?
#' @param k Integer denoting number of knots to use in the smoothing spline.
#' @param breaks Integer denoting number of discrete breaks to split variables by (when covariance plotting,
#' or for the `trajectoryplot` time axis).
#' @param entropy Still in development.
#' @param reg Logical. Use regularisation when estimating covariance matrices? Can be necessary / faster for some problems.
#' @param verbose Logical. If TRUE, shows optimization output when estimating covariances.
#' @param indlines Integer number of individual subject lines to draw per data type.
#' @param marginalcovcheck Logical. If TRUE, runs \code{\link{ctFitCheckCov}} at lag 0 (marginal,
#' not lagged, covariance or correlation), split by whether each observation falls in the early or
#' late half of that subject's own observed time range (a per-subject median split of \code{by},
#' not a split on absolute time across the sample -- with unbalanced start times, splitting on
#' absolute time would mix a subject's whole trajectory into a single side). Works for both stan
#' and julia backend fits, since \code{ctFitCheckCov} already supports both.
#' @param trajectoryplot Logical. If TRUE, plots observed means over time against the model's
#' implied (Kalman smoother) means over time, with a 95\% uncertainty band on the implied
#' trajectory. Reuses \code{\link{ctPredict}}/\code{\link{ctKalman}} (and, for julia fits,
#' \code{\link{ctBackendKalman}}) for both the implied trajectory and its uncertainty -- the
#' smoother covariance already computed and already used for the equivalent band in
#' \code{\link{plot.ctKalmanDF}} -- rather than computing an interval by some other route. Time is
#' discretised into \code{breaks} groups (as for \code{covplot}) since subjects are rarely
#' observed at identical times, and each group is plotted at its mean observed time. Works for
#' both stan and julia backend fits.
#'
#' @return Invisibly, a list with elements \code{plots} (every ggplot produced, named,
#' in the order printed), \code{data} (the long \code{data.table} the bivariate and
#' covariance panels were built from, or NULL if no classic panel was requested),
#' \code{covariances} (the covariance or correlation matrix per data source, when
#' \code{covplot=TRUE}), \code{marginalcov} and \code{trajectory} (the data behind
#' those two panels, when requested). The plots are printed as before, so
#' interactive use is unchanged; the return value is what lets a front end such as
#' ctsemGUI capture the panels instead of only the printed output.
#' @seealso \code{\link{ctFitCheckCov}}, the focused lagged-covariance diagnostic
#'   this dashboard delegates its \code{marginalcovcheck} panel to.
#' @aliases ctCheckFit
#' @export
#'
#' @examples
#' \donttest{
#' ctFitCheck(ctstantestfit)
#' }
ctFitCheck <- function(fit,
  data=TRUE, postpred=TRUE, priorpred=FALSE, statepred=FALSE, residuals=FALSE,
  by=NULL,
  TIpredNames=.ctFitModelObject(fit)$TIpredNames,
  nsamples=30, covplot=FALSE, corr=TRUE, combinevars=NA, fastcov=FALSE,
  lagcovplot=FALSE,
  aggfunc=mean,aggregate=FALSE,
  groupbysplit=FALSE, byNA=TRUE,lag=0,
  smooth=TRUE, k=4,breaks=4,entropy=FALSE,reg=FALSE,verbose=0, indlines=30,
  marginalcovcheck=FALSE, trajectoryplot=FALSE){

  # `by` defaults to the model's time variable, read through the
  # backend-agnostic accessor rather than `fit$ctstanmodelbase$timeName`
  # directly -- the latter is NULL for a julia fit, and this function accepts
  # one.
  if(is.null(by)) by <- .ctFitModelObject(fit)$timeName

  if(!inherits(fit, c('ctStanFit','ctJuliaFit'))) stop('Not a ctsem fit object', call.=FALSE)

  classicRequested <- data || postpred || priorpred || statepred || residuals ||
    covplot || entropy

  # Every panel below now reads the fit through the backend-agnostic accessors
  # (`$standata`, .ctFitModelObject(), .ctFitMeltStates()), so what used to be
  # a blanket refusal of julia fits is down to the one quantity that genuinely
  # has no julia route: the prior predictive. ctGenerateFromPriors() -- the only
  # thing that produces the `$priorpred` this reads -- is stan-only, so that
  # panel is skipped and named rather than left silently absent.
  if(priorpred && is.null(fit$priorpred)){
    if(inherits(fit, 'ctJuliaFit')){
      message('Skipping prior predictive panel: ctGenerateFromPriors(), which supplies fit$priorpred, does not support julia backend fits.')
    } else {
      message('Skipping prior predictive panel: attach prior draws first with fit$priorpred <- ctGenerateFromPriors(fit).')
    }
    priorpred <- FALSE
  }

  # The posterior predictive panel needs generated data, which is not part of a
  # fit until something asks for it. Generating here rather than dropping the
  # panel, the same way ctFitCheckCov() does, since postpred is on by default.
  if(postpred && is.null(fit$generated)){
    message('No generated data found, generating -- for faster repeated performance use ctGenerateFromFit first')
    fit <- ctGenerateFromFit(fit, nsamples = nsamples, cores = 1)
  }

  # Everything printed is also collected here, so a caller can have the panels
  # rather than only their side effects. Names are the panel titles.
  gglist <- list()
  covariances <- NULL
  meltdat <- NULL
  trajout <- NULL
  mcheckdat <- NULL
  .keep <- function(name, g){ gglist[[name]] <<- g; print(g) }

  if(classicRequested){
  ctmb <- .ctFitModelObject(fit)
  covORcor <- function(m){
    if(corr) return(cov2cor(m)) else return(m)
  }
  
  if(lagcovplot) covplot<-TRUE
  
  DataSource <-Sample<-Lag <- Row <- Sig. <- Sig <- NULL
  dat <- ctFitMelt(fit = fit,maxsamples = nsamples)
  
  
  byc=unique(c('Sample','WhichObs','DataSource',ctmb$timeName))
  bycid=c(ctmb$subjectIDname,byc)
  
  if(is.na(combinevars[1])){
    combinevars = setNames(
      colnames(dat)[!colnames(dat) %in% bycid],colnames(dat)[!colnames(dat) %in% bycid])
    # combinevars<-c(combinevars,LogLik='LogLik')
  }
  dat <- ctDataMelt(dat=dat,id=ctmb$subjectIDname, by=byc,combinevars = combinevars)
  dat$Sample <- factor(dat$Sample)
  dat$DataSource <- factor(dat$DataSource)
  
  
  wdat=dcast(dat,paste0(
    paste0(bycid,collapse='+'),
    '~variable'),value.var = 'value',fun.aggregate = mean,na.rm=TRUE)
  
  if(any(lag!=0)){ 
    if(aggregate){
      if(covplot){
        message('disabling aggregation -- incoherent with lags!')
        aggregate=FALSE
      }
    }
    prelagcols=colnames(wdat)[!colnames(wdat) %in% c(bycid,TIpredNames)]
    lagcols=(paste0("lag",  rep(lag, times = length(prelagcols)),'_',rep(prelagcols, each = length(lag))))
    
    wdat[, eval(lagcols) :=  
        shift(.SD, n=lag,type='lead'), by=c(ctmb$subjectIDname,'Sample','DataSource'),.SDcols=prelagcols]
  }
  
  if(covplot && by %in% names(combinevars)){ #then we need to make a copy for the splitting variable
    wdat[[paste0(by,'_split')]] <- wdat[[by]]
    by <- paste0(by,'_split')
  }
  
  dat <- melt(wdat,id.vars=unique(c(bycid,by)))
  
  if(!data) dat<-dat[!DataSource %in% 'Data']
  if(!priorpred) dat<-dat[!DataSource %in% 'PriorPred']
  if(!postpred) dat<-dat[!DataSource %in% 'PostPred']
  if(!statepred) dat<-dat[!DataSource %in% 'StatePred']
  if(!residuals) dat<-dat[!DataSource %in% 'Residuals']
  
  # if(!'WhichObs' %in% by) mdat$WhichObs <- NULL
  
  dat = dat[!is.na(value),]
  
  
  
  breaks = min(breaks,length(unique(dat[[by]][!is.na(dat[[by]])])))
  # k = min(k,length(unique(dat[[by]][!is.na(dat[[by]])]))-1)
  
  if(covplot ||entropy){
    discdat=dat #make copy for use in covs
    discdat[variable %in% TIpredNames & WhichObs > 1] <- NA #remove later tipreds to avoid duplicate cov columns
    
    nontivars <- unique(discdat$variable)[!unique(discdat$variable) %in% TIpredNames]
    
    if(requireNamespace('arules')){
      discdat[[paste0(by)]] <- arules::discretize(dat[[by]], #discretize
        method='cluster',breaks = breaks,labels=FALSE)
    } else stop('arules package needed for discretization!')
    
    if(covplot){
      corlist <- list()
      datasources <- as.character(unique(dat$DataSource))
      for(dsi in unique(dat$DataSource)){ #make wide discretized data and get cov
        
        wdat <- dcast(discdat[DataSource==dsi],
          paste0(
            ctmb$subjectIDname,
            '+Sample',
            if(!aggregate) '+WhichObs', #this caused problems, why was it in?
            '~variable + ', by),fun.aggregate=aggfunc,na.rm=TRUE)
        
        
        #put loglik on one side
        if('LogLik_1' %in% colnames(wdat)) wdat <- cbind(wdat[,colnames(wdat) %in% paste0('LogLik_',1:breaks),with=FALSE],
          wdat[,!colnames(wdat) %in% paste0('LogLik_',1:breaks),with=FALSE])
        
        if(byNA) breakset <-c(1:breaks,NA) else breakset=1:breaks #some values can't be placed in a by column if by = NA
        
        if(groupbysplit){
          colorder <- unlist(lapply(breakset, function(b) grep(paste0('\\_',b,'$'),x=colnames(wdat))))
          wdat <- wdat[,colorder,with=FALSE]
        } else if(!byNA) wdat <- wdat[,-grep('\\_NA%',colnames(wdat)),with=FALSE] #if not seperating by group, still remove NA by relations if needed
        
        sapply(TIpredNames,function(x){ #fix tipred column names
          if(paste0(x,'_1') %in% colnames(wdat)){
            colnames(wdat)[ colnames(wdat) %in% paste0(x,'_1')] <<- x
          }
        })
        if(breaks==1) colnames(wdat) <- gsub("\\_\\d+$","",colnames(wdat))
        wdat <- cbind(wdat[,c(which(colnames(wdat) %in% TIpredNames), which(!colnames(wdat) %in% TIpredNames)),with=FALSE])
        
        if(!fastcov) corlist[[dsi]] <- covml(
          data.frame(wdat)[,!colnames(wdat) %in% c('Sample',ctmb$subjectIDname),drop=FALSE],
          reg=reg,
          verbose=verbose)$cp$covm
        
        if(fastcov) corlist[[dsi]] <- cov(
          data.frame(wdat)[,!colnames(wdat) %in% c('Sample',ctmb$subjectIDname),drop=FALSE],
          use='pairwise.complete.obs')
        
        if(corr) corlist[[dsi]] <- cov2cor(corlist[[dsi]])
        
        # if(covsplitdiffs){
        #   
        #   splitcovs <- plyr::laply(breakset[!is.na(breakset)], function(b){
        #     corlist[[dsi]][,colnames(corlist[[dsi]]) %in% c(TIpredNames, paste0(nontivars,'_',b)), drop=FALSE]
        #   })
        #   commonnames <- x
        #   splitcovs <- x
        #   cplot=corplotmelt(meltcov(corlist[[datasources[i]]]),
        #     label=paste0(' corr.'),limits=c(-1,1))
        #   cplot = cplot + ggplot2::labs(title=paste0(datasources[i],' correlations, split by ', by))
        #   print(cplot)
        # }
        
      } #finish datasource loop
      
      covariances <- corlist
      if(corr) covplotlims <- c(-1,1) else covplotlims <- NA
      
      if(!lagcovplot){
        for(i in seq_along(corlist)){ #regular corplots
          cplot=corplotmelt(meltcov(covORcor(corlist[[datasources[i]]])),
            label=paste0(ifelse(corr,'Corr.','Cov.')),limits=covplotlims)
          cplottitle <- paste0(datasources[i],
            ifelse(corr,' correlations',' covariances'),if(breaks > 1) paste0(', split by ', by))
          cplot = cplot + ggplot2::labs(title=cplottitle)
          .keep(cplottitle, cplot)
        }
        for(i in seq_along(corlist)){
          for(j in seq_along(corlist)){ #difference corplots
            if(j > i){ #only plot unique differences
              coli <- colnames(corlist[[datasources[i]]])[
                colnames(corlist[[datasources[i]]]) %in% colnames(corlist[[datasources[j]]])
              ]
              cplot=corplotmelt(meltcov(corlist[[datasources[i]]][coli,coli,drop=FALSE] - 
                  corlist[[datasources[j]]][coli,coli,drop=FALSE]),
                label=paste0(ifelse(corr,'Corr.','Cov.'),' diff.'),limits=covplotlims)
              cplottitle <- paste0(datasources[i],' - ',datasources[j],
                ifelse(corr,' correlations',' covariances'),if(breaks > 1) paste0(', split by ', by))
              cplot = cplot + ggplot2::labs(title=cplottitle)
              .keep(cplottitle, cplot)
            }
          }
        }
      }
      
      if(lagcovplot){
        for(ci in seq_along(corlist)){
          if(ci==1) lagdat <-data.frame(corlist[[ci]],DataSource = names(corlist)[ci], 
            Row=rownames(corlist[[ci]])) else{
              lagdat <- rbind(lagdat,data.frame(corlist[[ci]],
                DataSource = names(corlist)[ci],Row=rownames(corlist[[ci]])))
            }
        }
        lagdat$Lag <- 0
        l=regmatches(x = lagdat$Row,m = regexpr(pattern = '^lag\\d+_',lagdat$Row))
        l=gsub('lag','',l)
        l=gsub('\\_','',l)
        lagdat$Lag[grepl('^lag\\d+\\_',lagdat$Row)] <- as.numeric(l)
        lagdat <- lagdat[,-grep('^lag\\d+\\_',colnames(lagdat))]
        lagdat$Row <- gsub('^lag\\d+\\_','',lagdat$Row)
        lagdat <- melt(data.table(lagdat),id.vars = c('Row','Lag','DataSource'))
        lagdat$variable <- gsub('\\_1$','',lagdat$variable)
        lagdat <- lagdat[!lagdat$Row %in% TIpredNames,]
        
        combinevars <- combinevars[!names(combinevars) %in% c(TIpredNames,by)] #because discretized / not in cov
        
        for(vi in names(combinevars)){    
          g=ggplot(data = lagdat[lagdat$variable %in% vi,],
            mapping = aes(x=Lag,y=value,colour=DataSource, linetype=DataSource))+geom_line(linewidth=1)+
            facet_wrap(facets = vars(Row))+theme_minimal()+ylab(label = ifelse(corr,'Correlation','Covariance'))+
            scale_y_continuous(minor_breaks = c(-.5,.5),breaks=seq(-1,1,1))+
            scale_x_continuous(minor_breaks=NULL,breaks=seq(0,max(lag), ceiling(max(lag)/5)))+
            ggtitle(label = paste0(vi,' ',ifelse(corr,'Correlations','Covariances')))
          if(corr) g <- g+coord_cartesian(ylim=c(-1,1))
          .keep(paste0(vi,' ',ifelse(corr,'Correlations','Covariances'),' by lag'), g)
          # if('try-error' %in% class(g) ) browser()
        }
        
        
      }
      
    }
    # if(entropy){
    #   # 
    #   dentropy <- -mean(covdat$cp$llrow)#lp/nrow(wdat)
    #   
    #   gdentropy <- sapply(unique(wgdat$Sample), function(x){
    #     print(x)
    #     -mean(covml(data.frame(wgdat)[wgdat$Sample==x,!colnames(wgdat) %in% 
    #         c('Sample',ctmb$subjectIDname)],verbose=verbose)$cp$llrow)
    #   }) 
    #   print(sum(covdat$cp$llrow))
    #   message('Entropy: Fit = ', -sum(fit$stanfit$transformedparsfull$ll)/nrow(wdat),'; Data = ',dentropy,'; Mean gen.data = ',mean(gdentropy),'  SD gen. data = ',sd(gdentropy))
    # }
  }
  
  if(!covplot){ #then plot bivariate relations
    vars <- names(combinevars)
    if(any(lag>0)) vars <- c(vars,lagcols)
    dat$manifest <- dat$variable %in% vars
    
    
    g=ggplot(
      data = dat[manifest == TRUE],
      mapping = aes(
        x = .data[[by]],
        y = value,
        colour = DataSource,
        fill   = DataSource
      )
    ) +theme_bw() +
      # scale_color_brewer(palette = 'Set1') +
      # scale_fill_brewer(palette = 'Set1')
      # +
      scale_colour_manual(values = c("blue", "red","green",  "Orange","Black"))+
      scale_fill_manual(values = c("blue", "red","green",  "Orange",'Black'))#+
    # scale_alpha_manual(values = c(1, max(.05,(.3/nsamples)),max(.05,(.3/nsamples)),1))
    
    if(smooth) {
      # g = g + geom_smooth(data=dat[manifest==TRUE & !DataSource %in% c('Data','StatePred','Residuals')],
      #   aes(group=Sample),
      #   alpha= max(.05,(.3/nsamples)),
      #   linetype=0,#3,#ifelse(nsamples==1,1,0),
      #   stat="smooth",#se = FALSE,#nsamples==1,
      #   linewidth=.1
      #   ,method='gam', formula= as.formula(paste0('y ~ s(x,bs="cr",k=',k,')')))
      
      g = g + geom_smooth(data=dat[manifest==TRUE 
        # & DataSource %in% c('Data','StatePred','Residuals')
      ],
        # aes(colour=DataSource,alpha=NULL),
        stat="smooth",se = TRUE,linewidth=1,alpha=.3
        ,method='gam', formula= as.formula(paste0('y ~ s(x,bs="cr",k=',k,')')))
      
      
      
    }
    if(!smooth) {
      # if(nsamples > 1) g = g + stat_summary(fun=mean,geom = "line",linewidth=1) #geom_line(stat=mean)
      
      # if(nsamples ==1)
      # g = g +  stat_summary(data=dat[manifest==TRUE 
      #   & !DataSource %in% c('Data','StatePred','Residuals')],
      #   aes(group=Sample),
      #   fun.data = function(x) list(y=mean(x),
      #     ymin=mean(x,na.rm=TRUE)-sd(x)/sqrt(length(x)), 
      #     ymax=mean(x)+sd(x)/sqrt(length(x))),
      #   geom = "ribbon",
      #   alpha= max(.05,max(.05,sqrt(.2/nsamples))),
      #   linetype=ifelse(nsamples==1,1,0))
      
      g = g +  stat_summary(data=dat[manifest==TRUE 
        # & DataSource %in% c('Data','StatePred','Residuals')
      ],
        fun.data = function(x) list(y=mean(x),
          ymin=mean(x,na.rm=TRUE)-sd(x)/sqrt(length(x)), 
          ymax=mean(x)+sd(x)/sqrt(length(x))),
        geom = "ribbon",alpha=.3)
    }
    
    if(indlines > 0){
      individualInt <- eval(parse(text=paste0('interaction(dat$',ctmb$subjectIDname,',dat$Sample, dat$DataSource)')))
      dat$individualInt <- individualInt
      ids <- unique(dat[[ctmb$subjectIDname]])
      ids=sample(ids,  min(indlines,length(ids)),replace = FALSE)
      ids <- unlist(lapply(unique(dat$DataSource),function(ds){
        dat$individualInt[dat$DataSource %in% ds][ 
          match(ids, dat[[ctmb$subjectIDname]][dat$DataSource %in% ds])]
      }))
      g = g + geom_line(data=dat[manifest==TRUE &dat$individualInt %in% ids],
        mapping = aes(group=individualInt),
        alpha= max(.2,(.8/sqrt(indlines))),
        linetype=1,#3,#ifelse(nsamples==1,1,0),
        # stat="smooth",#se = FALSE,#nsamples==1,
        linewidth=.1
        # ,method='gam', formula= as.formula(paste0('y ~ s(x,bs="cr",k=',k,')'))
      )
      
    }
    g=g+facet_wrap(facets = vars(variable),scales = 'free')+theme(legend.position = 'bottom')
    .keep(paste0('Bivariate relations by ', by), g)
  }
  meltdat <- dat
  } # end if(classicRequested)

  if(marginalcovcheck){
    ctmb <- .ctFitModelObject(fit)
    idname <- ctmb$subjectIDname
    covdat <- as.data.table(.ctFitLongData(fit))
    if(!by %in% names(covdat)) stop('marginalcovcheck requires `by` to name a column present in the fitted data: ', by)
    splitname <- '.ctFitCheckPeriod'
    # A per-subject median split -- each subject's own early half against its
    # own late half -- not a split on absolute time across the sample. With
    # unbalanced start times or staggered designs, splitting on absolute time
    # would put a subject's whole trajectory on one side, which is not what
    # "early vs late" means for panel data; ctFitCheckCov's own documentation
    # (see its `splitby` examples) does exactly this per-subject split.
    covdat[, (splitname) := ifelse(get(by) <= stats::median(get(by), na.rm=TRUE), 'Early', 'Late'), by = idname]
    mcheckdat <- ctFitCheckCov(fit, cor = corr, plot = FALSE, data = covdat,
      splitby = splitname, splitdata = covdat, split = 'factor', lags = 0,
      nsamples = nsamples)
    mcheck <- ctFitCovCheckPlot(mcheckdat, maxlag = 0, splitvar = splitname,
      cor = corr)
    for(gi in seq_along(mcheck)){
      .keep(paste0('Marginal covariance check: ', names(mcheck)[gi]), mcheck[[gi]])
    }
  }

  if(trajectoryplot){
    traj <- .ctFitCheckTrajectory(fit, by = by, breaks = breaks)
    trajout <- traj
    emp <- traj$observed
    imp <- traj$implied

    Row <- TimeMid <- Mean <- q025 <- q975 <- NULL # local variables for ggplot
    g <- ggplot() +
      geom_ribbon(data = imp, aes(x = TimeMid, ymin = q025, ymax = q975), alpha = .2) +
      geom_line(data = imp, aes(x = TimeMid, y = Mean, colour = 'Model implied (smoothed)')) +
      geom_point(data = emp, aes(x = TimeMid, y = Mean, colour = 'Observed'), size = 2) +
      geom_line(data = emp, aes(x = TimeMid, y = Mean, colour = 'Observed'), linetype = 'dashed') +
      facet_wrap(facets = vars(Row), scales = 'free_y') +
      theme_bw() + theme(legend.position = 'bottom') +
      labs(x = by, y = 'Mean', colour = NULL,
        title = 'Observed vs model-implied mean trajectory (95% band from Kalman smoother uncertainty)')
    .keep('Observed vs model-implied mean trajectory', g)
  }

  invisible(list(plots = gglist, data = meltdat, covariances = covariances,
    marginalcov = mcheckdat, trajectory = trajout))
}

#' @export
ctCheckFit <- ctFitCheck

# Observed vs model-implied (Kalman smoother) mean trajectory over time, for
# ctFitCheck(trajectoryplot=TRUE). Factored out of ctFitCheck() so the
# computation -- not just "did the plot error" -- can be tested directly.
#
# Reuses ctPredict()/ctKalman() for both the smoothed implied values and their
# per-observation uncertainty (the same Kalman smoother covariance that
# plot.ctKalmanDF already bands at errormultiply=1.96), rather than inventing
# a new uncertainty route. Subjects are rarely observed at identical times, so
# the time axis is discretised into `breaks` groups the same way ctFitCheck's
# covplot does, and each group is plotted at its mean observed time; the
# implied band at each bin combines the individual Kalman smoother variances
# averaged into that bin via the standard sd-of-a-mean rule.
#
# Works for both stan and julia fits, since ctPredict()/ctKalman() already do.
.ctFitCheckTrajectory <- function(fit, by, breaks){
  idmap <- .ctFitIdMap(fit)
  k <- as.data.table(ctPredict(fit, subjects = idmap[,1], timestep = 'asdata',
    removeObs = FALSE, plot = FALSE))
  k <- k[Element %in% c('y','ysmooth')]
  if(!requireNamespace('arules', quietly = TRUE)) stop('arules package needed for discretization!')
  breaksn <- min(breaks, length(unique(k$Time[!is.na(k$Time)])))
  k[, .TimeBin := arules::discretize(Time, method = 'cluster', breaks = breaksn, labels = FALSE)]
  binmid <- k[, .(TimeMid = mean(Time, na.rm = TRUE)), by = .TimeBin]

  emp <- k[Element == 'y', .(Mean = mean(value, na.rm = TRUE)), by = .(Row, .TimeBin)]
  emp <- merge(emp, binmid, by = '.TimeBin')

  imp <- k[Element == 'ysmooth', .(Mean = mean(value, na.rm = TRUE),
    se = sqrt(mean(sd^2, na.rm = TRUE) / sum(!is.na(value)))), by = .(Row, .TimeBin)]
  imp <- merge(imp, binmid, by = '.TimeBin')
  imp[, `:=`(q025 = Mean - 1.96*se, q975 = Mean + 1.96*se)]

  list(observed = emp, implied = imp)
}


corplotmelt <- function(corm, label='Coef.',limits=NA,title=''){
  
  if(is.na(limits[1])) limits <- range(corm[,'value'],na.rm=TRUE)
  ggplot(data=(corm),aes(x=Var1,y=Var2,fill=(value)))+ #ifelse(groups,NULL,'Group')))+
    geom_tile( width=1,height=1,colour='black')+
    scale_fill_gradient2(low = "blue", high = "red", mid = "white",
      midpoint = limits[2]-(limits[2]-limits[1])/2, limits = limits, space = "Lab", 
      name=label)  +
    theme_minimal()+ theme(axis.text.x = element_text(angle = 90),legend.position = 'bottom') + ggtitle(title)+
    scale_x_discrete(position = "top")+scale_y_discrete(limits=rev)
}


