#' ctStanPlotPost
#'
#' Plots posterior of subject level parameters for free model parameters in a \code{\link{ctStanModel}} resulting from the specified transformations.
#' 
#' @param ctstanmodelobj model object as generated by \code{\link{ctModel}} using one of the Stan type arguments.
#' @param ctstanfitobj fit object as generated by \code{\link{ctStanFit}}.
#' @param rows vector of integers denoting which rows of ctstanmodelobj$parameters to plot priors for. 
#' Character string 'all' plots all rows with parameters to be estimated.
#' @param wait If true, user is prompted to continue before plotting next graph.  If false, graphs are plotted one after another without waiting.
#' @export

ctStanPlotPost<-function(ctstanmodelobj,ctstanfitobj, rows='all',wait=FALSE){
  
  s<-extract(ctstanfitobj)
  m<-ctstanmodelobj$parameters
  if(rows=='all') rows<-1:nrow(m)
  snames<-names(s)
  hmeannames<-snames[grep('output_hmean_',snames)]
  hsdnames<-snames[grep('output_hsd_',snames)]
  tipnames<-snames[grep('output_tip_',snames)]
  sum<-getMethod('summary','stanfit')(ctstanfitobj)
  sumnames<-dimnames(sum$summary)[[1]]
  nsubjects<-max(  as.numeric(unlist(lapply(grep('^indparams[[]',sumnames),function(x){
    strsplit(gsub("[^0-9,]", "", sumnames[x]), ",")[[1]][1]
  }))))
  if(nsubjects < 1) nsubjects<-1
  
  
  indvaryingcount<-0
  hypermeancount<-0
  pmeans<-matrix(NA,nrow=nsubjects,ncol=sum(m$indvarying))
  pnames<-rep(NA,sum(m$indvarying))
  for(rowi in rows){
    if(is.na(m$value[rowi])){
      hypermeancount <- which(m$param[is.na(m$value)] %in% m$param[rowi])
      if(m$indvarying[rowi]){
        
        indvaryingcount<-which(m$param[is.na(m$value) & m$indvarying] %in% m$param[rowi])
        hypermean<- s$hypermeans[,hypermeancount]
        
        hypersd<-eval(parse(text=gsub('sdscale[rowi]' ,'m$sdscale[rowi]', #loghypersd samples
          gsub('loghypersd[rowi]','s$loghypersd[,indvaryingcount]',
            ctstanmodelobj$loghypersdtransform,fixed=TRUE),fixed=TRUE)))

        indparams<-s[['indparams']][,1:nsubjects,indvaryingcount]
        
        param<-indparams
        dindparams<-ctDensity(eval(parse(text=paste0(m$transform[rowi]))))
        param<-rnorm(50000,hypermean,hypersd)
        dsubjectprior<-ctDensity(eval(parse(text=paste0(m$transform[rowi]))))
        param<-rnorm(50000,0,1)
        meanprior <- eval(parse(text=paste0(m$transform[rowi])))
        meanprior <- meanprior[meanprior > dsubjectprior$xlim[1]-5 & meanprior < dsubjectprior$xlim[2] + 5]
        dmeanprior<-ctDensity(meanprior)

        plot(dindparams$density,xlab='Value',main=m$param[rowi],lwd=2,yaxs='i',
          ylim=c(0,max(dsubjectprior$ylim[2],dindparams$ylim[2])),
          xlim=c(min(dsubjectprior$xlim[1],dindparams$xlim[1]),max(dsubjectprior$xlim[2],dindparams$xlim[2])))
        points(dsubjectprior$density,col='red',lwd=2,lty=2,type='l')
        points(dmeanprior$density,lwd=2,type='l',col='blue',lty=3)
        legend('topright',c('Subject param posterior','Subject param prior','Pop mean prior'),
          text.col=c('black','red','blue'),bty='n')
        
        #pre-transform hyper std dev
        dloghypersdpost<-ctDensity(hypersd)
        
        loghypersdprior<-  eval(parse(text=gsub('normal(', 'rnorm(50000,',ctstanmodelobj$loghypersdprior,fixed=TRUE)))
        hypersdprior<-eval(parse(text=gsub('sdscale[rowi]' ,'m$sdscale[rowi]', #loghypersd samples
          gsub('loghypersd[rowi]','loghypersdprior',
            ctstanmodelobj$loghypersdtransform,fixed=TRUE),fixed=TRUE)))
        dloghypersdprior<-ctDensity(hypersdprior)

        plot(dloghypersdpost$density,main=paste0('Pre-tform pop. sd ',m$param[rowi]),xlab='Value',lwd=2,
          xlim=c(min(dloghypersdprior$xlim[1],dloghypersdpost$xlim[1]),max(dloghypersdprior$xlim[2],dloghypersdpost$xlim[2])),
          ylim=c(0,max(dloghypersdprior$ylim[2],dloghypersdpost$ylim[2])),
          xaxs='i',yaxs='i')
        points(dloghypersdprior$density,col='blue',type='l',lty=2,lwd=2)
        legend('topright',c('Pop. sd posterior','Pop. sd prior'),
          text.col=c('black','blue'),bty='n')
        
        #post-transform hyper std dev
        hsdpost <- s[[paste0('output_hsd_',m$param[rowi])]]
        dhsdpost<-ctDensity(hsdpost)
        
        param<-hypermean+hypersdprior*.01
        high<-eval(parse(text=paste0(m$transform[rowi])))
        param<-hypermean-hypersdprior*.01
        low<-eval(parse(text=paste0(m$transform[rowi])))
        hsdprior<-abs(high - low)/2*100

        dhsdprior<-ctDensity(sample(hsdprior,50000,replace=TRUE))
        plot(dhsdpost$density,main=paste0('Pop. sd ',m$param[rowi]),xlab='Value',lwd=2,
          ylim=c(0,max(dhsdpost$ylim[2],dhsdprior$ylim[2])),
          xlim=c(min(dhsdprior$xlim[1],dhsdpost$xlim[1]), max(dhsdprior$xlim[2],dhsdpost$xlim[2])),
            yaxs='i',xaxs='i')
        points(dhsdprior$density,col='blue',type='l',lty=2,lwd=2)
        legend('topright',c('Pop. sd posterior','Pop. sd prior'),
          text.col=c('black','blue'),bty='n')
        
        param<-hypermean
        dhypermeanpost<-ctDensity(eval(parse(text=paste0(m$transform[rowi]))))
        plot(dhypermeanpost$density,main=paste0('Pop. mean ',m$param[rowi]),
          xlim=dhypermeanpost$xlim,
          ylim=c(0,dhypermeanpost$ylim[2]),
          xlab='Value',lwd=2,xaxs='i',yaxs='i')
        points(dmeanprior$density,col='blue',type='l',lty=2,lwd=2)
        legend('topright',c('Pop. mean posterior','Pop. mean prior'),
          text.col=c('black','blue'),bty='n')
        
        
        
        pmeans[,indvaryingcount]<-sum$summary[sumnames %in% 
            paste0(m$matrix[rowi],'[',1:nsubjects,',',m$row[rowi],
                  if(!(m$matrix[rowi] %in% c('T0MEANS','CINT','MANIFESTMEANS'))) paste0(',',m$col[rowi]),']'),
          1]
        
        pnames[indvaryingcount]<-paste0(m$matrix[rowi],'[',m$row[rowi],',',m$col[rowi],']')
        
       
        if(wait==TRUE & rowi != tail(rows,1)){
          message("Press [enter] to display next plot")
          readline()
        }
      }
    }
  }
  
  if(length(rows)>1){
    require(lattice)
    colnames(pmeans)<-pnames
    splom(pmeans,
      upper.panel=function(x,y) panel.loess(x, y),
      diag.panel = function(x,...){
        yrng <- current.panel.limits()$ylim
        d <- density(x, na.rm=TRUE)
        d$y <- with(d, yrng[1] + 0.95 * diff(yrng) * y / max(y) )
        panel.lines(d)
        diag.panel.splom(x,...)
      },
      lower.panel = function(x, y, i,j){
        panel.splom(x,y,col=rgb(0,0,1,alpha=.2),pch=16)
        
        if( j==1)  panel.axis(side=c('left'),outside=T,
          at=round(seq(max(y),min(y),length.out=5)[c(-1,-5)],digits=3),tck=1,
          labels=round(seq(max(y),min(y),length.out=5)[c(-1,-5)],digits=3))
        
        if( i==ncol(pmeans))  panel.axis(side=c('bottom'),outside=T,
          at=round(seq(max(x),min(x),length.out=5)[c(-1,-5)],digits=3),tck=1,
          labels=round(seq(max(y),min(y),length.out=5)[c(-1,-5)],digits=3))
      },
      pscales=0,
      as.matrix = TRUE,
      varname.cex=.4,
      strip=T,
      main='Subject level parameter plots',
      xlab=NULL,ylab=NULL,
      col=rgb(0,0,1,alpha=.2),pch=16
    )
  }
  
  
 
  
  
  
  
}

