#' ctStanPlotPriors
#'
#' Plots priors for free model parameters in a \code{\link{ctStanModel}} resulting from the specified transformations.
#' 
#' @param ctstanmodelobj model object as generated by \code{\link{ctModel}} with type='stanct' or 'standt'.
#' @param rows vector of integers denoting which rows of ctstanmodelobj$parameters to plot priors for. 
#' Character string 'all' plots all rows with parameters to be estimated.
#' @param wait If true, user is prompted to continue before plotting next graph.  If false, graphs are plotted one after another without waiting.
#' @export

ctStanPlotPriors<-function(ctstanmodelobj,rows='all',wait=TRUE){
  m<-ctstanmodelobj$parameters
  n<-500000
  if(rows=='all') rows<-1:nrow(m)
  for(rowi in rows){
    param<-rnorm(n)
    if(is.na(m$value[rowi])){
    plot(density(eval(parse(text=paste0(m$transform[rowi]))),bw=.05,n=5000),main=m$param[rowi],lwd=2)
      param<-rep(-1,n)+rnorm(n,0,m$sdscale[rowi])
      points(density(eval(parse(text=paste0(m$transform[rowi]))),bw=.05,n=5000),type='l',col='blue')
      param<-rep(1,n)+rnorm(n,0,m$sdscale[rowi])
      points(density(eval(parse(text=paste0(m$transform[rowi]))),bw=.05,n=5000),type='l',col='red')
      legend('topright',c('pop mean prior', '-1sd mean, 2sd','+1sd mean, 2sd'),text.col=c('black','blue','red'),bty='n')
      if(wait==TRUE & rowi != tail(rows,1)){
        message("Press [enter] to display next plot")
        readline()
      }
    }
  }
}
