# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.ctsemCppBuild <- function(spec) {
    .Call(`_ctsem_ctsemCppBuild`, spec)
}

.ctsemCppNpars <- function(handle) {
    .Call(`_ctsem_ctsemCppNpars`, handle)
}

.ctsemCppEvaluate <- function(handle, pars, gradient = TRUE, contributions = FALSE) {
    .Call(`_ctsem_ctsemCppEvaluate`, handle, pars, gradient, contributions)
}

.ctsemCppOptimize <- function(handle, start, maxiter = 1000L, gtol = 1e-8) {
    .Call(`_ctsem_ctsemCppOptimize`, handle, start, maxiter, gtol)
}

.ctsemCppSubjectGradients <- function(handle, pars) {
    .Call(`_ctsem_ctsemCppSubjectGradients`, handle, pars)
}

.ctsemCppLayout <- function(handle) {
    .Call(`_ctsem_ctsemCppLayout`, handle)
}

